### ISSUE TITLE
[Feature] 指定连接IPv6链路本地地址时使用的设备名

### ISSUE THREAD

**Issue by UjuiUjuMandan** [MetaCubeX/mihomo#1001]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在局域网中，我想要访问另一台设备的链路本地地址如 fe80::2:705d:55ee:229d ，需要指定所使用设备名称，比如 wlan0 。

对于 curl ，使用方式为
```
curl -v http://[fe80::2:705d:55ee:229d%wlan0]:7654
```
或
```
curl -v http://[fe80::2:705d:55ee:229d]:7654 --interface wlan0
```
对于 netcat ，使用方式为
```
nc -v fe80::2:705d:55ee:229d%wlan0 7654
```

对于 ping ，使用方式为
```
ping6 fe80::2:705d:55ee:229d%wlan0
```
或
```
ping6 -I wlan0 fe80::2:705d:55ee:229d
```

参考：

1. https://unix.stackexchange.com/questions/520264/unable-to-ping-ipv6-device-with-linklocal-address
2. https://unix.stackexchange.com/questions/423534/how-do-i-get-the-pingable-ipv6-address-of-my-machine
3. https://stackoverflow.com/questions/31446953/how-do-i-access-the-web-server-or-website-using-link-local-ipv6-address

### Possible Solution

1. 解析 server 设置项的 % 后的字符作为设备名。
2. 添加新设置项 interface 。

**Comment by ccmuyuu** [comment]
写个rule不就能实现指定interface了
