### ISSUE TITLE
[Bug] TProxy server error since upgrade to 1.8.1

### ISSUE THREAD

**Issue by iMxSeraph** [MetaCubeX/mihomo#1027]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.8.1

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
mixed-port: 7890
tproxy-port: 7893
allow-lan: true
bind-address: '192.168.1.2'
mode: rule
log-level: info
ipv6: true
external-controller: 192.168.1.2:9090

rules:
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

dns:
  enable: true
  listen: 192.168.1.2:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  nameserver:
    - 192.168.1.3
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - https://45.11.45.11/dns-query
  
proxies:
  - name: yun
    type: http
    server: 192.168.1.1
    port: 7890

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - yun
```

### Mihomo log

```shell
INFO[2024-02-06T16:58:23.555388451+08:00] Start initial configuration in progress      
INFO[2024-02-06T16:58:23.555592948+08:00] Geodata Loader mode: memconservative         
INFO[2024-02-06T16:58:23.555610996+08:00] Geosite Matcher implementation: succinct     
INFO[2024-02-06T16:58:23.573838419+08:00] Initial configuration complete, total time: 18ms 
INFO[2024-02-06T16:58:23.575627358+08:00] RESTful API listening at: 192.168.60.2:9090  
INFO[2024-02-06T16:58:23.63960607+08:00] Sniffer is closed                            
INFO[2024-02-06T16:58:23.639786475+08:00] DNS server listening at: 192.168.60.2:53     
ERRO[2024-02-06T16:58:23.639870333+08:00] Start TProxy server error: protocol not available 
INFO[2024-02-06T16:58:23.639963556+08:00] Mixed(http+socks) proxy listening at: 192.168.60.2:7890 
INFO[2024-02-06T16:58:23.643495057+08:00] Start initial Compatible provider PROXY      
INFO[2024-02-06T16:58:23.643564792+08:00] Start initial Compatible provider default
```

### Description

Based on the same config file, 1.8.0 TProxy could work. But under 1.8.1, the log shows TProxy server start error. "Start TProxy server error: protocol not available "

I'm using mihomo-linux-amd64-compatible-v1.18.1 on Debian 12. (Linux gate 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux)

Same issue happened on the latest alpha version.

**Comment by Lovest20018** [comment]
同样的问题。最新alpha也一样。

**Comment by Lovest20018** [comment]
可以了。

**Comment by iMxSeraph** [comment]
It works. Thanks a lot :)
