### ISSUE TITLE
[Feature] please add english mode on wiki website

### ISSUE THREAD

**Issue by matamatmatew** [MetaCubeX/mihomo#1029]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

to make it easier to configure in universal languages, you don't always have to go through the translate app.  please add universal language

### Possible Solution

please add universal language

**Comment by xishang0128** [comment]
The English version has been added, translated using GPT. If there are any issues, please initiate a PR for the document
