### ISSUE TITLE
Hysteria 2协议的链式代理不可用[Feature] 

### ISSUE THREAD

**Issue by Kingroyal78** [MetaCubeX/mihomo#1035]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

链式代理的所有协议都是hysteria 2协议，查看log 提示 not support。

**Comment by Kingroyal78** [comment]
> 你用的relay还是dialer-proxy

用的relay

**Comment by PuerNya** [comment]
@Kingroyal78 请使用 dialer-proxy

**Comment by Kingroyal78** [comment]
> dialer-proxy



> @Kingroyal78 请使用 dialer-proxy

喔喔，好的

**Comment by W3XA56Y3RDUKBS** [comment]
> @Kingroyal78 请使用 dialer-proxy

  请问dialer-proxy和relay的区别是什么呀？

**Comment by wwqgtxx** [comment]
> > @Kingroyal78 请使用 dialer-proxy
> 
> 请问dialer-proxy和relay的区别是什么呀？

区别就是不要用relay，早晚会废弃的
