### ISSUE TITLE
[Bug] 如果不是作为网关，客户端自己配置文件中Fake-ip需要设置

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/mihomo#1037]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

最新

### Mihomo config

```yaml
enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
```

### Description

傻瓜配置里这一段

  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
我目前配置文件里没有这一段。
我看了一些文章，似乎这个是用在透明网关上的。我就是想确认下，如果我只是pc、mac、移动设备上用，有必要设置么？带来的好处是什么呢？

请解惑！谢谢

**Comment by Paulgudring** [comment]
tun模式也可以用。移步discussion。

**Comment by xishang0128** [comment]
这不是一个正常的bug反馈,该issues将被关闭
