### ISSUE TITLE
geosite未命中域名的ipv6解析未成功仅分流到nameserver

### ISSUE THREAD

**Issue by whatagoodboy** [MetaCubeX/mihomo#104]
核心版本：1.11.2，alpha-6664547 均能复现
APP：merlinclash 22.05.20-003
DNS服务器：两个自建adguardhome服务器，一个用于nameserver解析国内DNS1，一个用于fallback解析国外DNS2
配置：
开启merlinclash ipv6代理+tproxy tcp/udp
sniffer：开启，配置默认
tcp并发：开启

dns:
  enable: true
  ipv6: true
  listen: :23453
  enhanced-mode: redir-host
  nameserver:
    - DNS1
  fallback:
    - "https://DNS2/#dnsPROXY"
  fallback-filter:
    geosite:
      - gfw
      - greatfire
      - disney
      - netflix
    geoip: false
    geoip-code: CN

现象：
1.DNS配置  ipv6: false情况下，分流正常，属于geosite指定范围域名的走fallback解析，其他域名只走nameserver解析。
2.DNS配置  ipv6: true情况下，属于geosite指定范围域名解析正常，不会使用nameserver，只出现在fallback解析记录中。不属于geosite指定范围域名ipv4解析记录也正常分流到nameserver，但ipv6解析记录会同时出现在nameserver和fallback解析记录中，未能正确分流到nameserver。

建议：
不属于geosite指定范围域名IPv6解析，希望只走nameserver，不走fallback。

**Comment by zhudan** [comment]
@whatagoodboy 2好像并没有什么毛病啊，geosite的域名本来就会到那么server

**Comment by whatagoodboy** [comment]
> @whatagoodboy 2好像并没有什么毛病啊，geosite的域名本来就会到那么server

但是ipv4是可以正确分流的，不会出现同时在nameserver和fallback同时解析的情况，只有ipv6解析会出现。

**Comment by zhudan** [comment]
@whatagoodboy When fallback is present, the DNS server will send concurrent requests to the servers in this section along with servers in nameservers. The answers from fallback servers are used when the GEOIP country is not CN.

原版是这么说的，大致意思是fallback返回的解析记录不是CN就会使用fallback，言下之意就是当启用了fallback，那么nameserver和fallback的dns服务都会并发取解析。

**Comment by whatagoodboy** [comment]
> @whatagoodboy When fallback is present, the DNS server will send concurrent requests to the servers in this section along with servers in nameservers. The answers from fallback servers are used when the GEOIP country is not CN.
> 
> 原版是这么说的，大致意思是fallback返回的解析记录不是CN就会使用fallback，言下之意就是当启用了fallback，那么nameserver和fallback的dns服务都会并发取解析。

原版只能使用geoip，只能并发解析然后根据解析ip来判断地区来选择使用哪个解析。而meta的新特性是通过geosite分流，在ipv4下是严格分流的，没有并发。这是个非常好的特性，能够有效避免需要代理的域名使用nameserver解析造成访问记录隐私泄漏等相关风险。

**Comment by whatagoodboy** [comment]
> 你这个geoip: true参数删除了？删除了是不是就是默认true啊，应该改成false吧。

    geoip: false
    geoip-code: CN

抱歉没有贴完整。

**Comment by topsite** [comment]
> > 你这个geoip: true参数删除了？删除了是不是就是默认true啊，应该改成false吧。
> 
> ```
> geoip: false
> geoip-code: CN
> ```
> 
> 抱歉没有贴完整。

第一个，你试试改成geosite:
      - '!CN'
删除其他分类
第二个，你说ipv6不行，能给一个你说的不行的网站，我试试吗

**Comment by whatagoodboy** [comment]
> > > 你这个geoip: true参数删除了？删除了是不是就是默认true啊，应该改成false吧。
> > 
> > 
> > ```
> > geoip: false
> > geoip-code: CN
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 抱歉没有贴完整。
> 
> 第一个，你试试改成geosite: - '!CN' 删除其他分类 第二个，你说ipv6不行，能给一个你说的不行的网站，我试试吗


在纯ipv4环境下没问题，推测应该不是geosite规则配置的原因导致的。

我尝试过 - geolocation-!cn。问题依旧。如www.163.com  www.ifeng.com

我换个方式重新描述下遇到的问题：

在支持ipv6的环境下：

1.未匹配到geosite的网站：A记录请求nameserver（没有问题），AAAA记录同时请求了nameserver和fallback（疑似bug）。
希望未匹配未匹配到geosite的网站，A记录和AAAA记录都走nameserver，不走fallback。

2.匹配到geosite的网站：A记录请求仅出现在fallback（没有问题），AAAA记录请求也仅出现fallback（没有问题）。

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
