### ISSUE TITLE
[Feature] 增加对 Juicity 的支持

### ISSUE THREAD

**Issue by flyingbug2** [MetaCubeX/mihomo#1041]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

 Tuic 已经停了一段时间，希望能够增加对 Juicity 的支持，替代tuic。

**Comment by wwqgtxx** [comment]
never
