### ISSUE TITLE
[Feature] multi select client fingerprint

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#1043]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Hi
Please add option to set multiple client fingerprint and clashmeta must select one of them randomly (random for each proxy)
`global-client-fingerprint: chrome,firefox,edge,safari` for example
Thanks

**Comment by ccmuyuu** [comment]
```global-client-fingerprint: random```
