### ISSUE TITLE
[Feature] 请支持overtls

### ISSUE THREAD

**Issue by chenxudong2020** [MetaCubeX/mihomo#1056]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

请支持overtls协议

### Possible Solution

https://github.com/ShadowsocksR-Live/overtls 这个是项目介绍

**Comment by jtzhpf** [comment]
这个协议的特点/优点是什么呢？

**Comment by Skyxim** [comment]
使用 Trojan
