### ISSUE TITLE
[Feature] proxy-groups配置的filter字段应该是筛选满足关键词或正则表达式的节点，但是文档里写着“仅作用于引入代理集合”，应该针对所有代理的筛选

### ISSUE THREAD

**Issue by dongchengjie** [MetaCubeX/mihomo#1059]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

比如现在我有个需求，我已经在proxies中定义了一系列节点，然后我想把所有带有"us"字样的独立分一个组，使用**include-all**或**include-all-proxies**，引入了所有代理。然后使用**filter**配置进行筛选满足条件的，这样符合逻辑吧。
但是文档里写着**仅作用于引入代理集合**，proxy-providers是不是有着自己的filter配置么？先在proxy-providers配置里初筛不就可以了吗,为何要耦合到proxy-groups的配置中？现在如果要实现上述功能，用filter是达不到效果的，难不成使用**exclude-filter**正则写成"非us"字样的排除掉？
proxy-providers的filter：https://wiki.metacubex.one/config/proxy-providers/#filter
proxy-groups的filter：https://wiki.metacubex.one/config/proxy-groups/#filter
我预想中的流程应该是这样
![未命名绘图 drawio](https://github.com/MetaCubeX/mihomo/assets/37543964/e855eb12-6253-4550-b1f0-7a3318564d58)

### Possible Solution

proxy-providers的filter效果保持原样
proxy-groups的filter的生命周期应该是在引入了相关代理后（包括硬编码定义、include-all定义的），对引入的结果进行筛选保留，而不是**仅作用于引入代理集合**，人家proxy-providers自己有filter属性了

**Comment by xishang0128** [comment]
@dongchengjie groups引入proxies是可控性的,但是引入provider不是,只能引入一整个provider,所以有groups的filter,在引入多个provider的时候更方便的筛选,如果你需要引用配置内的proxies并且筛选,建议使用file类型的provider

**Comment by dongchengjie** [comment]
@xishang0128 在使用include-all或者include-all-proxies时，等价于引入一个provider，引入proxies同样是不可控性的，硬编码的方式控制proxies很长一摞太麻烦了

**Comment by xishang0128** [comment]
@dongchengjie 所以把proxies单独开,用provider引入,就好了

**Comment by Skyxim** [comment]
@xishang0128 终归都有缺点，如果筛选，又会有人说，影响硬编码的配置文件。仅仅是一个选择

**Comment by xishang0128** [comment]
@dongchengjie 或者使用exclude-filter,好像可以对proxies生效,断言排除一下,应该也能做到筛选的效果
