### ISSUE TITLE
遇到这种问题

### ISSUE THREAD

**Issue by alsojin0806** [MetaCubeX/mihomo#106]
time="2022-06-29T22:32:18+08:00" level=info msg="Start initial configuration in progress"
time="2022-06-29T22:32:18+08:00" level=warning msg="Auto detect interface: WLAN"
time="2022-06-29T22:32:18+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-06-29T22:32:18+08:00" level=info msg="Start initial GeoIP rule CN => Proxies, records: 10294"
time="2022-06-29T22:32:18+08:00" level=info msg="Initial configuration complete, total time: 4ms"
time="2022-06-29T22:32:18+08:00" level=info msg="Use interface name: WLAN"
time="2022-06-29T22:32:18+08:00" level=info msg=" proxy listening at: [::]:7890"
time="2022-06-29T22:32:18+08:00" level=info msg="SOCKS proxy listening at: [::]:7891"
2022/06/29 22:32:18 Using existing driver 0.14
2022/06/29 22:32:18 Creating adapter
time="2022-06-29T22:32:18+08:00" level=info msg="TUN stack listening at: Clash(198.18.0.1), mtu: 9000, auto route: true, ip stack: gVisor"
time="2022-06-29T22:32:18+08:00" level=info msg="Start initial compatible provider Proxies"
time="2022-06-29T22:32:18+08:00" level=info msg="Start initial compatible provider default"
time="2022-06-29T22:32:18+08:00" level=error msg=this_is_end
time="2022-06-29T22:32:23+08:00" level=warning msg="[UDP] dial Proxies (match GeoIP/CN) to 59.39.128.64:2722 error: ustest.test.com:443 connect error: all DNS requests failed, first error: EOF"
"2022-06-29T22:32:23+08:00" level=warning msg="[UDP] dial Proxies (match Match/) to 239.255.255.250:3702 error: ustest.test.com:443 connect error: all DNS requests failed, first error: EOF"

**Comment by alsojin0806** [comment]
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: xxxx
  server: xxx.xxx.xxx
  port: 1111
  type: vmess
  uuid: 12222222
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: 
    headers:
      Host: xxx.xxxx.xxx
  udp: true
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - xxxx
rules:
 - DOMAIN-SUFFIX,1password.com,Proxies
 - DOMAIN-SUFFIX,vultr.com,Proxies
 - DOMAIN-SUFFIX,mb3admin.com,Proxies
 - DOMAIN-SUFFIX,rixcloud.io,Proxies
 - DOMAIN-SUFFIX,tempestapp.io,Proxies
 - DOMAIN-SUFFIX,baidu.com,Proxies
 - DOMAIN-SUFFIX,baidu-int.com,Proxies
 - DOMAIN-SUFFIX,erebor.douban.com,Proxies
 - DOMAIN,mtalk.google.com,Proxies
 - DOMAIN,alt1-mtalk.google.com,DIRECT
 - DOMAIN,alt2-mtalk.google.com,DIRECT
 - DOMAIN,alt3-mtalk.google.com,DIRECT
 - DOMAIN,alt4-mtalk.google.com,DIRECT
 - DOMAIN,alt5-mtalk.google.com,DIRECT
 - DOMAIN,alt6-mtalk.google.com,DIRECT
 - DOMAIN,alt7-mtalk.google.com,DIRECT
 - DOMAIN,alt8-mtalk.google.com,DIRECT
 - DOMAIN,alt9-mtalk.google.com,DIRECT
 - DOMAIN,captive.apple.com,DIRECT
 - DOMAIN,time-ios.apple.com,DIRECT
 - DOMAIN-SUFFIX,gateway.push-apple.com.akadns.net,DIRECT
 - DOMAIN-SUFFIX,push.apple.com,DIRECT
 - DOMAIN-KEYWORD,github,Proxies
 - DOMAIN-SUFFIX,github.com,Proxies
 - DOMAIN-SUFFIX,github.io,Proxies
 - DOMAIN-SUFFIX,githubapp.com,Proxies
 - DOMAIN-SUFFIX,githubassets.com,Proxies
 - DOMAIN-SUFFIX,githubusercontent.com,Proxies
 - DOMAIN-SUFFIX,home-intl.console.aliyun.com,Proxies
 - DOMAIN,ip.skk.moe,Proxies
 - DOMAIN,ip.sb,Proxies
 - DOMAIN-SUFFIX,googleapis.cn,Proxies
 - DOMAIN-SUFFIX,maying.co,Proxies
 - DOMAIN-SUFFIX,flowercloud.net,Proxies
 - DOMAIN-SUFFIX,socloud.me,Proxies
 - DOMAIN-SUFFIX,ytoo.asia,Proxies
 - DOMAIN-SUFFIX,ytoo.co.uk,Proxies
 - GEOIP,CN,Proxies
 - MATCH,Proxies
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true

**Comment by alsojin0806** [comment]
dns部分的配置是：
dns:
enable: true
ipv6: false
listen: 0.0.0.0:5353
enhanced-mode: redir-host
nameserver:
- https://doh.pub/dns-query
fallback:
- tls://1.1.1.1:853
- tls://1.0.0.1:853
dns 这样配置也不行

**Comment by MetaCubeX** [comment]
@alsojin0806 listen 127.0.0.1:9527

**Comment by alsojin0806** [comment]
dns:
  enable: true   
  listen: 127.0.0.1:9527   
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true

**Comment by alsojin0806** [comment]
time="2022-06-30T19:59:33+08:00" level=warning msg="♻️ 自动选择 first failed"
time="2022-06-30T19:59:33+08:00" level=warning msg="[UDP] dial 🐟 漏网之鱼 (match Match/) to 239.255.255.250:1900 error: new vmess client error: dial xxx.xxxx.com:443 error: context deadline exceeded"
time="2022-06-30T19:59:33+08:00" level=warning msg="♻️ 自动选择 first failed"
time="2022-06-30T19:59:33+08:00" level=warning msg="[UDP] dial 🐟 漏网之鱼 (match Match/) to 239.255.255.250:3702 error: new vmess client error: dial xxx.xxx.com:443 error: read tcp4 192.168.43.13:5950->144.24.72.63:443: i/o timeout"
time="2022-06-30T19:59:42+08:00" level=warning msg="♻️ 自动选择 failed count: 2"
time="2022-06-30T19:59:42+08:00" level=warning msg="[UDP] dial 🐟 漏网之鱼 (match Match/) to 239.255.255.250:1900 error: new vmess client error: dial qhk1.pgfhub.com:443 error: context deadline exceeded"
time="2022-06-30T19:59:46+08:00" level=info msg="[TCP] 198.18.0.1:5957(SunloginClient.exe) --> ws-std01.sunlogin.oray.com:443 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
time="2022-06-30T19:59:49+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP/CN) to sl-log.oray.net:443 error: dial tcp4 192.168.43.13:0->121.40.118.44:443: i/o timeout"

**Comment by nickolastone** [comment]
@MetaCubeX 请问群是哪个?没找到

**Comment by oluceps** [comment]
> @MetaCubeX 请问群是哪个?没找到

t.me/MetaKernel

**Comment by nick008a** [comment]
遇到了同样的问题。

同样故障的还有： https://github.com/Dreamacro/clash/issues/2145 https://github.com/Kr328/ClashForAndroid/issues/1358 https://github.com/Dreamacro/clash/issues/2131

clash好像没法修改tcp的timeout？https://www.v2fly.org/v5/config/service/policy.html#policyobject

https://github.com/Dreamacro/clash/issues/1876

**Comment by SplitGemini** [comment]
premium 2022.08.26仍未解决，访问bilivideo.cn会timeout

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
