### ISSUE TITLE
[Bug] 出现了段错误的提示

### ISSUE THREAD

**Issue by ToKingl** [MetaCubeX/mihomo#1062]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.2-alpha-78b4b11

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
No response
```

### Mihomo log

```shell
No response
```

### Description

处理器：Loongson-3A6000-HV × 8 
操作系统名称：loongnix 20.5
操作系统版本：64-bit

安装loong64版本的deb包，提示：软件包体系结构(loong64)与本机系统体系结构(loongarch64)不符，解压deb包修改control文件中的架构为loongarch64后重新打包并安装成功，然后在加载yaml配置文件时提示出现了段错误，求开发大大看看是哪里出现了问题。

![1](https://github.com/MetaCubeX/mihomo/assets/146187689/fe3da82e-22e6-48c9-b2b8-704e3c5568dc)
![2](https://github.com/MetaCubeX/mihomo/assets/146187689/8f7f3ad6-03c8-4110-872b-544924460c87)

**Comment by Cyenoch** [comment]
出现了段错误 这个错误是啥

**Comment by ziqi-cn** [comment]
可能是由于[新旧世界的问题](https://areweloongyet.com/docs/old-and-new-worlds#%E6%88%91%E7%BB%99%E9%BE%99%E6%9E%B6%E6%9E%84%E4%BA%A4%E5%8F%89%E7%BC%96%E8%AF%91%E7%9A%84-go-%E7%A8%8B%E5%BA%8F%E8%BF%90%E8%A1%8C%E6%8A%A5%E6%AE%B5%E9%94%99%E8%AF%AF%E5%92%8B%E5%9B%9E%E4%BA%8B)，试一试本机编译运行是否还有问题

**Comment by ziqi-cn** [comment]
我看了一下，[这个文件](https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-loong64-alpha-78b4b11.deb)属于新世界，loongnix属于旧世界，此错误是由于新旧世界不兼容所致

**Comment by ToKingl** [comment]
此问题已修复
