### ISSUE TITLE
规则无法匹配

### ISSUE THREAD

**Issue by pizixi** [MetaCubeX/mihomo#1070]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.1 windows amd64 with go1.21.6 Fri Feb  2 12:19:51 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
rules:
  - DOMAIN-SUFFIX,openai.com,🔰 节点选择
...
```

### Description

上面的规则已经放到第一位了，但是无法匹配
![image](https://github.com/MetaCubeX/mihomo/assets/56673215/b9c44931-7fa5-4455-92fc-b462e3c50520)
配置文件不变情况下，使用原版clash正常匹配

**Comment by xishang0128** [comment]
@pizixi 请确保节点支持udp(书写udp: true),如果节点不支持udp,将会继续匹配

**Comment by pizixi** [comment]
可以了，感谢感谢
