### ISSUE TITLE
[Bug] build docker container from source met error

### ISSUE THREAD

**Issue by levihuayuzhang** [MetaCubeX/mihomo#1073]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Alpha

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
null
```

### Mihomo log

```shell
null
```

### Description

error is following:
```sh
 => CACHED [builder 6/7] COPY bin/ bin/                                                                            0.0s
 => ERROR [builder 7/7] RUN FILE_NAME=`sh file-name.sh` && echo $FILE_NAME &&     FILE_NAME=`ls bin/ | egrep "$FI  0.3s
------                                                                                                                  
 > [builder 7/7] RUN FILE_NAME=`sh file-name.sh` && echo $FILE_NAME &&     FILE_NAME=`ls bin/ | egrep "$FILE_NAME.gz"|awk NR==1` && echo $FILE_NAME &&     mv bin/$FILE_NAME mihomo.gz && gzip -d mihomo.gz && echo "$FILE_NAME" > /mihomo-config/test:
0.293 mihomo-linux-amd64-compatible-
0.293 cat: can't open 'bin/version.txt': No such file or directory
0.294 
0.315 gzip: mihomo.gz is a directory -- ignored
------
Dockerfile:14
--------------------
  13 |     COPY bin/ bin/
  14 | >>> RUN FILE_NAME=`sh file-name.sh` && echo $FILE_NAME && \
  15 | >>>     FILE_NAME=`ls bin/ | egrep "$FILE_NAME.gz"|awk NR==1` && echo $FILE_NAME && \
  16 | >>>     mv bin/$FILE_NAME mihomo.gz && gzip -d mihomo.gz && echo "$FILE_NAME" > /mihomo-config/test
  17 |     FROM alpine:latest
--------------------
ERROR: failed to solve: process "/bin/sh -c FILE_NAME=`sh file-name.sh` && echo $FILE_NAME &&     FILE_NAME=`ls bin/ | egrep \"$FILE_NAME.gz\"|awk NR==1` && echo $FILE_NAME &&     mv bin/$FILE_NAME mihomo.gz && gzip -d mihomo.gz && echo \"$FILE_NAME\" > /mihomo-config/test" did not complete successfully: exit code: 2

```

**Comment by levihuayuzhang** [comment]
using command `sudo docker build .` under project root.

**Comment by Skyxim** [comment]
The Dockerfile in the warehouse does not use a general build method and only works on Github Action.

**Comment by levihuayuzhang** [comment]
I see. Thanks a lot.
