### ISSUE TITLE
[Feature] 自动转换配置中的国际化域名（IDN）

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#1075]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

例如，我想让使用 `.中国` 顶级域的网站走直连：

```
rules:
- DOMAIN-SUFFIX,中国,DIRECT
```

此时该配置无效，因为不会自动将 `中国` 转换成 Punycode 形式的 `xn--fiqs8s`。

从人类的角度而言，在配置中直接写入可读的字符是比较合理的，如果使用 Punycode，在配置达到一定数量后将无法直观地进行增删改查。

**Comment by xishang0128** [comment]
已添加
