### ISSUE TITLE
[Feature] 希望GroupBaseOption增加配置项max-failed-times和failed-timeout-interval，控制差错时激活health check的频率

### ISSUE THREAD

**Issue by dongchengjie** [MetaCubeX/mihomo#1082]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

如源码groupbase.go文件所示，硬编码设置是5秒内DialContext错误了5次就主动激活health check。
这个频率能否支持可以通过配置进行控制啊？默认值还是5和5000，个人可以根据自身情况进行控制
节点可能不太稳定，health check的interval还没到来，AliveForTestUrl根据上次health check的history来尝试，onDialFailed只进行了错误计数，没有对history记录进行不可用标记，即**使用当前selected的节点去尝试5次**。尝试去建立连接也会有超时（假设2~3秒，一来二去就奔10-15秒），导致url-test和是fallback都是断流了一阵才自动切换节点。反倒是减少次数或跳过尝试，直接health check，可能因为并发test的缘故反倒会更快些
```go
func (gb *GroupBase) maxFailedTimes() int {
	return 5
}

func (gb *GroupBase) failedTimeoutInterval() time.Duration {
	return 5 * time.Second
}
```

### Possible Solution

GroupBaseOption增加配置项max-failed-times和failed-timeout-interval

**Comment by xishang0128** [comment]
增加了max-failed-times,failed-timeout-interval直接用timeout
