### ISSUE TITLE
[Bug] 基本无法使用

### ISSUE THREAD

**Issue by cliuff** [MetaCubeX/mihomo#1088]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

git-alpha

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
另附文件
```

### Description

使用了安卓最新客户端，然后自己clone编译运行，都基本上不能正常使用，然而Windows的clash客户端能够正常使用。测延迟绝多数情况都超时，选择节点后无法使用，一直报错见截图，我尝试找了错误的位置见代码截图，根本原因没能找到。附上配置文件[Configuration.yaml.txt](https://github.com/MetaCubeX/mihomo/files/14539351/Configuration.yaml.txt)，两台pixel3和4，安卓13和14，另外一台三星平板安卓10均无法正常使用，只有极少情况下能用。

![image](https://github.com/MetaCubeX/mihomo/assets/35420834/504e3044-ef11-4988-abcd-cedce00deca9)
<img src="https://github.com/MetaCubeX/mihomo/assets/35420834/3e6a9f1b-801a-4616-a724-5bc4ed0bfb8c" height=540 />

**Comment by 666dechaoge** [comment]
> ### Verify steps
> * [x]   确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**。
> * [x]   如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> * [x]   我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists.
> * [x]   我已经仔细看过 [文档](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [文档](https://wiki.metacubex.one/) and was unable to solve the issue.
> * [x]   这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core _per se_, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo.
> 
> ### Mihomo version
> git-alpha
> 
> ### What OS are you seeing the problem on?
> Linux
> 
> ### Mihomo config
> ```yaml
> 另附文件
> ```
> 
> ### Mihomo log
> _No response_
> 
> ### Description
> 使用了安卓最新客户端，然后自己clone编译运行，都基本上不能正常使用，然而Windows的clash客户端能够正常使用。测延迟绝多数情况都超时，选择节点后无法使用，一直报错见截图，我尝试找了错误的位置见代码截图，根本原因没能找到。附上配置文件[Configuration.yaml.txt](https://github.com/MetaCubeX/mihomo/files/14539351/Configuration.yaml.txt)，两台pixel3和4，安卓13和14，另外一台三星平板安卓10均无法正常使用，只有极少情况下能用。
> 
> ![image](https://private-user-images.githubusercontent.com/35420834/311263946-504e3044-ef11-4988-abcd-cedce00deca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NjAwOTEsIm5iZiI6MTcwOTk1OTc5MSwicGF0aCI6Ii8zNTQyMDgzNC8zMTEyNjM5NDYtNTA0ZTMwNDQtZWYxMS00OTg4LWFiY2QtY2VkY2UwMGRlY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA0NDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZjA5MTAyOGFkZWYxYmNmZjc2ZGE4ZjBlNWQwNDczYzJjMGVkYTUxNjkyMmViMDk5YzQ3ZjMzOGM4OTllOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpSFqJTOfsqc9nOQpk3uSGiQ_2EUx_xX951xUnIb7X8) <img alt="" height="540" src="https://private-user-images.githubusercontent.com/35420834/311263574-3e6a9f1b-801a-4616-a724-5bc4ed0bfb8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NjAwOTEsIm5iZiI6MTcwOTk1OTc5MSwicGF0aCI6Ii8zNTQyMDgzNC8zMTEyNjM1NzQtM2U2YTlmMWItODAxYS00NjE2LWE3MjQtNWJjNGVkMGJmYjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA0NDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YWJjNWQ1OTE2YjMzYzhjMzUyNmZhMTc1MjRhYmI2MjU0YjRhOTc0NGJlMDRkYmZhOWI2MjFjMWNlOTFjZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.spm_rMkdT1_Iax_VBdb_4GXJEO3PVCmJ8V1Iac5MG5g">

节点，密码全暴露了，建议尽快重置密码

**Comment by xishang0128** [comment]
这里只接受来自核心的问题,如果你是android客户端发生的问题,那么这边无法提供帮助

**Comment by 666dechaoge** [comment]
编辑历史还是能看到，建议尽快重置节点连接密码
