### ISSUE TITLE
[Feature] Better Auto Update function on the Android App

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#1093]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Currently Auto Update is Disable by default
Auto Update will work in Background, and Create annoying Notification with a Sound after each Update!

### Possible Solution

You can make it like Sing-Box Auto Update (that is the best mechanism currently)
It is enabled by default, Auto Updates each 1 hour by default
Will only work when user opens the app, It's working in silence, there is no annoying notification and notification sound

**Comment by xishang0128** [comment]
Only core issues are accepted here

**Comment by xishang0128** [comment]
> Rules says 'does not accept problem reports from clients that only use other kernels, such as clash for windows' So I thought it's ok to report CM4A issues here as it's code is ClashMeta and it's own issues are closed Sorry, but are you going to turn the auto update notification to a toast notification that will shows only inside the app? update notifications of CM4A and it's notification sound is really annoying

This is because clash meta for android is in a state of almost no official maintenance, so clash meta for android does not accept any issues.
