### ISSUE TITLE
[Feature] Mux setting per proxy

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#1096]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

I see in Docs that global Mux settings exist
but there is no Mux setting per proxy

### Possible Solution

Add Mux setting for each proxy that can override the global mux settings

**Comment by Skyxim** [comment]
Mux is not a universal setting and should not be set for every
