### ISSUE TITLE
[Bug] 使用最新1.18.1  致使电脑内存占用极大

### ISSUE THREAD

**Issue by lbcake** [MetaCubeX/mihomo#1098]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.18.1

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
https://github.com/clash-verge-rev/clash-verge-rev/issues/488

https://github.com/clash-verge-rev/clash-verge-rev/issues/511
```

### Description

使用 clash-verge-rev  切换meta的最新内核     当订阅里存在hy2   刷新订阅 内存直接猛增100M+

使用上内存可能会猛增到上G

**Comment by xishang0128** [comment]
@lbcake h2是什么,http/2?另外内存问题上传上传heap

**Comment by lbcake** [comment]
> @lbcake h2是什么,http/2?另外内存问题上传上传heap

hy2协议

**Comment by wjs876046992** [comment]
我也遇到同样的问题。
<img width="535" alt="image" src="https://github.com/MetaCubeX/mihomo/assets/17695195/ccf936a4-d4a7-487f-8f03-08e15544b72f">

**Comment by wjs876046992** [comment]
> 我也遇到同样的问题。 <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/17695195/312519446-ccf936a4-d4a7-487f-8f03-08e15544b72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDM4NjksIm5iZiI6MTcxMDM0MzU2OSwicGF0aCI6Ii8xNzY5NTE5NS8zMTI1MTk0NDYtY2NmOTM2YTQtZDRhNy00ODdmLThmMDMtMDhlMTU1NDRiNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE1MjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOTRjZjkwNWQ0OGE1NWY5NTVmZDNhNGE1MTRmNjY3YTVkYTllZmMwYThmYTM4YTIyYTBlMTBkZmIyMjA0MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k30b16X-SbGIpmbRvJjeNn6rR3cLOxrulVVlZaPIH8w">

准确地讲，是开启tun模式才会。

**Comment by lbcake** [comment]
> 我也遇到同样的问题。 <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/17695195/312519446-ccf936a4-d4a7-487f-8f03-08e15544b72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTAyMjMsIm5iZiI6MTcxMDUwOTkyMywicGF0aCI6Ii8xNzY5NTE5NS8zMTI1MTk0NDYtY2NmOTM2YTQtZDRhNy00ODdmLThmMDMtMDhlMTU1NDRiNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDEzMzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWFjMDQ1MjFiZmYxMGY0Zjg3YTQ5MjFkNmI0ZWVkNDU2Mjg3MWM2N2E5ZWVmNGVkMDlhMWY3ZTE5NjZiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTQ11bbIpRVr52m8Pk9z9Zl-hDSuyqomGOnyZhHMR-M">

上传你的heap  直接回复上边的0129

**Comment by EventHorizonV** [comment]
遇到了同样的情况，开了tun模式之后几分钟后内存占用到达4G-6G 同时连接里存在了大量的上传流量

**Comment by lovitus** [comment]
最新的内核. 开启tun ,一分钟用了11G ram, 而且还在继续加.

![image](https://github.com/MetaCubeX/mihomo/assets/14361541/618a954a-a0f3-42b7-86b2-dc16ca8745c2)

**Comment by nodokasaki** [comment]
我也是，上传速度满了，然后没网，tun开关好多次最后好了，不知道是什么原因

**Comment by EventHorizonV** [comment]
我发现开启ipv6之后才会出现这种情况，关闭之后没有再遇到过大量上传和内存高占用的情况

**Comment by Skyxim** [comment]
https://github.com/MetaCubeX/mihomo/commit/16fadd24418ea3606b57b793f1f6ce14b56ffb01

尝试最新测试版本

**Comment by xishang0128** [comment]
你这并不是直接运行核心测试的,无法提供支持
