### ISSUE TITLE
[Bug] 最新版alpha-81c832e被Windows defender报毒

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#1101]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-81c832e

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
无
```

### Description

从GitHub release界面下载最新的alpha-81c832e二进制程序，解压后Windows Defender就报毒并自动删除了该二进制文件。
报毒的详细信息如下：
![image](https://github.com/MetaCubeX/mihomo/assets/45709305/fd226838-13c1-4aae-a5ef-6b5603916164)

Windows官方解释如下：https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505

下载的二进制文件如下：
[mihomo-windows-amd64-alpha-81c832e.zip](https://github.com/MetaCubeX/mihomo/files/14572877/mihomo-windows-amd64-alpha-81c832e.zip)

不清楚是什么最近什么代码更改触发了Windows病毒库。

**Comment by xishang0128** [comment]
@ForestL18 没法复现,本机编译扫描并没有任何问题

**Comment by xishang0128** [comment]
@ForestL18 建议白名单完事,而且这也不算bug

**Comment by xishang0128** [comment]
@ForestL18 1.407.353.0的,不知道是不是最新的

**Comment by wwqgtxx** [comment]
已经重新运行action编译，现在应该不会报毒了
https://www.virustotal.com/gui/file/8e04b3c860f939dd0c599e53d62d30107139f2f6dec304f4a17fb3ee7c90b29c?nocache=1
