### ISSUE TITLE
[Bug] shadowsocks协议的server中ipv6地址带"[]"无法连接

### ISSUE THREAD

**Issue by wuying2021** [MetaCubeX/mihomo#1103]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.18.1 windows amd64 with go1.21.6 Fri Feb  2 12:19:51 UTC 2024 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
- {name: ali-az-us1, server: "[2408:400a:5:3600:*]", port: 59932, type: ss, cipher: chacha20-ietf-poly1305, password: *}
```

### Mihomo log

```shell
time="2024-03-13T18:16:17.6546316+08:00" level=warning msg="[TCP] dial 📲 电报消息 (match IPCIDR/2001:67c:4e8::/48) 127.0.0.1:30116(Telegram.exe) --> [2001:67c:4e8:f004::a]:80 error: [[2408:400a:5:3600:*]]:59932 connect error: address [[2408:400a:5:3600:*]]:59932: missing port in address"
time="2024-03-13T18:16:17.684187+08:00" level=warning msg="Mihomo shutting down"
```

### Description

shadowsocks协议的server中ipv6地址带"[]"无法连接
同样我用hy2可以连接
最终log中address [[2408:400a:5:3600:*]]:59932

**Comment by wwqgtxx** [comment]
最新alpha版中hy2也不会再支持这种写法
