### ISSUE TITLE
希望调整domain(text)的匹配逻辑

### ISSUE THREAD

**Issue by AkinoYuiko** [MetaCubeX/mihomo#1106]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### 前言

Mihomo支持text格式的domain rule-set，然而仍然要求与yaml格式相同的通配符，这就导致已有的Surge DOMAIN-SET无法直接用于Mihomo。

\* 同样的写法在Stash上面是没问题的，可以正常匹配。

### 举例

.github.com 可以匹配到 *.github.com 却不能匹配 github.com，要实现类似DOMAIN-SUFFIX的效果，需要写成+.github.com

Surge系无法读取后者的写法

### Possible Solution

个人认为text格式的规则，是方便Surge系和Clash系用户使用同一套规则集，无需维护两套格式，建议像Stash那样，yaml格式保持原要求写法，text格式向Surge系靠拢。

**Comment by xishang0128** [comment]
@AkinoYuiko text是为了大集合的解析性能,而不是兼容,所以不会考虑放弃已有解析格式

**Comment by Skyxim** [comment]
这种变动会产生逻辑不一致，但是处理 Surge 的 `.example.com` 接近是一个简单的前匹配和添加一个 `+`

**Comment by wwqgtxx** [comment]
您好，mihomo不是surge的下游软件，没有必要也不会去为了surge打破现有配置的兼容性
