### ISSUE TITLE
[Feature] 允许配置COMPATIBLE目标的行为为DIRECT或REJECT

### ISSUE THREAD

**Issue by githablocal** [MetaCubeX/mihomo#1111]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前COMPATIBLE目标的行为为DIRECT，有时配合url-test容易造成IP发生跳变进而触发风控。能否增加一个配置项，允许指定COMPATIBLE目标的行为？

**Comment by xishang0128** [comment]
@githablocal COMPATIBLE仅在组内无节点时产生,如果为reject,则可能无法更新集合,所以,是不会更改COMPATIBLE的行为的

**Comment by githablocal** [comment]
更新集合的链路可以通过域名规则等多种方式指定，另外未配置时可以默认为DIRECT，不影响兼容性。

**Comment by dycwuxing** [comment]
> 更新集合的链路可以通过域名规则等多种方式指定，另外未配置时可以默认为DIRECT，不影响兼容性。

大佬，请问如果是代理链中出现COMPATIBLE，是不是意味会暴露自己的节点？相当于direct-vps？因为一般代理链的时候，vps用的都是ss协议了…

**Comment by Skyxim** [comment]
> 更新集合的链路可以通过域名规则等多种方式指定，另外未配置时可以默认为DIRECT，不影响兼容性。

你这和 COMPATIBLE 不是同一个问题，COMPATIBLE 是为了解决指定代理组未成功加载任何节点情况下无法联通

**Comment by Skyxim** [comment]
> @Skyxim INNER在文档中没有搜到，请问是指什么？
> 
> > 你这和 COMPATIBLE 不是同一个问题，COMPATIBLE 是为了解决指定代理组未成功加载任何节点情况下无法联通。
> 
> 我是想说，目前COMPATIBLE的效果可以通过在代理组内部额外添加一个DIRECT代理实现。 不过你后面倒是提醒我，给每个use后面都加一个REJECT就可以避免任何时候出现COMPATIBLE了。

内核自己的特殊请求，通过内部的方式进入规则匹配的流量，比如 Provider 的请求下载
