### ISSUE TITLE
[Bug] UDP DNS返回结果超过512字节时用TCP重新发起查询无法正常返回结果

### ISSUE THREAD

**Issue by AllForLandlord** [MetaCubeX/mihomo#1117]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-gb3db113

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 223.5.5.5
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  use-hosts: true
```

### Mihomo log

```shell
2024-03-19 09:32:09 level=debug msg="[DNS] www.ai2moe.org --> [] A from udp://223.5.5.5:53"
2024-03-19 09:32:09 level=debug msg="[DNS] resolve www.ai2moe.org from udp://223.5.5.5:53"
2024-03-19 09:32:09 level=debug msg="[DNS] cache hit for www.ai2moe.org., expire at 2024-03-19 01:32:10"
2024-03-19 09:32:09 level=debug msg="[DNS] www.ai2moe.org --> [] A from udp://223.5.5.5:53"
2024-03-19 09:32:09 level=debug msg="[DNS] www.ai2moe.org --> [] HTTPS from udp://223.5.5.5:53"
2024-03-19 09:32:09 level=debug msg="[DNS] resolve www.ai2moe.org from udp://223.5.5.5:53"
2024-03-19 09:32:09 level=debug msg="[DNS] cache hit for www.ai2moe.org., expire at 2024-03-19 01:32:09"
2024-03-19 09:32:09 level=debug msg="[DNS] resolve www.ai2moe.org from udp://223.5.5.5:53"
```

### Describe the Bug
在OpenClash issue提出了此问题，V大表示是内核的问题：https://github.com/vernesong/OpenClash/issues/3811

详见：https://www.v2ex.com/t/1024280
223.5.5.5在进行UDP DNS查询返回A记录过多超过512字节后会重新用TCP进行DNS查询，而在开启openclash（nameserver只用223.5.5.5）的情况下无法正常进行DNS查询。复现网址：[www.ai2moe.org](url)。 表现结果为chrome浏览器访问该网站报错`DNS_PROBE_FINISHED_NXDOMAIN`。

而关掉openclash用命令`dig +tcp @223.5.5.5 -p 53 www.ai2moe.org`返回结果正常。后在PC上手动设置DNS用223.5.5.5，可以正常访问[www.ai2moe.org](url)。而开了openclash就无法正常访问。

所以我推测可能openclash或者可能是meta内核对于这种情况的DNS查询有bug，而V大表示是内核的问题。

### To Reproduce

openclash用meta内核，在redir-host模式下，DNS设置中启用`自定义上游 DNS 服务器`，nameserver只勾选223.5.5.5，fallback关掉。
访问[www.ai2moe.org](url)，发现无法访问，chrome浏览器报错`DNS_PROBE_FINISHED_NXDOMAIN`。

**Comment by AllForLandlord** [comment]
@wwqgtxx 
大佬，感谢commit，我刚刚把openclash meta内核升级到`alpha-g9c08e93`，然后再测试了访问[https://www.ai2moe.org/](url)，依旧报错`DNS_PROBE_FINISHED_NXDOMAIN`。

下面是debug的DNS日志：
<img width="877" alt="1" src="https://github.com/MetaCubeX/mihomo/assets/68906347/0bfbe459-7b4f-43b2-8df3-848b1bb2873f">

如果需要什么测试结果，请随时回复。

**Comment by wwqgtxx** [comment]
试试 https://github.com/MetaCubeX/mihomo/commit/d56a439a741ec8762409598bc927390cdf67c5fa

**Comment by AllForLandlord** [comment]
> 试试 [d56a439](https://github.com/MetaCubeX/mihomo/commit/d56a439a741ec8762409598bc927390cdf67c5fa)

测试下来现在可以正常解析了！感谢修复！

下面是日志：
<img width="1594" alt="1" src="https://github.com/MetaCubeX/mihomo/assets/68906347/35b118a7-e34c-4467-ae25-8f5614b70476">
