### ISSUE TITLE
[Feature] tcpPing test

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#1119]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

What do you think about new server test method using TCP Ping? (can tcp ping 8.8.8.8:443 or 1.1.1.1:443 for example)
It can make the core use less HW resources and even give more accurate results
core can make multiple tcp ping at same time and take the average of them and find the best server in less than 250ms
and can use same method to do health check without using a lot of traffic or HW resources

**Comment by xishang0128** [comment]
@APT-ZERO Tcp ping cannot produce more accurate results, because the target of tcp ping is the server address written by proxies. Proxies may have multiple nested server addresses that may not be the final outbound.
