### ISSUE TITLE
[Feature] 请问RULE-SET未来会支持AND & OR & NOT逻辑规则吗

### ISSUE THREAD

**Issue by weijingcheng4** [MetaCubeX/mihomo#1126]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

GitHub的域名需要代理，但是22端口不需要代理，需要用到逻辑规则，规则写在RULE-SET中。因为机场关闭了22端口，现在每次ssh连接GitHub 需要手动切换全局直连。
目前识别不出逻辑规则
![IMG_1620](https://github.com/MetaCubeX/mihomo/assets/49937971/f726ac64-e58a-4f7b-9c5e-4316fc8b2e3b)
![IMG_1621](https://github.com/MetaCubeX/mihomo/assets/49937971/dbeeeadf-03c1-4264-b82e-903aeebcd099)

**Comment by weijingcheng4** [comment]
规则写错了

**Comment by HydrangeaPurple** [comment]
git clone ssh://git@ssh.github.com:443/MetaCubeX/mihomo.git
![image](https://github.com/MetaCubeX/mihomo/assets/21093249/887d76b8-f994-4d99-aa94-23431a0c808e)
你有试过443端口的ssh么
