### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by bouncerbrogues** [MetaCubeX/mihomo#1129]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前一个mihomo实例对应着一个配置目录，配置目录中包括config.yaml和相关的资源。如果在同一个机器上运行多个mihomo实例，就需要多个相关的配置目录，相关的资源比如Country.mmdb，rule-providers、proxy-providers等都需要单独下载保存，这稍微有点浪费。

### Possible Solution

是否能多个配置文件，共享同一个资源目录？比如通过 -d 指定的是目录，-c指定 config.yaml 的文件位置而不是一个目录。不指定 -c 的时候，就从 -d 中读取，指定了 -c，-d 就只是相关资源文件的存储位置。
当然这个需求比较小众了，仅供参考。

**Comment by bouncerbrogues** [comment]
补充标题

**Comment by xishang0128** [comment]
@bouncerbrogues 请好好看看-h输出

**Comment by robustmaster** [comment]
> @bouncerbrogues 请好好看看-h输出

  -f string
    	specify configuration file
  -d string
    	set configuration directory

如果单独指定 -f 不指定 -d，配置相关的资源文件会存放在什么位置？？我试了单独 -f 后，启动成功，但是在当前目录，config.yaml 所在的目录 和 mihomo 二进制所在的目录（/usr/local/bin）都没有。

**Comment by xishang0128** [comment]
@robustmaster ~/.config

**Comment by bouncerbrogues** [comment]
ok，原来已经有了这个功能。感谢！
