### ISSUE TITLE
[Feature] 能否开发类似于tun模式的tproxy模式

### ISSUE THREAD

**Issue by Karaokechen** [MetaCubeX/mihomo#1137]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前来说我知道的是增强模式中的udp流量让tproxy接管的，但是我想让全部流量都由tproxy接管能否做到，tun模式太吃性能不能够跑满我的带宽

### Possible Solution

能否直接开发出切换tproxy模式的选项

**Comment by xishang0128** [comment]
@Karaokechen 配置tproxy-port,然后手动配置iptables/nftables即可

**Comment by Karaokechen** [comment]
> 配置tproxy-port，然后手动配置iptables/nftables即可

前面的添加tproxy端口这个我已经自行添加，后面的手动配置iptables/nftables的具体步骤我该如何操作呢？

**Comment by xishang0128** [comment]
@Karaokechen 学习iptables/nftables语法

**Comment by ArchGuyWu** [comment]
@Karaokechen 那就别用

**Comment by xishang0128** [comment]
@Karaokechen 如果觉得困难,那就使用tun,而不是tproxy
