### ISSUE TITLE
[Feature] Update ClashMetaforAndroid to Use the Latest ClashMeta-Meta Kernel

### ISSUE THREAD

**Issue by lanrosng** [MetaCubeX/mihomo#1139]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

The ClashMeta-Meta kernel has recently released a new version. We kindly request an update for ClashMetaforAndroid to incorporate this latest kernel.

Additionally, we recommend implementing daily automatic releases for ClashMetaforAndroid using the ClashMeta-Alpha kernel.

Thank you for your attention to this matter.

**Comment by WindSakura** [comment]
https://github.com/MetaCubeX/ClashMetaForAndroid/actions

**Comment by istek** [comment]
CMFA’s [Prerelease-alpha](https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha) doesn't have the lastest apk file.

**Comment by xishang0128** [comment]
Please go to the Actions page of cmfa to retrieve.
