### ISSUE TITLE
DOMAIN-REGEX中含有逗号时会识别错误

### ISSUE THREAD

**Issue by zhihans** [MetaCubeX/mihomo#1143]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-11f0983

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
rules:
  - DOMAIN-REGEX,^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$,DIRECT
  # - RULE-SET,private,DIRECT
  # - RULE-SET,geolocation-!cn,DIRECT

rule-providers:
  private:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/zhihans/geodata/master/rule-set/geosite/geosite_private.yaml"
    interval: 43200
  geolocation-!cn:
    type: http
    format: yaml
    behavior: classical
    url: "https://raw.githubusercontent.com/zhihans/geodata/master/rule-set/geosite/geosite_geolocation-!cn.yaml"
    interval: 43200
```

### Mihomo log

```shell
INFO[2024-03-29T10:35:46.565272424+08:00] Start initial configuration in progress      
INFO[2024-03-29T10:35:46.565380018+08:00] Geodata Loader mode: memconservative         
INFO[2024-03-29T10:35:46.565487613+08:00] Geosite Matcher implementation: succinct     
FATA[2024-03-29T10:35:46.56560176+08:00] Parse config error: rules[0] [DOMAIN-REGEX,^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$,DIRECT] error: proxy [61}[a-z0-9])?$] not found
```

### Description

此外，rule provider中某些正则会提示
```
WARN[2024-03-29T10:38:31.785770455+08:00] parse rule error:[error parsing regexp: missing closing ): `^[a-z]([a-z0-9-]{0`] 
WARN[2024-03-29T10:38:31.921041076+08:00] parse rule error:[error parsing regexp: missing closing ): `(^|\.)luchuxue([0-9]{0`] 
WARN[2024-03-29T10:38:31.92159511+08:00] parse rule error:[error parsing regexp: missing closing ): `(^|\.)zayy([0-9]{0`] 
```

**Comment by xishang0128** [comment]
@zhihans 等大概五分钟后用新的alpha试试
