### ISSUE TITLE
[Feature] clash meta for android添加CPU唤醒

### ISSUE THREAD

**Issue by ckaak** [MetaCubeX/mihomo#1144]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

android上如果使用hy协议，手机息屏以后很大概率会在手机亮屏后无法立刻使用，需要等待几秒。猜测是hy用的udp传输，手机系统会在手机息屏后自动关闭连接。

这个问题就算手机系统允许了clash meta自动后台运行，无限制使用流量，也会这样，但是如果换成nekobox，在nekobox设置里开启cpu唤醒锁就不会出现问题。

**Comment by xishang0128** [comment]
cmfa的问题,提交给内核并不能解决
