### ISSUE TITLE
[Bug] 1.83版本，微软WD检测木马

### ISSUE THREAD

**Issue by yiiyahui** [MetaCubeX/mihomo#1147]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.83

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
..........
```

### Description

反馈一下，v1.83巨硬WD的核酸红码，给隔离了。没人有这问题吗？

![1](https://github.com/MetaCubeX/mihomo/assets/30188835/9645e652-92c7-4d63-8ca6-80c2a9200774)

**Comment by ArchGuyWu** [comment]
@yiiyahui https://www.virustotal.com/gui/file/5e9f63be25e238e6328a13bd106d71ee09e5c3c9efadadd27e3fbdc8cb739caf 就一个江民杀毒引擎报了

**Comment by yiiyahui** [comment]
> @yiiyahui https://www.virustotal.com/gui/file/5e9f63be25e238e6328a13bd106d71ee09e5c3c9efadadd27e3fbdc8cb739caf 就一个江民杀毒引擎报了
忘了这技能了，不过确实是被巨硬的WD给秒杀了。。列表里的 NANO-Antivirus 是什么鬼。试了下alpha是绿码。

**Comment by Skyxim** [comment]
> > @yiiyahui https://www.virustotal.com/gui/file/5e9f63be25e238e6328a13bd106d71ee09e5c3c9efadadd27e3fbdc8cb739caf 就一个江民杀毒引擎报了
> > 忘了这技能了，不过确实是被巨硬的WD给秒杀了。。列表里的 NANO-Antivirus 是什么鬼。试了下alpha是绿码。

具体原因不明，好久了，但是就算同一个代码 Action 再次编译就可能不在被杀

**Comment by xishang0128** [comment]
wd是最容易误杀的了,从官方渠道下载的软件没必要信wd的

**Comment by yiiyahui** [comment]
> > > @yiiyahui https://www.virustotal.com/gui/file/5e9f63be25e238e6328a13bd106d71ee09e5c3c9efadadd27e3fbdc8cb739caf 就一个江民杀毒引擎报了
> > > 忘了这技能了，不过确实是被巨硬的WD给秒杀了。。列表里的 NANO-Antivirus 是什么鬼。试了下alpha是绿码。
> 
> 具体原因不明，好久了，但是就算同一个代码 Action 再次编译就可能不在被杀

属实未解之迷了，刚试了下另台电脑,样的系统版本和最后接收更新。但是这次是绿码。可能巨硬天天整活半吊子AI把自己整魔怔了。

**Comment by cerellean** [comment]
CPU占用率爆表，滚回1.18.1了

**Comment by lbcake** [comment]
> CPU占用率爆表，滚回1.18.1了

发新issues
