### ISSUE TITLE
[Feature] 希望 dns 下的 fake-ip-filter 支持 geosite 配置

### ISSUE THREAD

**Issue by fillpit** [MetaCubeX/mihomo#1163]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

现在我有个需求, 我希望国内的域名跳过 fake-ip 的域名处理
现在我只能一条一条添加, 如下:
  fake-ip-filter:
    - "+.baidu.com"
    - "+.bilibili.com"

我希望我能用如下配置来实现国内的域名都能跳过处理,  如下:
  fake-ip-filter:
    - "geosite:cn"

测试版本:
meta core: v1.18.3

**Comment by xishang0128** [comment]
不会支持,如有真实IP需要,请使用redir-host

**Comment by TurnOffNOD** [comment]
> 不会支持,如有真实IP需要,请使用redir-host

这里clash meta内核的redir-host支持是原生的么？

**Comment by iKira** [comment]
+.baidu.com 这个写法有问题吧，如果要匹配 *.baidu.com 和 baidu.com，按正则规则不是应该写成「.*baidu.com」吗？
