### ISSUE TITLE
某台 Windows 10 21H2 台式机无法运行，Windows 事件查看有出错信息

### ISSUE THREAD

**Issue by tifish** [MetaCubeX/mihomo#117]
- 某 Windows 10 21H2 台式机无法运行，Windows 事件查看出错信息如下：

```
Faulting application name: clash-meta.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x277c
Faulting application start time: 0x01d8946f076b18f7
Faulting application path: C:\xxx\clash-meta.exe
Faulting module path: unknown
```

- 1.12、1.11 均无法运行。
- 下载主干源码，使用 Go 1.18.3 编译后可以正常运行。

**Comment by Skyxim** [comment]
@tifish clash有启动日志没

**Comment by yimozi** [comment]
我也有这个问题，就某一台电脑不能启动，楼主能否把可以启动的文件发我下，谢谢，382453#gmail.com。

**Comment by tifish** [comment]
@Skyxim 没有任何日志输出，看起来启动就失败了。是不是编译器的问题？

**Comment by tifish** [comment]
@yimozi
[clash-meta.zip](https://github.com/MetaCubeX/Clash.Meta/files/9364355/clash-meta.zip)

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
