### ISSUE TITLE
[Feature] API文档缺少/group接口的定义，望完善

### ISSUE THREAD

**Issue by dongchengjie** [MetaCubeX/mihomo#1171]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

[REST API](https://wiki.metacubex.one/api/)文档少了一组API定义，[metacubexd](https://github.com/MetaCubeX/metacubexd)不是已经用上了吗？
```go
// server.go
r.Mount("/group", GroupRouter())
```
```go
// groups.go
func GroupRouter() http.Handler {
  r := chi.NewRouter()
  r.Get("/", getGroups)

  r.Route("/{name}", func(r chi.Router) {
  r.Use(parseProxyName, findProxyByName)
  r.Get("/", getGroup)
  r.Get("/delay", getGroupDelay)})
  return r
}
```

**Comment by xishang0128** [comment]
@dongchengjie 如果你指的r.Use(parseProxyName, findProxyByName) ,那么,这只是一个偷懒的用法应当使用/providers/proxies/provider name/proxies name/healthcheck?url=xxx

**Comment by xishang0128** [comment]
已补

**Comment by dongchengjie** [comment]
👌
