### ISSUE TITLE
access localhost return [::1] [Bug] 

### ISSUE THREAD

**Issue by xue-lei** [MetaCubeX/mihomo#1179]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-16fadd2

### Mihomo config

```yaml
无
```

### Description

Causing localhost to be unusable

**Comment by xishang0128** [comment]
mihomo will read the system hosts and give the response, so this is the expected behavior. The system hosts usually contains a mapping of localhost to [::1]

**Comment by xishang0128** [comment]
@xue-lei Check your hosts file and delete the mapping from localhost to [::1]

**Comment by xue-lei** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/59636936/fdc82994-e051-41f4-9b21-c9a662d89fe1)
@xishang0128  I didn`t set it up

**Comment by xishang0128** [comment]
@xue-lei https://wiki.metacubex.one/config/dns/#listen  尝试设置dns监听,然后用dig/nslookup对着mihomo的dns监听端口查询localhost

**Comment by xue-lei** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/59636936/10a5f2a3-2d05-4a2d-ba04-4ca7b8e1b3c4)
@xishang0128

**Comment by Skyxim** [comment]
所以和内核无关
