### ISSUE TITLE
[Bug] include-all和include-all-proxies设为true选项里不会出现自建节点

### ISSUE THREAD

**Issue by uerax** [MetaCubeX/mihomo#1181]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.1

### What OS are you seeing the problem on?

macOS

### Mihomo config

```yaml
proxy-groups:

  - name: 全部节点 
    type: select
    proxies: 
      - DIRECT
    include-all: true
```

### Description

include-all和include-all-proxies设为true选项里不会出现自建节点, 只能显示我默认添加的DIRECT
<img width="336" alt="image" src="https://github.com/MetaCubeX/mihomo/assets/44748971/e45a5b27-9954-427d-8ae5-76e86ca884a2">

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/083cd0d9-ac22-47a3-a83a-64120d58e2ea)
无效反馈
