### ISSUE TITLE
[Bug] ClashMetaForAndroid项目中链接失效问题

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#1190]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

latest

### Mihomo config

```yaml
无
```

### Description

ClashMetaForAndroid/build.gradle.kts中的        `maven("https://maven.kr328.app/releases")
`链接失效，导致编译时产生错误。
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ClashMetaForAndroid'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.kr328.golang:gradle-plugin:1.0.4.
     Required by:
         project :
      > Could not resolve com.github.kr328.golang:gradle-plugin:1.0.4.
         > Could not get resource 'https://maven.kr328.app/releases/com/github/kr328/golang/gradle-plugin/1.0.4/gradle-plugin-1.0.4.pom'.
            > Could not GET 'https://maven.kr328.app/releases/com/github/kr328/golang/gradle-plugin/1.0.4/gradle-plugin-1.0.4.pom'. Received status code 521 from server: 

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Error: Process completed with exit code 1.

**Comment by xishang0128** [comment]
https://github.com/MetaCubeX/mihomo/issues/1049

**Comment by xishang0128** [comment]
@ForestL18 cmfa不接受issues
