### ISSUE TITLE
[Bug] 从clash premium迁移过来的rule不起作用

### ISSUE THREAD

**Issue by lanceyliao** [MetaCubeX/mihomo#1191]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.5.11

### Mihomo config

```yaml
...
```

### Mihomo log

```shell
...
```

### Description

似乎direct起作用，但是global又被重定向走direct了，之前在clash premium内核是有用的
    - DOMAIN-SUFFIX,dama.lu,DIRECT
    - DOMAIN-SUFFIX,ys168.com,DIRECT
    - DOMAIN-SUFFIX,ifconfig.me,DIRECT
    - DOMAIN-SUFFIX,coze.com,GLOBAL
    - DOMAIN-KEYWORD,google,GLOBAL
![image](https://github.com/MetaCubeX/mihomo/assets/45159389/08083444-4793-4306-b994-fb6d870b4713)

**Comment by xishang0128** [comment]
贴出的版本不是最新版本,另外,未提供最小可复现配置
