### ISSUE TITLE
[Feature] DNS模块中fallback-filter支持RULE-SET、NOT逻辑规则等

### ISSUE THREAD

**Issue by cojsns** [MetaCubeX/mihomo#1202]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

fallback-filter处能否支持路由规则，比如RULE-SET、AND & OR & NOT逻辑规则等等，以此实现更详细的分流，比如在domain处添加一个NOT,((RULE-SET,direct))，国内小众域名和国外小众域名走fallbackdns，在解析小众网站的同时又能防止国外网站dns泄露
  fallback:
    - https://101.101.101.101/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://1.0.0.1:853
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
    - https://8.8.4.4/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - NOT,((RULE-SET,direct))

**Comment by cojsns** [comment]
rules:
  - RULE-SET,OpenAI_No_Resolve,📚 OpenAI
  - RULE-SET,Telegram_No_Resolve,📲 Telegram
  - RULE-SET,Steam_No_Resolve,🎮 Steam
  - RULE-SET,Microsoft_No_Resolve,Ⓜ️ 微软
  - RULE-SET,reject,⛔ 广告拦截  # 域名
  - RULE-SET,private,🇨🇳 国内网站  # 域名
  - RULE-SET,lancidr,🇨🇳 国内网站,no-resolve
  - RULE-SET,proxy,🚀 节点选择  # 域名
  - RULE-SET,direct,🇨🇳 国内网站  # 域名
  - RULE-SET,cncidr,🇨🇳 国内网站  # ip
  - MATCH,🚀 节点选择

**Comment by xishang0128** [comment]
防止"dns泄露"应当合理配置路由规则,引用集合应当使用nameserver policy

**Comment by cojsns** [comment]
> 防止"dns泄露"应当合理配置路由规则,引用集合应当使用nameserver policy

感谢
