### ISSUE TITLE
[Feature] 优化[listeners:]的分流规则

### ISSUE THREAD

**Issue by xuemingyang** [MetaCubeX/mihomo#1204]
### Verify steps 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

优化[listeners:]的逻辑, 下面是一段官方配置文件的描述
- name: http-in-1
    type: http
    port: 10809
    listen: 0.0.0.0
    rule: sub-rule-name1 # 默认使用 rules，如果未找到 sub-rule 则直接使用 rules
    proxy: proxy # 如果不为空则直接将该入站流量交由指定 proxy 处理 (当 proxy 不为空时，这里的 proxy 名称必须合法，否则会出错)
    
    
这里面有个逻辑冲突为:
proxy和rule.
如果proxy不为空, 则不经过rule, 直接把流量交给proxy处理.
我认为这样是不合理的.
应该要同时生效.
proxy也要遵守rule规则.

最终想要的效果是, 同时配置多个代理在不同的端口监听不同的代理, 然后这些代理还可以根据rule规则进行分流.
优先进行rule规则的匹配, 如果匹配成功, 则使用rule规则, 如果匹配不成功, 则使用proxy.
当然, 也可以在rule里面加一个标志, 如果都无法匹配, 则使用当前监听端口的代理.

**Comment by Skyxim** [comment]
proxy: proxy 是指定出口代理
你想要就是不指定 proxy 指定规则即可，这两个本来就是冲突，指定了 proxy 将不会通过规则

**Comment by xuemingyang** [comment]
> 想要就是不指定 proxy 指定规则

但是我还想使用当前出口代理的时候, 使用规则进行分流.

**Comment by Skyxim** [comment]
@xuemingyang 这是入口

**Comment by xuemingyang** [comment]
> @xuemingyang 这是入口

对对, 入口.

但是,  这里的rule和proxy也没有冲突的必要. 如果不想匹配任何规则直接走proxy可以设置rule为空.就表达为不经rule直接走proxy.
如果想使用proxy的同时,进行分流, 这个时候就很无力. 规则层面是做不到的

**Comment by Skyxim** [comment]
自行梳理逻辑

**Comment by xuemingyang** [comment]
> 自行梳理逻辑

逻辑很清晰呀.
就是认为目前设置的rule和proxy冲突是不合理的.
rule生效的优先级应该高于proxy.而不是设置了proxy, 就让rule直接失效了.

**Comment by 13wenwen** [comment]
因为它们的作用是相同的，两者是在效果上是相互平行的，所以两者是冲突的。核心只能在这两个字段之间，选择一个字段来进行处理。两个字段你不管选择哪一个，入站流量的去向就已经确定了。你得明白这是决定入站流量去哪的两种方式，

**Comment by xuemingyang** [comment]
> 因为它们的作用是相同的，两者是在效果上是相互平行的，所以两者是冲突的。核心只能在这两个字段之间，选择一个字段来进行处理。两个字段你不管选择哪一个，入站流量的去向就已经确定了。你得明白这是决定入站流量去哪的两种方式，

其实不一样~~

假设一种场景:
我同时监听了4个端口. 分别对应4个不同的流量出口.
listeners:
- name: proxy_name_19999
  port: 19999
  rule: rule1
  proxy: name_20001
  type: mixed
- name: proxy_name_20001
  port: 20001
  rule: rule1
  proxy: name_20001
  type: mixed
- name: proxy_name_20002
  port: 20002
  proxy: name_20002
  type: mixed
- name: proxy_name_20003
  port: 20003
  proxy: name_20003
  type: mixed
- name: proxy_name_20004
  port: 20004
  proxy: name_20004
  type: mixed
proxies:
- name: name_20001
  port: 6126
  skip-cert-verify: true
  type: socks5
  udp: true
  username: rfcrsnrw
- name: name_20002
  port: 6742
  skip-cert-verify: true
  type: socks5
  udp: true
  username: rfcrsnrw
- name: name_20003
  port: 5083
  skip-cert-verify: true
  type: socks5
  udp: true
  username: rfcrsnrw
- name: name_20004
  port: 6397
  skip-cert-verify: true
  type: socks5
  udp: true
  username: rfcrsnrw
  
  在这种情况下, 20001 - 20004 分别对应四个socks5出口.
  但是这四个出口的流量很贵, 并且很慢.
  我想让19999这个入口的流量作为一个分流端口. 以目前的规则, 就做不到, 冲突了. sing-box却可以.
