### ISSUE TITLE
[Bug] Rule Providers的txt写法没有通配符包含主域名吗

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/mihomo#1205]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Meta_v1.18.1

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
# comment
.blogger.com
*.*.microsoft.com
books.itunes.apple.com
```

### Description

按照这三个示例来写，都无法同时包含x.com与api.x.com
为了实现这个规则，必须写x.com与.x.com这么两条才能实现吗

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/f59ccd08-bfe3-4fa9-a5bc-74ac50eaa7b6)
