### ISSUE TITLE
[Feature] 完善文档对vless quic配置说明

### ISSUE THREAD

**Issue by git10135405** [MetaCubeX/mihomo#1207]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

看了下文档没有明确指出是否支持network的quic支持，要是支持是不是可以完善下文档说明？
另外请教下 如果支持quci协议 如以下vless怎么配置
vless://f4f2ff28-2c22-1455-0000-a2d219a096a0@http.cloudns.as:39010?type=quic&quicSecurity=chacha20-poly1305&key=lj02Fv&headerType=wireguard&security=none#43209-w8sy6o1f

**Comment by xishang0128** [comment]
@git10135405 没写就是不支持,怎么完善

**Comment by git10135405** [comment]
> @git10135405 没写就是不支持,怎么完善

好的，quic怎么样，有计划支持吗？

**Comment by xishang0128** [comment]
@git10135405 没计划支持,要用quic请使用正经quic类协议,如tuic/hy
