### ISSUE TITLE
[Feature] 希望能支持TAP虚拟网卡

### ISSUE THREAD

**Issue by QijYooRytowYum** [MetaCubeX/mihomo#1219]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

1.当Tun模式因为某些原因无法使用，可以用Tap代替。
2.Tap虚拟网卡支持桥接和独立MAC，可在有桥接需求下使用。

**Comment by xishang0128** [comment]
@QijYooRytowYum 不会支持tap
