### ISSUE TITLE
[Feature] 希望全局模式下新配置文件默认选择REJECT或随机选择一个节点

### ISSUE THREAD

**Issue by QijYooRytowYum** [MetaCubeX/mihomo#1220]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

当使用支持mihomo内核的GUI时，因为机场配置中的所有节点出现问题，切换到其他机场的配置或添加新的机场配置后，默认选择DIRECT，未加载完或自动重连的网站通过DIRECT连接，导致真实ip泄露。
希望机场订阅添加或更新后默认选择REJECT或随机选择一个节点，或者可以在配置文件中指定默认节点。

**Comment by xishang0128** [comment]
@QijYooRytowYum 自行创建一个GLOBAL组,就会覆盖了,请自行关闭这个issues

**Comment by jelly21fish** [comment]
@xishang0128 大佬您好！自行创建的GLOBAL组，只要没有包含proxy-groups的所有选项，并按原来的顺序排列，就会导致“代理”页面的排序异常。比如，假设策略组/代理组原本的排序是ABCDEFG，而我添加如下的GLOBAL组
 - {name: GLOBAL, type: select, proxies: [C,B,A]}
这样，代理页面就会显示成：DEFGCBA。我觉得这是设置GLOBAL组的非预期结果。
追根溯源，开启全局模式的默认选择是DIRECT，这本身就很反直觉了，不知有没有优化的可能？
最后，感谢您的付出！

**Comment by jelly21fish** [comment]
@xishang0128 感谢您的回复。
您提到：”使用http api的ui都会按照global组的排序进行排序,如果修改了,排序自然就错误了,这是预期行为“
但是，在我的例子里，GLOBAL组的排序是CBA，而在ui中显示的是DEFGCBA，为什么DFEG会被排到前面？（这里忘了说明，被排到前面的也不是按原顺序，而是变成字符顺序）
更想问的问题是，为什么规则模式下的ui排序，要受GLOBAL组的影响呢？ui能否直接按照groups的顺序进行排序呢？既然这在GLOBAL未修改时可以实现，那说明ui可以通过某种机制复制groups的排序，能否把这个过程和GLOBAL设置的过程分离开来呢？
如果我的提问有什么不当的地方，还望见谅。

**Comment by xishang0128** [comment]
@jelly21fish api展示顺序是

没有被配置的组会按字符在前边显示,只有被配置的组才会按照global顺序显示

**Comment by jelly21fish** [comment]
@xishang0128 感谢您的回复！
所以结论是，ui读取groups顺序的行为，内核本身无法改变，所以这一问题应该在ui、客户端那里进行反馈，对么？

**Comment by xishang0128** [comment]
@jelly21fish 是api给的顺序就依赖global组,除非ui能读配置文件去排序

**Comment by jelly21fish** [comment]
@xishang0128 那么，api的问题应该在哪里反馈呢？在这里的话，api依赖GLOBAL进行排序的这个机制，是否暂时没有调整的计划？不管如何，感谢你们的工作。

**Comment by xishang0128** [comment]
@jelly21fish 不会调整,修改组内建策略组造成的后果自己承担

**Comment by jelly21fish** [comment]
@xishang0128 明白了，谢谢！我看到Allow customization of GLOBAL这个commit https://github.com/MetaCubeX/mihomo/commit/846bdfa8129b9b984a62f04204b4a6925a016834 ，以为之前不能修改，现在可以了，于是才进行尝试，然后发现这个问题。看来还是不适宜修改GLOBAL组。

**Comment by xishang0128** [comment]
@jelly21fish 只是有人想改不阻止
