### ISSUE TITLE
[Feature] 禁止读取系统的hosts

### ISSUE THREAD

**Issue by ztjal** [MetaCubeX/mihomo#1229]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

自己的hosts有定义某些网址为本地ip进行反代，用以前的clash是没问题的，不会用hosts内的定义来解释，但miho会这样干。

本来自己想查一下源码里有没有跳过的办法。

mihomo-1.18.3\component\resolver\host.go

var DisableSystemHosts, _ = strconv.ParseBool(os.Getenv("DISABLE_SYSTEM_HOSTS"))

然后发现竟然没实现功能……

所以请求实现它，配置上实现自己定义开关更好，如：
localhosts: false

**Comment by xishang0128** [comment]
@ztjal 已经实现了,这是读取系统变量,请配置系统变量

**Comment by ztjal** [comment]
> @ztjal 已经实现了,这是读取系统变量,请配置系统变量

请问如何实现呢？文档真的找不到。（dns内的use-hosts设为false也没用）

**Comment by xishang0128** [comment]
@ztjal 自行google配置系统变量,不包教,值=1

**Comment by ztjal** [comment]
> @ztjal 自行google配置系统变量,不包教,值=1

我将DISABLE_SYSTEM_HOSTS加到系统变量，但还是不行，还是解释hosts的IP。

![屏幕截图 2024-04-28 213421](https://github.com/MetaCubeX/mihomo/assets/6552290/00e6814c-2851-4a9f-a2d9-5f200f8d5bd5)

**Comment by xishang0128** [comment]
@ztjal 重启了?是alpha?

**Comment by ztjal** [comment]
没事了，忘


> @ztjal 重启了?是alpha?

不好意思，是我SB，忘记换EXE了，麻烦你了。
