### ISSUE TITLE
This program can only be run on AMD64 processors with v3 microarchitecture support.

### ISSUE THREAD

**Issue by leien0529** [MetaCubeX/mihomo#123]
使用黑群晖docker安装，启动后显示This program can only be run on AMD64 processors with v3 microarchitecture support.

**Comment by Skyxim** [comment]
@leien0529 docker镜像默认提供的是v3的

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.

**Comment by thksdhr** [comment]
> 考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。 Considering that this issue did not use the correct template format, we decided to close it.

我在时也遇到了此问题~
且此问题不是配置问题，这个问题实际是虚拟化平台的原因，他可能使用了PVE的虚拟机，PVE默认使用的虚拟化CPU默认是KVM64，支持的指令集过少所以导致了此问题，比较简单的方法是将PVE的CPU虚拟改为Host或者Max模式即可，或者手动将需要的指令集加入虚拟CPU的支持中，不过那需要对PVE及虚拟机技术有更深入的了解才行。

**Comment by shaoyuyoung** [comment]
@thksdhr 我也遇到了这个问题，我也是用的虚拟机，添加指令集或者模式的更改是不是需要宿主机的权限呀？

**Comment by Skyxim** [comment]
@shaoyuyoung 下载 amd64 v1 后缀的内核即可
