### ISSUE TITLE
[Bug] Sniffer 冗余误解日志

### ISSUE THREAD

**Issue by liangyi9812** [MetaCubeX/mihomo#1236]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并无法自行解决问题
- [x] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

OpenBSD/FreeBSD

### 系统版本

Mac

### Mihomo 版本

latest

### 配置文件

```yaml
无
```

### 描述

开启 Sniffer，无论是否 overrideDest 都会输出 replace domain 日志
https://github.com/MetaCubeX/mihomo/blob/107e3e763009668b174a6ef4d36a4c06e3169930/component/sniffer/dispatcher.go#L120C1-L124C23
代码里注释说因为下面会修改值所以提前打log，但这种行为会造成看debug日志排查时候的误解。
希望有空时顺手改了，非常感谢~

### 重现方式

开启 Sniffer，与 override-destination 无关

### 日志

```shell
[DEBUG] [Sniffer] Sniff tcp [192.168.xx.xx:50676]-->[api.segment.io:443] success, replace domain [api.segment.io]-->[api.segment.io]
```

**Comment by xishang0128** [comment]
改了
