### ISSUE TITLE
[Bug] 访问其他国内网站都正常，但是京东报错

### ISSUE THREAD

**Issue by iamjimmycheng** [MetaCubeX/mihomo#1237]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not carefully reviewed the [documentation](https://wiki.metacubex.one/) and cannot resolve the issue on my own.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

v0.46.003-beta

### Mihomo Version

[v0.46.003-beta]

### Configuration File

```yaml
无
```

### Description

访问大部分都国内、国外网站都正常，唯独访问京东不行，但是换成passwall的话，访问京东就正常了，是DNS的问题吗？我的DNS设置如下：
dns:
  enable: true
  listen: 0.0.0.0:1053
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#DNS_Proxy'
    - 'tls://1.0.0.1#DNS_Proxy'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#h3=true
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 114.114.114.114
      - https://dns.alidns.com/dns-query#h3=true

### Reproduction Steps

 无

### Logs

```shell
2024-04-30 17:33:27 level=warning msg="[TCP] dial DIRECT (match RuleSet/ChinaMaxDomain) 192.168.3.176:57468 --> misc.360buyimg.com:443 error: dial tcp 117.72.226.3:443: i/o timeout"
2024-04-30 17:33:27 level=info msg="[TCP] 192.168.3.176:57472 --> static.360buyimg.com:443 match RuleSet(ChinaMaxDomain) using DIRECT"
2024-04-30 17:33:27 level=warning msg="[TCP] dial DIRECT (match RuleSet/ChinaMaxDomain) 192.168.3.176:57467 --> misc.360buyimg.com:443 error: dial tcp 117.72.226.3:443: i/o timeout"
```

**Comment by xishang0128** [comment]
不存在的版本,且并未提供最简可复现配置
