### ISSUE TITLE
开启tun后，traceroute不能正常使用

### ISSUE THREAD

**Issue by lchannng** [MetaCubeX/mihomo#124]
开启tun后，udp流量被tun代理了，traceroute不能trace到目标地址，clash premium也有这个问题

> 
> traceroute to www.baidu.com (163.177.151.110), 30 hops max, 60 byte packets
>  1  172.17.0.109 (172.17.0.109)  0.444 ms  0.400 ms  0.389 ms
>  2  * * *
>  3  * * *
>  4  * * *
>  5  * * *
>  6  * * *
>  7  * * *
>  8  * * *
>  9  * * *
> 10  * * *
> 11  * * *
> 12  * * *
> 13  * * *
> 14  * * *
> 15  * * *
> 16  * * *
> 17  * * *`

> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:60724 --> 163.177.151.110:33437 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:54839 --> 163.177.151.110:33438 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:34899 --> 163.177.151.110:33449 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:58556 --> 163.177.151.110:33447 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:51508 --> 163.177.151.110:33443 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:60946 --> 163.177.151.110:33444 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:40581 --> 163.177.151.110:33439 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:42476 --> 163.177.151.110:33445 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:45150 --> 163.177.151.110:33440 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:51789 --> 163.177.151.110:33441 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:46498 --> 163.177.151.110:33446 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:39502 --> 163.177.151.110:33442 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:40494 --> 163.177.151.110:33448 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:39939 --> 163.177.151.110:33452 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:38217 --> 163.177.151.110:33450 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:54Z" level=info msg="[UDP] 172.17.0.233:34023 --> 163.177.151.110:33451 match GeoIP(CN) using DIRECT"
> time="2022-07-16T13:28:59Z" level=info msg="[UDP] 172.17.0.233:59942 --> 163.177.151.110:33453 match GeoIP(CN) using DIRECT"

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
