### ISSUE TITLE
[Feature] 配置文件中增加测速超时时间

### ISSUE THREAD

**Issue by huajideshutiao** [MetaCubeX/mihomo#1242]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望在配置文件中增加测速超时时间这个配置项，比如我个人几乎不会用超过800ms的节点，测速时默认的5秒5次tcp握手失败才超时有点太长了。
metacubexd面板中好像有对应设置，如果我在面板中设置之后，不打开面板的情况下内核还会按照我设置的超时时间进行处理吗？

**Comment by xishang0128** [comment]
> * [x]   我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.

https://wiki.metacubex.one/config/proxy-groups/#timeout

**Comment by huajideshutiao** [comment]
> > * [x]    我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.
> 
> https://wiki.metacubex.one/config/proxy-groups/#timeout

😂下次不犯了

**Comment by huajideshutiao** [comment]
> > * [x]    我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.
> 
> https://wiki.metacubex.one/config/proxy-groups/#timeout

我试了下，设置为800，但是从yacd meta面板上看还是有接近5秒的节点，好像没生效啊

**Comment by huajideshutiao** [comment]
> > * [x]    我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.
> 
> https://wiki.metacubex.one/config/proxy-groups/#timeout

我试了下，设置为800，但是从yacd meta面板上看还是有接近5秒的节点，好像没生效啊

**Comment by xishang0128** [comment]
@huajideshutiao 主动测试是主动测试,hc是hc,主动测试由前端控制

**Comment by huajideshutiao** [comment]
> @huajideshutiao 主动测试是主动测试,hc是hc,主动测试由前端控制

我没有用面板进行测试，就是单纯看一下节点对应延迟的。

**Comment by xishang0128** [comment]
@huajideshutiao 用provider的改provider的hc,groups的只负责proxies

**Comment by huajideshutiao** [comment]
> @huajideshutiao 用provider的改provider的hc,groups的只负责proxies

可以了，感谢算命😇
