### ISSUE TITLE
GLOBAL

### ISSUE THREAD

**Issue by ldh1983** [MetaCubeX/mihomo#1246]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

编辑了GLOBAL分组后在cmfa上根本不生效，只是规则模式下多了个GLOBAL分组，且这个分组不是自己设置的样子，而是没有设置这个分组时全局模式下的的样子。也就是不是自己设置的GLOBAL覆盖了自动生成的GLOBAL，而是自动生成的GLOBAL把自己设置的GLOBAL给覆盖掉。不知是cmfa的问题还是mihomo核心的问题。因为在verge上也有一点点不正常。verge是自己编辑的GLOBAL分组没有出现在规则分组且在全局模式下正常显示出我设置的样子。但是编辑了GLOBAL分组后，它让规则模式下的分组显示顺序发生了变化，不按照我在配置文件中编辑的顺序，而是用分组名称的第一个字母按照字母表的顺序排序。希望改进后能按照自己设置的意愿正常显示。

### Possible Solution

希望改进后能按照自己设置的意愿正常显示。

**Comment by jelly21fish** [comment]
我在 https://github.com/MetaCubeX/mihomo/discussions/1306 提到了同一问题，看来有相同疑惑的不止我一个人。GLOBAL的默认选择是DIRECT，还需要手动改掉，这本身就十分反直觉。同时，感谢开发者的付出，希望对GLOBAL能有所优化，可惜自己不会相关代码无法协助。

**Comment by xishang0128** [comment]
gui客户端的issues不应发布在内核issues
