### ISSUE TITLE
[Feature]  关于tunnel.go的 match() 函数的优化建议

### ISSUE THREAD

**Issue by snakem982** [MetaCubeX/mihomo#1247]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

关于tunnel.go的 [match()](https://github.com/MetaCubeX/mihomo/blob/Alpha/tunnel/tunnel.go#L595) 函数的优化建议
看了源码发现该函数在每次请求时会对规则进行遍历，如果规则少的话函数效率没啥问题，
但是规则多达上千上万的话，效率会有所降低， **因此希望增加缓存**
**针对重复请求**除首次外直接从缓存返回Proxy
LRU LFU 缓存机制都可以，这样能减少很多无用的遍历

**Comment by Skyxim** [comment]
存在过度优化，并且在这种逻辑下由于元数据维度具有多样性，并不能正确实现判断

**Comment by snakem982** [comment]
> 存在过度优化，并且在这种逻辑下由于元数据维度具有多样性，并不能正确实现判断

好的，了解了
