### ISSUE TITLE
[Feature] 请求更新 ClashMetaForAndroid 的内核

### ISSUE THREAD

**Issue by aersoi** [MetaCubeX/mihomo#1252]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

当前 ClashMetaForAndroid 的内核为 1.7.0

[MetaCubeX/ClashMetaForAndroid (core/src/foss/golang/go.mod)](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/main/core/src/foss/golang/go.mod#L47-L57)
```go
github.com/metacubex/gopacket v1.1.20-0.20230608035415-7e2f98a3e759 // indirect
github.com/metacubex/gvisor v0.0.0-20240320004321-933faba989ec // indirect
github.com/metacubex/mihomo v1.7.0 // indirect
github.com/metacubex/quic-go v0.43.1-0.20240428051621-a109abfb4cf6 // indirect
github.com/metacubex/sing-quic v0.0.0-20240429040940-fa3a4ff2533e // indirect
github.com/metacubex/sing-shadowsocks v0.2.6 // indirect
github.com/metacubex/sing-shadowsocks2 v0.2.0 // indirect
github.com/metacubex/sing-tun v0.2.6 // indirect
github.com/metacubex/sing-vmess v0.1.9-0.20231207122118-72303677451f // indirect
github.com/metacubex/sing-wireguard v0.0.0-20240321042214-224f96122a63 // indirect
github.com/metacubex/tfo-go v0.0.0-20240228025757-be1269474a66 // indirect
```
而当前 ClashMeta 的内核为 1.18.4

**Comment by xishang0128** [comment]
cmfa内核一直在更新,且内核仓库不接受来自cmfa的任何问题
