### ISSUE TITLE
trojan-go协议在mihomo中支持ss的AEAD加密[Feature] 

### ISSUE THREAD

**Issue by AquaSimulacra** [MetaCubeX/mihomo#1269]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在服务端配置了trojan-go以及为其加入ss的AEAD的加密后，可以使安全性更上一层楼，然而，目前mihomo并没有配置trojan的AEAD加密方法。由于AEAD加密需要在服务端和客户端的配置与密码完全相同的情况下，服务端才可以与客户端正常通讯，所以如果服务端的trojan-go开启了AEAD加密，会导致mihomo客户端无法使用trojan。

### Possible Solution

...
transport:
	protocol: shadowsocks
	cipher: aes-256-gcm
	password: "example"
...

**Comment by wwqgtxx** [comment]
ok
https://github.com/MetaCubeX/mihomo/blob/0b6ae6ffb881872e3ff7a0b4454bb43a1b178dd3/docs/config.yaml#L614-L617

**Comment by AquaSimulacra** [comment]
Has this been added to mihomo 1.18.5?

**Comment by wwqgtxx** [comment]
目前还在alpha版本中

**Comment by AquaSimulacra** [comment]
Thank you for your good work!
