### ISSUE TITLE
[Feature] 希望app可以保存上次测速后的结果

### ISSUE THREAD

**Issue by Zhizhr** [MetaCubeX/mihomo#1274]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望可以启动后直接看到上次测速的结果，现在启动后有的显示有的不显示。
另外可以支持单个节点独自测速就好了。

**Comment by xishang0128** [comment]
缓存测试数据是无意义的,重新启动数据已经过时,并没有任何参考意义
单节点测试一直都支持 https://wiki.metacubex.one/api/#proxiesproxies_namedelay
