### ISSUE TITLE
改进 ebpf分流方式

### ISSUE THREAD

**Issue by EternalARK** [MetaCubeX/mihomo#1278]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前clash meta已经支持基本的ebpf分流。但是这个分流几乎没有意义；即使是direct的分流依然会经过clash tunnel。如果可以希望所有走direct流的流量都可以ebpf直连。

### Possible Solution

更改ebpf实现方式使分流direct的所有连接直连。

**Comment by xishang0128** [comment]
在ebpf区分流量意味着没法进行域名分流,所以这个功能不会做

**Comment by ArcticLampyrid** [comment]
> 在ebpf区分流量意味着没法进行域名分流

是否方便提供一些技术细节？
基于 eBPF 实现的 https://github.com/daeuniverse/dae 似乎支持域名分流

**Comment by Skyxim** [comment]
这需要大幅修改以满足将程序加载至内核，和原本目标冲突

**Comment by xishang0128** [comment]
> > 在ebpf区分流量意味着没法进行域名分流
> 
> 是否方便提供一些技术细节？ 基于 eBPF 实现的 https://github.com/daeuniverse/dae 似乎支持域名分流

dae是通过dns映射支持的,但是这并不完善,如果两个域名都是同一个ip,那么这两个域名都可能进入用户态程序,通过嗅探获取域名

**Comment by xiandu999-yu** [comment]
放弃支持了...

**Comment by ArcticLampyrid** [comment]
> 这需要修改以满足将程序加载至内核，和原本目标冲突

是否有可能先支持一些简单的 filter，例如根据进程名进行筛选，这样可以把各种 P2P 类应用从 Clash Tunnel 中摘除出去，大大减小需要处理的连接数。

**Comment by PuerNya** [comment]
@ArcticLampyrid ebpf 已移除

**Comment by ArcticLampyrid** [comment]
> 看样子是 Windows 环境，能否使用 epbf 实现不太清楚

是 Linux 用户（逃

**Comment by lyb-human** [comment]
啊啊啊啊，这逼AI害我，我说mihomo什么支持了epbf，唉....

**Comment by jellyterra** [comment]
> dae是通过dns映射支持的,但是这并不完善,如果两个域名都是同一个ip,那么这两个域名都可能进入用户态程序,通过嗅探获取域名
> 
> 如果dns劫持不到,那就只能是纯ip分流,ip可能不会进入用户态程序进行域名分流,直接直连

软路由核心太菜带不动，我想让 ebpf 或者 ip set 把能直连的分出去，也想到了这些问题，就，没办法呗 😢
