### ISSUE TITLE
[Feature] 可以对syn请求加密或者做一些预验证处理

### ISSUE THREAD

**Issue by flowerseacar** [MetaCubeX/mihomo#1280]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

因为一些vps经常遭受别人的ddos攻击，其中tcp最为常见的就是syn,可以让那个vps开放的端口去对syn请求进行预共享密钥处理之类的吗，没有密钥的syn请求一律丢掉这种。

**Comment by yellowsavant** [comment]
这是fw层面的事情，跟clash没有太大关系，况且谁都能发syn，这种建立连接的flag说实话也没啥好处理的，做一个IP白名单可能就符合你的需要了

**Comment by xishang0128** [comment]
这不是代理工具该处理的
