### ISSUE TITLE
[Feature]  源码 proxydialer.go 的 NewByName 方法，如果在proxy-providers里配置了 dialer-proxy  这里不会返回节点，不知这算不算bug ?

### ISSUE THREAD

**Issue by snakem982** [MetaCubeX/mihomo#1284]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

[源码](https://github.com/MetaCubeX/mihomo/blob/Alpha/component/proxydialer/proxydialer.go#L29) 这里只返回proxies里配置的节点，
如果我的节点都在proxy-providers里，proxies就是个空参数，下方代码就不会返回节点了
这样我在proxy-providers里配置的节点，设置了 dialer-proxy 它就会报错
不知这算不算bug ? 
还是默认设计不支持在proxy-providers里 配置 dialer-proxy 参数
```go
func NewByName(proxyName string, dialer C.Dialer) (C.Dialer, error) {
	proxies := tunnel.Proxies()
	if proxy, ok := proxies[proxyName]; ok {
		return New(proxy, dialer, true), nil
	}
	return nil, fmt.Errorf("proxyName[%s] not found", proxyName)
}
```

### Possible Solution

添加返回 proxy-providers 里配置的节点

**Comment by xishang0128** [comment]
这是预期行为,proxy-provider只能被策略组引用
