### ISSUE TITLE
[Feature] snell这个古老的玩意儿有意向更新么？

### ISSUE THREAD

**Issue by xiandu999-yu** [MetaCubeX/mihomo#1290]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

遨游github的时候发现snell有版本4了...所以问问

**Comment by xishang0128** [comment]
@xiandu999-yu Snell4老刘不给逆向,别想了

**Comment by xiandu999-yu** [comment]
> @xiandu999-yu Snell4老刘不给逆向,别想了

唉...

**Comment by gengjiawen** [comment]
> [@xiandu999-yu](https://github.com/xiandu999-yu) Snell4老刘不给逆向,别想了

之前也不给逆向的。主要是之前逆向的人暂时没时间了。还是挺期待逆向 4, 5 的

**Comment by gengjiawen** [comment]
哈哈，终于有人逆向成功了

**Comment by xiandu999-yu** [comment]
> 哈哈，终于有人逆向成功了

看见了，已经在github上找了个延迟不错的snell
