### ISSUE TITLE
希望增加对DoH/3的支持

### ISSUE THREAD

**Issue by BlessandKathy** [MetaCubeX/mihomo#130]
DNS over HTTPS/3已经发布标准了，也有不少公共DNS支持，而且在拥堵网络环境中也比其他协议有优势，希望支持

**Comment by Skyxim** [comment]
@BlessandKathy 使用h3 https://mozilla.cloudflare-dns.com/dns-query#h3=true
仅强制开启无回落

**Comment by samlux04** [comment]
Tried with nextdns it only worked for a brief few seconds then constantly failed.
`[DNS Server] Exchange ;a.nel.cloudflare.com. IN A failed: all DNS requests failed, first error: Post "https://dns.nextdns.io/fd44f5/clash%20Meta": INTERNAL_ERROR: short buffer`

![IMG_20220722_081045](https://user-images.githubusercontent.com/85811479/180335406-ec581872-9493-40b3-827d-f03581ce70e4.jpg)

**Comment by Skyxim** [comment]
@samlux04 What's your OS, Windows?

**Comment by samlux04** [comment]
> @samlux04 What's your OS, Windows?

Android. Also tried with windows the same problem.

**Comment by Kingsmanvn-Official** [comment]
@samlux04 How do you make Clash hijack dns and forward to local

**Comment by samlux04** [comment]
> @samlux04 How do you make Clash hijack dns and forward to local

Just put local address?🤔
