### ISSUE TITLE
[Bug] v1.18.4 开始，proxy-provider 中包含 vmess://xxxxxxx 节点会导致内核退出

### ISSUE THREAD

**Issue by leic4u** [MetaCubeX/mihomo#1302]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 11 23H2 22635.3646

### Mihomo 版本

Mihomo Meta v1.18.5 windows amd64 with go1.22.3 Sun May 19 08:49:31 UTC 2024
Use tags: with_gvisor

### 配置文件

节点信息如下，已脱敏。

```yaml
vmess://ewogICJhZGQiOiAiZG9tYWluLm15dnBzLmNvbSIsCiAgImFpZCI6IDAsCiAgImhvc3QiOiBudWxsLAogICJpZCI6ICI2NzE5OWM2Mi03Yzg1LTQ4Y2UtYjQyMC01NTJlNDM3MTgzYjYiLAogICJuZXQiOiAid3MiLAogICJwYXRoIjogIi93ZWJzb2NrZXRwYXRoIiwKICAicG9ydCI6IDEyMzQ1LAogICJwcyI6ICJ2bWVzcyt3cyIsCiAgInNuaSI6ICIiLAogICJ0bHMiOiAibm9uZSIsCiAgInYiOiAyCn0=
```

### 描述

v1.18.4 & v1.18.5两个版本都会出现此问题，只要 proxy-provider 包含了以上节点，内核就会退出。
v1.18.3 正常。

### 重现方式

将上方样例节点添加到 proxy-provider 拉取到的本地文件（该文件其他节点也是 URI 格式）后，重新启动内核，即可观察到错误。

或者把上方样例节点单独做一个 proxy-provider 也可以。

**Comment by xishang0128** [comment]
@leic4u 这是一个错误的节点,host为null,请正确书写

**Comment by leic4u** [comment]
> @leic4u 这是一个错误的节点,值不能为null,请正确书写
> 
> `echo "ewogICJhZGQiOiAiZG9tYWluLm15dnBzLmNvbSIsCiAgImFpZCI6IDAsCiAgImhvc3QiOiBudWxsLAogICJpZCI6ICI2NzE5OWM2Mi03Yzg1LTQ4Y2UtYjQyMC01NTJlNDM3MTgzYjYiLAogICJuZXQiOiAid3MiLAogICJwYXRoIjogIi93ZWJzb2NrZXRwYXRoIiwKICAicG9ydCI6IDEyMzQ1LAogICJwcyI6ICJ2bWVzcyt3cyIsCiAgInNuaSI6ICIiLAogICJ0bHMiOiAibm9uZSIsCiAgInYiOiAyCn0=" | base64 -d` 内容为 { "add": "domain.myvps.com", "aid": 0, "host": null, "id": "67199c62-7c85-48ce-b420-552e437183b6", "net": "ws", "path": "/websocketpath", "port": 12345, "ps": "vmess+ws", "sni": "", "tls": "none", "v": 2 }

确实是这个问题。加上 `hosy` 的值之后 v1.18.5 可以正常使用了。

这个校验是从 v1.18.4 才加上的吗？我测试 v1.18.3 是可以不报错的。

另外是否考虑友好一点的提示方式呢，而不是直接退出。

**Comment by xishang0128** [comment]
@leic4u 这是值的类型错误导致的panic,并不是退出,log会有提示
配置错误问题内核不会主动去兼容处理
