### ISSUE TITLE
[Feature] Proxy-provider 中的节点使用 URI 格式时，如何确认 mihomo 已正确识别到所有参数？

### ISSUE THREAD

**Issue by leic4u** [MetaCubeX/mihomo#1313]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

比如 TCP Brutal 参数，配置了才生效，没配置也不影响节点的连通性，只是没开启 Brutal 算法而已。

或者有没有方法可以查看 mihomo 内核最终运行的节点配置？

### Possible Solution

支持打印 proxy-provider 的在 mihomo 内存中的最终节点配置。

**Comment by xishang0128** [comment]
@leic4u 没法确认,打印在日志是不安全的行为,既然是自己写的那就写成yaml

**Comment by leic4u** [comment]
> @leic4u 没法确认,打印在日志是不安全的行为,既然是自己写的那就写成yaml

那有没有可能生成一份最终配置文件呢？类似于 GUI 客户端上的查看 merge 后的当前配置这种。

**Comment by xishang0128** [comment]
@leic4u 不能,真要验证就写一个1测试不就好了

**Comment by leic4u** [comment]
现在 x-ui 和 s-ui 这种面板，分享出来的都是 URI 链接。看来暂时只能继续手搓配置了。😂

希望后续能有更好的查看最终配置的方式。

感谢回复。🫡
