### ISSUE TITLE
[Bug] 订阅链接IPV6地址重复套中括号[]

### ISSUE THREAD

**Issue by siasbaily** [MetaCubeX/mihomo#1317]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

WIN11

### Mihomo Version

[TCP] dial GLOBAL 127.0.0.1:58162 --> www.msftconnecttest.com:80 error: [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443 connect error: address [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443: missing port in address

### Configuration File

```yaml
[TCP] dial GLOBAL 127.0.0.1:58162 --> www.msftconnecttest.com:80 error: [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443 connect error: address [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443: missing port in address
```

### Description

订阅链接加有解析器，IPV6地址已经加了中括号[]，但拉取订阅链接节点时，仍然在外面又套了中括号，导致IPV6节点无法使用。同样的订阅链接在V2RAY、小火箭、QX、Surge上都可正常使用，应该就是重复[]造成的。

### Reproduction Steps

订阅链接加有解析器，IPV6地址已经加了中括号[]，如“[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]:443”。但拉取订阅链接节点时，仍然在外面又套了中括号，导致IPV6节点无法使用。同样的订阅链接在V2RAY、小火箭、QX、Surge上都可正常使用，应该就是重复[]造成的。

### Logs

```shell
[TCP] dial GLOBAL 127.0.0.1:58162 --> www.msftconnecttest.com:80 error: [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443 connect error: address [[2606:4700:e3:e2d4:2564:32af:d29b:6c1b]]:443: missing port in address
```

**Comment by xishang0128** [comment]
这是一个无效的问题
