### ISSUE TITLE
[Bug] ipv6通过redirect/tproxy代理，使用dnslookup时，日志只记录ipv4 DNS请求的连接，没有ipv6 DNS的连接

### ISSUE THREAD

**Issue by jelly21fish** [MetaCubeX/mihomo#1319]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows, Linux

### 系统版本

Windows10, ImmortalWrt 23.05.2

### Mihomo 版本

ImmortalWrt系统OpenClash的内核（抱歉，不知道在哪输入mihomo命令）：
Meta内核版本: alpha-gcacfefa

Win系统Clash Nyanpasu的内核（输入命令的是.\mihomo-alpha -v，因为我设置的内核是alpha分支的）：
Mihomo Meta alpha-0d4e57c windows amd64 with go1.22.3 Fri Jun  7 13:44:26 UTC 2024
Use tags: with_gvisor

### 描述

为了测试不同DNS在代理和直连状态下的表现，我在ImmortalWrt的终端，使用[dnslookup](https://github.com/ameshkov/dnslookup)分别向 https://1.1.1.1/dns-query 和 https://[2606:4700:4700::1001]/dns-query 发起解析，都成功返回结果。

但是，在OpenClash的日志中，我只找到向1.1.1.1发起请求的连接，没有看到2606:4700:4700::1001的记录，进而也不确定这个DOH请求是否经过了代理。

接着，我在Win系统的powershell使用dnslookup，向 https://[2606:4700:4700::1001]/dns-query 发起解析，OpenClash的日志成功记录了连接。

为了排除OpenClash客户端的问题，我将其关闭，开启Clash Nyanpasu的Tun模式，并在powershell使用dnslookup。结果，Clash Nyanpasu的日志也只记录到1.1.1.1的连接。

提问的主要目的是：1）弄清“1.1.1.1/1.0.0.1有记录而2606:4700:4700::1001没记录”背后的机制逻辑，这是否表示ipv6流量没有完全经过代理？2）如果不经过代理，这是否是预期行为？如果不是，希望能修复。3）如果经过代理，为何日志没有显示？既然ipv4的DOH、DOT请求可以显示，希望ipv6的也可以在日志显示。

不论如何，感谢开发者的付出和贡献！若提问有不当之处，还望见谅。

### 重现方式

开启ipv6代理和ipv6解析 **（更新：模式需选择redirect/tproxy，TUN模式没有问题）** 
选择支持ipv6的节点，启动OpenClash
在终端输入命令：dnslookup baidu.com https://[2606:4700:4700::1001]/dns-query 返回解析结果
在终端输入命令：dnslookup baidu.com https://1.1.1.1/dns-query 返回解析结果
查看日志，只看到：[TCP] 192.168.1.2:35404 --> 1.1.1.1:443

使用tls://1.0.0.1，也可以看到[TCP] 192.168.1.2:54250 --> 1.0.0.1:853
使用tls://[2606:4700:4700::1111]，可以解析，但在日志里也没有记录

在PC的powershell输入命令，在OpenClash上看到日志：[TCP] [2xxx:xxxx]:59868 --> [2606:4700:4700::1001]:853 
关闭OpenClash，开启Clash Nyanpasu
在powershell输入命令，只看到日志：[TCP] 198.18.0.1:65422 --> 1.1.1.1:853 **（更新：是PC权限设置问题，修改后，使用TUN模式没有问题）** 

### 日志

```shell
06-12 22:20:42INFO
[TCP] 198.18.0.1:65348 --> static-pcs-sdk-server.alibaba.com:80 match GeoIP(cn) using DIRECT
06-12 22:20:48INFO
[TCP] 198.18.0.1:65355 --> self.events.data.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
06-12 22:21:05INFO
[TCP] 198.18.0.1:65380 --> www.google.com:443 match DomainKeyword(google) using Proxy[新加坡01]
06-12 22:21:36INFO
[TCP] 198.18.0.1:65403 --> static-pcs-sdk-server.alibaba.com:80 match GeoIP(cn) using DIRECT
06-12 22:21:37INFO
[TCP] 198.18.0.1:65406 --> accounts.google.com:443 match DomainKeyword(google) using Proxy[新加坡01]
06-12 22:22:01INFO
[TCP] 198.18.0.1:65422 --> 1.1.1.1:853 match Match using Proxy[新加坡01]
06-12 22:22:05INFO
[TCP] 198.18.0.1:65429 --> www.google.com:443 match DomainKeyword(google) using Proxy[新加坡01]
06-12 22:22:30INFO
[TCP] 198.18.0.1:65446 --> service-aggregation-layer-subs.juno.ea.com:443 match Match using Proxy[新加坡01]
06-12 22:23:00INFO
[TCP] 198.18.0.1:65480 --> array801.prod.do.dsp.mp.microsoft.com:443 match DomainSuffix(microsoft.com) using DIRECT
```

Clash Nyanpasu不知为何设置debug等级仍只有info内容，找到办法后会补充。
与此同时（两个dnslookup命令的间隔远小于1分钟）：

```
PS F:\dnslookup> .\dnslookup baidu.com https://[2606:4700:4700::1001]/dns-query
dnslookup v1.10.1
Server: https://[2606:4700:4700::1001]/dns-query

dnslookup result (elapsed 127.9963ms):
;; opcode: QUERY, status: NOERROR, id: 14820
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.     IN       A

;; ANSWER SECTION:
baidu.com.      295     IN      A       110.242.68.66
baidu.com.      295     IN      A       39.156.66.10

PS F:\dnslookup> .\dnslookup baidu.com tls://1.1.1.1
dnslookup v1.10.1
Server: tls://1.1.1.1

dnslookup result (elapsed 157.3404ms):
;; opcode: QUERY, status: NOERROR, id: 23739
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.     IN       A

;; ANSWER SECTION:
baidu.com.      479     IN      A       39.156.66.10
baidu.com.      479     IN      A       110.242.68.66
```
### 配置文件

```yaml
mode: rule
mixed-port: 11111
allow-lan: false
log-level: debug
ipv6: true
external-controller: 127.0.0.1:12345
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://223.5.5.5/dns-query
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true

#代理和规则部分省略
```

**Comment by jelly21fish** [comment]
找到debug日志的查看方法了，结果如下：

```
24-06-13 00:18:17[ info ][TCP] 198.18.0.1:54853 --> steamcommunity.com:443 match DomainSuffix(steamcommunity.com) using Proxy[新加坡01]
24-06-13 00:18:16[ debug ][Rule] use default rules
24-06-13 00:18:16[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:49766
24-06-13 00:17:49[ info ][TCP] 198.18.0.1:54835 --> static-pcs-sdk-server.alibaba.com:80 match GeoIP(cn) using DIRECT
24-06-13 00:17:49[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:49[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:49[ debug ][DNS] static-pcs-sdk-server.alibaba.com --> 111.62.167.236
24-06-13 00:17:49[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:49[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:49[ debug ][Rule] use default rules
24-06-13 00:17:49[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:62002
24-06-13 00:17:46[ info ][TCP] 198.18.0.1:54832 --> activity.windows.com:443 match DomainSuffix(windows.com) using Proxy[新加坡01]
24-06-13 00:17:46[ debug ][Rule] use default rules
24-06-13 00:17:33[ info ][TCP] 198.18.0.1:54816 --> static-pcs-sdk-server.alibaba.com:80 match GeoIP(cn) using DIRECT
24-06-13 00:17:33[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:33[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:33[ debug ][DNS] static-pcs-sdk-server.alibaba.com --> 111.63.137.116
24-06-13 00:17:33[ debug ][DNS] static-pcs-sdk-server.alibaba.com --> [] AAAA from https://223.5.5.5:443/dns-query
24-06-13 00:17:33[ debug ][DNS] resolve static-pcs-sdk-server.alibaba.com from https://223.5.5.5:443/dns-query
24-06-13 00:17:33[ debug ][DNS] cache hit for static-pcs-sdk-server.alibaba.com., expire at 2024-06-13 00:32:05
24-06-13 00:17:33[ debug ][Rule] use default rules
24-06-13 00:17:33[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:59692
24-06-13 00:17:32[ info ][TCP] 198.18.0.1:54815 --> 1.1.1.1:853 match Match using Proxy[新加坡01]
24-06-13 00:17:32[ debug ][Rule] use default rules
24-06-13 00:17:26[ info ][TCP] 198.18.0.1:54811 --> clientservices.googleapis.com:443 match DomainKeyword(google) using Proxy[新加坡01]
24-06-13 00:17:26[ debug ][Rule] use default rules
24-06-13 00:17:26[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:60365
```
同时进行的dnslookup查询：
```
PS F:\dnslookup> .\dnslookup baidu.com tls://1.1.1.1
dnslookup v1.10.1
Server: tls://1.1.1.1

dnslookup result (elapsed 153.3348ms):
;; opcode: QUERY, status: NOERROR, id: 2144
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.     IN       A

;; ANSWER SECTION:
baidu.com.      279     IN      A       39.156.66.10
baidu.com.      279     IN      A       110.242.68.66

PS F:\dnslookup> .\dnslookup baidu.com tls://[2606:4700:4700::1001]
dnslookup v1.10.1
2024/06/13 00:17:58 [fatal] Cannot make the DNS request: getting conn to tls://[2606:4700:4700::1001]:853: connecting to 2606:4700:4700::1001: dial tcp [2606:4700:4700::1001]:853: i/o timeout
PS F:\dnslookup> .\dnslookup baidu.com https://[2606:4700:4700::1001]/dns-query
dnslookup v1.10.1
Server: https://[2606:4700:4700::1001]/dns-query

dnslookup result (elapsed 189.5873ms):
;; opcode: QUERY, status: NOERROR, id: 29674
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.     IN       A

;; ANSWER SECTION:
baidu.com.      196     IN      A       39.156.66.10
baidu.com.      196     IN      A       110.242.68.66
```

**Comment by xishang0128** [comment]
请确保你的配置没有被客户端/工具覆盖,或者直接运行内核

另外这不是可复现问题的最简配置

**Comment by jelly21fish** [comment]
@xishang0128 感谢您的回复！

我粘贴的配置是Clash Nyanpasu的“运行配置”，也就是已经覆盖过的配置。我复制时只删除了proxy-provider，填入支持ipv6的订阅就能用来复现问题了。

您说"这不是可复现问题的最简配置"，我看到要求是不能依赖“远程服务器、TUN、图形界面客户端或者其他闭源软件”。很抱歉我对具体要求的理解不够充分。是不是只要节点服务器需要支持ipv6、TUN模式需要开启，这就不能算是可复现问题的最简配置？但这都和问题本身相关。

还是说，这里的要求是：必须直接使用内核，来排除客户端的干扰？我没尝试过直接运行，但会学习如何使用，复现问题后会再反馈。

不过，还是很希望维护者能尝试一下dnslookup，看日志能不能捕捉到ipv6 DNS的请求。不管如何，再次感谢！

**Comment by xishang0128** [comment]
> @xishang0128 感谢您的回复！
> 
> 我粘贴的配置是Clash Nyanpasu的"运行配置"，也就是已经覆盖过的配置。我复制时只删除了proxy-provider，填入支持ipv6的订阅就能用来复现问题了。

运行配置不等于最终配置,内核内部的配置是可以被patch修改的

以及,最简配置就是能删的都删,只保留用于复现必须的功能(比如只保留tun)

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/1caeff39-c341-4e5b-9b62-86e34efeacfa)
并且我测试没问题

**Comment by jelly21fish** [comment]
@xishang0128 感谢您的回复！

抱歉我理解错了。我看到后面要求完整配置，怕自己删到了必要的部分，影响判断。

我刚刚下载了最新内核并尝试直接运行，但失败了。这其实也是我在使用Win客户端时遇到的问题：在打开ipv6的时候，开启TUN，会出错。必须先打开TUN，再开启ipv6。我怀疑，日志不显示所述内容，也与这个问题有关。

PS F:\> .\mihomo -v
Mihomo Meta alpha-d96d765 windows amd64 with go1.22.4 Thu Jun 13 01:09:42 UTC 2024
Use tags: with_gvisor
PS F:\> .\mihomo -f fzg.yaml
time="2024-06-13T14:42:49.1192256+08:00" level=info msg="Start initial configuration in progress"
time="2024-06-13T14:42:49.1497084+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-06-13T14:42:49.1497685+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-06-13T14:42:49.1547416+08:00" level=info msg="Initial configuration complete, total time: 7ms"
time="2024-06-13T14:42:49.155805+08:00" level=info msg="RESTful API listening at: 127.0.0.1:12345"
time="2024-06-13T14:42:49.1585445+08:00" level=info msg="Sniffer is closed"
time="2024-06-13T14:42:49.159063+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:11111"
time="2024-06-13T14:42:49.1611752+08:00" level=warning msg="[TUN] default interface changed by monitor,  => 以太网"
time="2024-06-13T14:42:49.4842474+08:00" level=error msg="Start TUN listening error: configure tun interface: set ipv6 dns: Access is denied."
……下面是health check的内容，然后就没有了。

不知道您是否开启了ipv6代理和解析？

**Comment by xishang0128** [comment]
@jelly21fish 你本地存在ipv6地址吗

**Comment by jelly21fish** [comment]
@xishang0128 感谢回复，有的。不过听您这么说，感觉我网络设置可能有问题。

![1234](https://github.com/MetaCubeX/mihomo/assets/131505153/73409f1e-bbeb-4a45-a3d9-62b1267e7d08)

**Comment by xishang0128** [comment]
@jelly21fish 看看注册表  \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters 是不是丢了

**Comment by jelly21fish** [comment]
@xishang0128 谢谢！好像真没有。我为了管理各设备的ipv6地址，把路由器的SLAAC关了，只用有状态ipv6，不知道有没有关系…

![1234](https://github.com/MetaCubeX/mihomo/assets/131505153/5c15b98b-37bf-4938-8fda-3d98ab8fce4d)

**Comment by HydrangeaPurple** [comment]
> @xishang0128 谢谢！我找找…

[tcpip6 parameters.reg.txt](https://github.com/user-attachments/files/15815345/tcpip6.parameters.reg.txt)
![Snipaste_2024-06-13_15-19-48](https://github.com/MetaCubeX/mihomo/assets/21093249/ab291a78-807c-4959-ac2d-829c9584e853)

如果注册表丢了只能这么解决了, 或者重装系统

**Comment by HydrangeaPurple** [comment]
> 原来的上面那些文件夹都是空的，可能确实是"丢了"…

上面这些 "UUID" 项代表的不同的网卡, 这些网卡包括了虚拟网卡, WAN拨号, VPN等. 不是所有网卡上都有ipv6是正常的, tun写不进去就是权限问题.

**Comment by jelly21fish** [comment]
@HydrangeaPurple 谢谢！我Parameters那里确实也没有Dhcpv6那一项…可能是我手动设置时折腾没了。我试试怎么解决。

但我还是不明白，我在ImmortalWrt上用dnslookup和OpenClash，也存在看不到那部分日志的问题。

难道路由器的网络设置也有错误？我为了管理各设备的ipv6地址，把路由器的SLAAC关了，只用有状态ipv6（这导致我的PC只能手动设置ipv6）不知道有没有关系。

**Comment by xishang0128** [comment]
@jelly21fish OpenWrt尝试运行内核,而不是使用其他工具运行

**Comment by HydrangeaPurple** [comment]
> SLAAC

为了保证安卓设备的正常获取ipv6, 请尽量使用 SLAAC 而不是DHCPv6, 而windows和mac都是同时支持SLAAC和DHCPv6的.

**Comment by jelly21fish** [comment]
@HydrangeaPurple 谢谢！其实我就是为了不让安卓获取ipv6（只有安卓设备测出webrtc的ipv6泄漏，不知原因为何，但这是另一话题了）才关闭SLAAC的。

按照您说的添加了权限，成功运行了！日志也成功获取到了[TCP] [fdfe:dcba:9876::1]:52296 --> [2606:4700:4700::1001]:443 match Match using Proxy[新加坡01]

@xishang0128 下面准备尝试在Wrt上直接运行内核，一会儿再反馈情况。感谢两位大佬的帮助！

**Comment by jelly21fish** [comment]
按照该教程 https://qing.shuncs.com/post/tech/clashinst 在openwrt/immortalwrt上直接运行了mihomo内核。

日志成功记录到：[TCP] [fdfe:dcba:9876::1]:49570 --> [2606:4700:4700::1001]:443 match Match using Proxy[新加坡01] 

配置如下：
```
mode: rule
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: true
log-level: debug
ipv6: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://223.5.5.5/dns-query
  fake-ip-filter:
  - dns.msftncsi.com
  - www.msftncsi.com
  - www.msftconnecttest.com
tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```
而我查看了OpenClash接管后的运行配置，相比之下，OpenClash将auto-route和auto-detect-interface改成了false，不知道是否与此有关。

也有可能与OpenClash修改的防火墙配置有关。我是按照这个教程设置防火墙的 https://qing.shuncs.com/post/tech/nft4clash ，不知道与OpenClash设置的有什么差别，将去OpenClash的issue提问。

再次感谢 @xishang0128 @HydrangeaPurple 两位大佬的帮助！祝好~

**Comment by jelly21fish** [comment]
虽然TUN模式一切正常了，但在redirect/tproxy模式下，ipv6的代理还是存在问题。

为了完全确认**不是内核导致了ipv6透明代理的问题**，我需要先让内核正常地直接运行，至少和通过OpenClash运行时一样。但目前进行了很多尝试，仍未成功。所以希望有大神能够在这个问题 https://github.com/MetaCubeX/mihomo/issues/1320 底下给予帮助！

不过，我真正想弄明白的也并非上一个问题。最终的问题还是：为什么在通过redirect/tproxy实现透明代理时，日志中没有ipv6 DNS查询的连接？ 这是由于防火墙、路由设置的缘故，还是内核设置的问题？或者，原因是**redirect/tproxy本来就无法完美代理ipv6？** 

所以，reopen是想要确认：有没有哪位大神，在自己配置的redirect/tproxy透明代理下，可以使用ipv6 DOH请求解析，并能被内核日志记录？如果可以，就说明内核对ipv6的透明代理支持没有问题。如果都不行，说明即使可以，也很难实现，可能我也没有必要试着去钻研防火墙等设置了。

很抱歉为了这点问题打扰大家，但弄不清这个问题确实特别沮丧。不论后续如何，再次感谢维护者们！

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/6f696a75-d23d-4cb9-9fd2-ca847bdd2dfb)

**Comment by jelly21fish** [comment]
@xishang0128 非常感谢您的测试！这是运行内核的设备本身发起解析时记录的连接对吧？看来只要正确配置，这类ipv6流量确实不会被漏掉，可以被正确代理。

既然内核的问题可以被排除了，我会在OpenClash的issue https://github.com/vernesong/OpenClash/issues/3919 继续寻求更完善的透明代理配置方法。再次感谢大神的帮助，感谢维护这个优秀的内核！
