### ISSUE TITLE
[Bug] 直接使用内核进行redirect/tproxy透明代理，无法直连访问网站，报错 error: reject loopback connection

### ISSUE THREAD

**Issue by jelly21fish** [MetaCubeX/mihomo#1320]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

ImmortalWrt 23.05.2

### Mihomo 版本

Mihomo Meta alpha-d96d765 linux arm64 with go1.22.4 Thu Jun 13 01:08:28 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
mode: rule
redir-port: 7892
tproxy-port: 7893
mixed-port: 7895
allow-lan: true
log-level: debug
ipv6: true
external-controller: 192.168.2.1:9090
secret: 12345
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 223.5.5.5
```

### 描述

很抱歉，我又来提问了！之前为了解决ipv6相关的问题，我尝试不用客户端，直接运行内核。我的设备是主路由，在TUN模式下，一切正常（感谢大佬们的指导）。随后我重新尝试OpenClash，发现ipv6代理使用TUN模式没有问题，使用redirect/tproxy就会出现之前反馈的问题 https://github.com/MetaCubeX/mihomo/issues/1319 。因此，ipv6部分流量没有被代理或记录的问题实际上仍没有解决。

于是，我试图在单独运行内核时，用redirect/tproxy进行透明代理，进而能排查问题。在我的理解中，OpenClash修改了防火墙的设置，使其能够更正常地进行透明代理。所以，我把OpenClash开启时的nftables设置复制下来。在使用内核时，我会先把nft设置成与OpenClash运行时一样的状态，并添加路由规则、DNS转发。

结果，内核成功运行了，但是，只有代理网站可以打开，直连网站则无法打开。使用OpenClash时，并没有出现这样的问题。关键是，防火墙等设置的状态已经与OpenClash运行时一样了。

从日志中可以看出，msedge.b.tlu.dl.delivery.mp.microsoft.com 被解析为111.51.176.20，随后eth0所在的192.168.1.2试图直连，然后报错： error: reject loopback connection to: 111.51.176.20:80 
但另一个匹配到代理规则的连接 192.168.2.216:49369 --> 199.16.156.38:443 就没有报错。
当然并不是所有直连连接都失败，面板中仍有极少数直连流量。但实际感受还是直连无法打开，代理可以。

我真的很不想再麻烦各位维护者，但检索了很久，都没有找到针对这类报错的解答。我不理解这个报错的成因：为什么同样的防火墙配置，OpenClash运行时，这个地址就不会被视为回环连接？我找到一些nft配置透明代理的博文，只有少数不是TUN模式，但我套用了他们的配置也是一样的结果。如果有大佬自己正好在OpenWrt使用mihomo进行透明代理，正好有相应的nft配置，不知可否提供一下？能提供一些思路的话也非常感谢！

我想说明，提问的主要目的并不是请求现成的配置，而是想弄明白报错的成因，希望至少能缩小一下排查的范围。这个问题确实关系到内核在非TUN模式下的表现，关系到如何排查是内核还是防火墙等因素导致的问题。我在直接用内核进行redirect/tproxy透明代理时，也测试了ipv6 DOH的解析，发现日志并未像TUN模式那样记录到这个连接，这和开头所述的OpenClash的表现一样。我想排查这个问题，就需要先让内核正常运行，因此也就需要先解决直连网站不能访问的问题。

再次抱歉打扰各位开发者，非常感谢你们的贡献！

### 重现方式

1）开启OpenClash，使用Fake-ip增强模式，在终端输入 nft list ruleset ，复制配置到 /etc/nftables.conf
2）关闭OpenClash，输入 nft flush ruleset 和 nft -f /etc/nftables.conf ，还有 ip rule add from all fwmark 0x162 lookup 100 和 ip route add local default dev lo scope host table 100 ，最后到Dnsmasq添加 127.0.0.1#7874 转发
3）按该教程安装好内核 https://qing.shuncs.com/post/tech/clashinst ，使用和客户端一样的配置，输入mihomo

### 日志

```shell
DEBU[2024-06-14T17:27:51.483868929Z] [Rule] use default rules                     
DEBU[2024-06-14T17:27:51.484413778Z] [DNS] resolve msedge.b.tlu.dl.delivery.mp.microsoft.com from udp://223.5.5.5:53 
DEBU[2024-06-14T17:27:51.484577116Z] [DNS] resolve msedge.b.tlu.dl.delivery.mp.microsoft.com from udp://223.5.5.5:53 
DEBU[2024-06-14T17:27:51.496821344Z] [DNS] msedge.b.tlu.dl.delivery.mp.microsoft.com --> [111.51.176.20] A from udp://223.5.5.5:53 
DEBU[2024-06-14T17:27:51.498497017Z] [DNS] msedge.b.tlu.dl.delivery.mp.microsoft.com --> [] AAAA from udp://223.5.5.5:53 
INFO[2024-06-14T17:27:51.499712136Z] [TCP] 192.168.2.216:49367 --> msedge.b.tlu.dl.delivery.mp.microsoft.com:80 match DomainSuffix(microsoft.com) using DIRECT 
DEBU[2024-06-14T17:27:51.499811597Z] [Rule] use default rules                     
WARN[2024-06-14T17:27:51.500475741Z] [TCP] dial DIRECT (match GeoIP/cn) 192.168.1.2:48854 --> 111.51.176.20:80 error: reject loopback connection to: 111.51.176.20:80 
DEBU[2024-06-14T17:27:53.342706014Z] [Rule] use default rules                     
INFO[2024-06-14T17:27:53.343764211Z] [TCP] 192.168.2.216:49369 --> 199.16.156.38:443 match Match using Proxy[新加坡01]
```

**Comment by xishang0128** [comment]
@jelly21fish 这应该是iptables/nftables配置错误导致的触发回环检测器的阻止,请正确配置iptables/nftables

**Comment by xishang0128** [comment]
@jelly21fish 另外,这里不负责iptables/nftables教学,如果非内核功能导致的异常,请自行解决

**Comment by jelly21fish** [comment]
@xishang0128 感谢回复！我理解这里不负责防火墙教学，我不理解的是nftables配置、mihomo配置等与OpenClash开启时相同，直接使用内核为何会出错。

**Comment by xishang0128** [comment]
@jelly21fish openclash会覆写配置,可能有些许配置不同,这应该去询问openclash

**Comment by jelly21fish** [comment]
@xishang0128 感谢您的建议。不知道大佬是否自己配置过防火墙使用透明代理？我不请求教学，但恳求在不使用TUN模式的条件下，重复上个问题 https://github.com/MetaCubeX/mihomo/issues/1319 所述的操作，看看能否记录到和TUN模式下一样的信息？如果不行，我只能推断：使用mihomo时，不适合通过redirect/tproxy实现ipv6的透明代理了。如果可以，我会试着学习配置。

**Comment by jelly21fish** [comment]
@xishang0128 大佬在这里 https://github.com/MetaCubeX/mihomo/issues/1319#issuecomment-2169258930 给出的截图说明，运行内核的设备向ipv6 DOH请求解析的流量，可以在tproxy模式下被代理。

这说明内核不存在我猜想的bug，最主要的困惑已经被解答了~ 我会在OpenClash的issue https://github.com/vernesong/OpenClash/issues/3919 继续询问透明代理的配置问题。鉴于内核项目不负责提供相关配置，我也会关闭这个issue，但希望有兴趣的朋友能在Discussions一起讨论这个问题，毕竟我看到不少人有类似的疑问。

最后，再次感谢开发者们的付出和贡献！
