### ISSUE TITLE
[Feature] 改进域名匹配

### ISSUE THREAD

**Issue by CaoKang-David** [MetaCubeX/mihomo#1321]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我设置了DOMAIN-SUFFIX,codeium.com,HongKong，但如下图所示，连接用的是codeium.com:443这种带端口的形式，没有按照要求走HongKong而走了漏网之鱼。
![image](https://github.com/MetaCubeX/mihomo/assets/19624728/1fa7cfd0-858c-4ec7-8df8-04bba7f3db10)

可否考虑在域名匹配那里改进一下，只是要域名匹配了就按规则走，忽略端口号。

**Comment by xishang0128** [comment]
@CaoKang-David 主机就是带端口的,看详情里的metadata.host

**Comment by CaoKang-David** [comment]
> @CaoKang-David 主机就是带端口的,看详情里的metadata.host

居然能秒联大佬。感谢！
附上详情
![image](https://github.com/MetaCubeX/mihomo/assets/19624728/ddaad2d1-8eed-4bda-97c5-9af84ffcd7ce)
我在rule-set 文件里面的这两行内容
![image](https://github.com/MetaCubeX/mihomo/assets/19624728/70e9976c-aa13-41dd-87da-2110185b84f3)
我重启了多次mihomo,确认它加载了这个rule-set。但它还是没有按照规则走HongKong

**Comment by xishang0128** [comment]
@CaoKang-David 看规则里的规则提供者,确保加载了规则条目以及确认顺序

**Comment by CaoKang-David** [comment]
规则提供者显示加载了43条，我核对了一下规则集文件，也确实是43条。
![image](https://github.com/MetaCubeX/mihomo/assets/19624728/eda6dc9a-f8d8-4c9a-9cf1-b7b2014e96a3)
规则顺序里面，others-direct就是我用的规则集，现在这个规则里面用的是DIRECT，但最终结果是它走到了漏网之鱼。我的规则如下图。
![image](https://github.com/MetaCubeX/mihomo/assets/19624728/9228563e-fb6e-4d28-a0cb-cf9b8d7cb00f)

**Comment by xishang0128** [comment]
@CaoKang-David https://wiki.metacubex.one/config/rule-providers/content/

**Comment by jelly21fish** [comment]
你这是classical类型的规则集，不是domain类型的。

**Comment by CaoKang-David** [comment]
> 你这是classical类型的规则集，不是domain类型的。规则集那里的behavior要修改成对应类型的。

天哪，这个一不留神就搞错了。
我想确认一下，domain类型的就是用通配符写的规则集，而classical是用诸如domain-suffix等前缀写的规则集。我这样理解对不对？

**Comment by CaoKang-David** [comment]
是我自己搞错了，不是内核的原因。

**Comment by jelly21fish** [comment]
@CaoKang-David 是的！

> @CaoKang-David https://wiki.metacubex.one/config/rule-providers/content/

看这个文档的例子就知道区别了~

**Comment by CaoKang-David** [comment]
> @CaoKang-David 是的！
> 
> > @CaoKang-David https://wiki.metacubex.one/config/rule-providers/content/
> 
> 看这个文档的例子就知道区别了~

感谢！
