### ISSUE TITLE
tun模式下，不同网段的地址无法代理？

### ISSUE THREAD

**Issue by kingvsliuzhi** [MetaCubeX/mihomo#1322]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  device: utun0

开启 tun 模式后，wirdguard网段的流量无法通过，Tcp state:syn sent。

**Comment by xishang0128** [comment]
这看起来不像一个功能请求
