### ISSUE TITLE
SSID Strategy

### ISSUE THREAD

**Issue by xihuai18** [MetaCubeX/mihomo#1330]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

功能描述 / Feature description
能不能有根据网络（比如WIFI SSID）切换部分代理选择的功能，比如一个clash proxy-group有两个选项，in-company 和 out-of-company，是两种内网代理，有了这个功能就可以自动切换这个proxy-group，做到无缝使用。

Is it possible to have a feature that switches proxy settings based on the network (e.g., WiFi SSID)? For example, a Clash proxy group could have two options, "in-company" and "out-of-company", which are two different internal proxies. With this feature, it could automatically switch between these proxy groups, allowing for seamless usage.

使用场景 / Use case
在不同的WIFI需要使用不同的代理。

Switch to different strategies according to WIFI SSIDs.

**Comment by xishang0128** [comment]
@xihuai18 这不应当是内核做的事,内核并不方便监听ssid变更

**Comment by xishang0128** [comment]
@xihuai18 如果你是直接运行内核,请自行使用shell去循环获取,然后使用api切换

如果你使用的是gui客户端,应当由客户端实现

**Comment by xihuai18** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/issues/1231#issuecomment-2175013459

GUI说应该由内核实现

**Comment by xishang0128** [comment]
反正内核做不了

**Comment by wangwei354** [comment]
一个设计草案
https://github.com/MetaCubeX/mihomo/discussions/2722
