### ISSUE TITLE
[Feature] 对CNAME记录使用代理

### ISSUE THREAD

**Issue by giveup** [MetaCubeX/mihomo#1333]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

如`api.fast.com`，尽管设置了规则`DOMAIN,api.fast.com`，但是DNS查询下返回的是CNAME记录，真正建立连接的域名是CNAME域名，导致后续连接无法通过代理进行连接。
```
; <<>> DiG 9.18.24 <<>> @127.0.0.1 -p 1154 api.fast.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29936
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.fast.com.			IN	A

;; ANSWER SECTION:
api.fast.com.		444	IN	CNAME	apiproxy-api-fast-vpc0-nlb-103017a815808492.elb.us-west-2.amazonaws.com.
apiproxy-api-fast-vpc0-nlb-103017a815808492.elb.us-west-2.amazonaws.com. 444 IN	A 54.69.47.224
apiproxy-api-fast-vpc0-nlb-103017a815808492.elb.us-west-2.amazonaws.com. 444 IN	A 44.236.74.109
apiproxy-api-fast-vpc0-nlb-103017a815808492.elb.us-west-2.amazonaws.com. 444 IN	A 35.161.104.116

;; Query time: 0 msec
;; SERVER: 127.0.0.1#1154(127.0.0.1) (UDP)
;; WHEN: Thu Jun 20 17:56:32 HKT 2024
;; MSG SIZE  rcvd: 160
```
此类域名返回的CNAME记录通常是动态变化的，无法把所有CNAME记录都添加到规则集合中。

### Possible Solution

也许应该新增一个规则语法来处理这种情况。

**Comment by xishang0128** [comment]
>> 导致后续连接无法通过代理进行连接

请证明
