### ISSUE TITLE
关于classical类型中无法使用IPCIDR

### ISSUE THREAD

**Issue by dududuK** [MetaCubeX/mihomo#134]
在classical类型中存在domain和ipcidr两种类型，单独输入列表中的域名和IP可以进行分流，但是无法对域名通过解析后与其中的Ipcidr进行匹配

**Comment by dududuK** [comment]
后来发现需要在rule中写一条带geoip的规则，后面的classical才能正常使用

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
