### ISSUE TITLE
路由规则中能否添加识别某种协议比如bittorrent

### ISSUE THREAD

**Issue by Xuchengen** [MetaCubeX/mihomo#1344]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

路由规则中能否添加识别某种协议比如bittorrent

**Comment by wy580477** [comment]
难，现在 bt 客户端都会加密流量，建议用进程规则或者只代理常用端口。
