### ISSUE TITLE
[Feature]  Hope that the classic part of the rule provider can support IP-ASN, PROCESS-NAME, AND & OR & NOT.

### ISSUE THREAD

**Issue by Energetic3906** [MetaCubeX/mihomo#1346]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

The current [classical](https://wiki.metacubex.one/config/rule-providers/content/#classical) only supports the following rules:

```yaml
payload:
- DOMAIN-SUFFIX,google.com
- DOMAIN-KEYWORD,google
- DOMAIN,ad.com
- SRC-IP-CIDR,192.168.1.201/32
- IP-CIDR,127.0.0.0/8
- GEOIP,CN
- DST-PORT,80
- SRC-PORT,7777
```

Hope to support IP-ASN, PROCESS-NAME, as well as AND, OR and NOT.

In that case, we can set up the rules like this:

```yaml
payload:
- DOMAIN-SUFFIX,google.com
- DOMAIN-KEYWORD,google
- DOMAIN,ad.com
- SRC-IP-CIDR,192.168.1.201/32
- IP-CIDR,127.0.0.0/8
- GEOIP,CN
- DST-PORT,80
- SRC-PORT,7777
- IP-ASN,13335,DIRECT
- PROCESS-NAME,chrome.exe,PROXY
- AND,((DOMAIN,baidu.com),(NETWORK,UDP)),DIRECT
```

Of course, supporting all [routing rules](https://wiki.metacubex.one/config/rules/#_1) is the best.

**Comment by xishang0128** [comment]
![Screenshot_2024-06-26-00-58-33-853_com android chrome](https://github.com/MetaCubeX/mihomo/assets/95160953/0803dcfc-7178-4689-a4b6-e2357a9327de)
I guess you didn't read the documentation carefully.

**Comment by Energetic3906** [comment]
I'm very sorry for not reading carefully. I habitually looked at the configuration file and didn't pay attention to the text above.

**Comment by Energetic3906** [comment]
> ![Screenshot_2024-06-26-00-58-33-853_com android chrome](https://private-user-images.githubusercontent.com/95160953/342830561-0803dcfc-7178-4689-a4b6-e2357a9327de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzY3OTksIm5iZiI6MTcxOTMzNjQ5OSwicGF0aCI6Ii85NTE2MDk1My8zNDI4MzA1NjEtMDgwM2RjZmMtNzE3OC00Njg5LWE0YjYtZTIzNTdhOTMyN2RlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE3MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzUzOTVmYWM0MzNiY2VjOWQ1YjBlMzlmM2I4ZDIyMzNiMjRlYjAzYmFjMzk5YmI1ODZkNTBiZDIxODVlYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.897BQUbp0Ax7rDNEJCNYQD-OZe5c5VcjJkHvAaWbZY4) I guess you didn't read the documentation carefully.

Thank you for your response, your answer solved my problem. Thanks again.
