### ISSUE TITLE
[Feature] 加入Tap模式和windivert模式 

### ISSUE THREAD

**Issue by mysteriously136** [MetaCubeX/mihomo#1347]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

某些情况在使用Tun模式的情况下会出问题，或者不能使用Tun模式，请求加入Tap模式和windivert模式。

**Comment by xishang0128** [comment]
@mysteriously136 不会加
