### ISSUE TITLE
[Bug] ubuntu-ports cannot locate latest version 1.18.5

### ISSUE THREAD

**Issue by BrandonStudio** [MetaCubeX/mihomo#1348]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Armbian 24

### Mihomo Version

1.18.2-alpha-974332c

### Configuration File

_not relative_

### Description

Cannot install latest mihomo using apt

The newest version in ubuntu-ports noble is 1.18.2-alpha-974332c.

### Reproduction Steps

```bash
apt update && apt install mihomo
```
```
mihomo is already the newest version (1.18.2-alpha-974332c).
```

### Additional Information
apt sources list:
```source
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-security main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ noble-backports main restricted universe multiverse
```

**Comment by xishang0128** [comment]
@BrandonStudio Here does not provide explanations for issues related to Ubuntu software sources.
