### ISSUE TITLE
[Bug] rule-provider文件只有一行时，解析报错

### ISSUE THREAD

**Issue by morytyann** [MetaCubeX/mihomo#1349]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

OpenWrt 23.05

### Mihomo Version

1.18.5

### Configuration File

```yaml
rule-providers:
  MyDirect:
    type: http
    url: https://example.com/MyDirect.txt
    behavior: domain
    format: text
```

### Description

如果`https://example.com/MyDirect.txt`只有一行时，启动会报错

### Reproduction Steps

1. 添加rule-provider配置，指向一个内容只有一行的文件/URL
2. 启动

### Logs

```shell
initial rule provider MyDirect error: file must have a `payload` field
```

**Comment by xishang0128** [comment]
@morytyann 只有一行就不要用ruleset了,没意义

**Comment by morytyann** [comment]
@xishang0128 那在文档里加一个ruleset必须大于一行？

**Comment by xishang0128** [comment]
@morytyann 处理了,等会用新的alpha就好了

**Comment by morytyann** [comment]
感谢
