### ISSUE TITLE
[Bug] go get version conflict

### ISSUE THREAD

**Issue by starsea** [MetaCubeX/mihomo#1350]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

win

### System Version

win

### Mihomo Version

v.1.18.5

### Configuration File

```yaml
-
```

### Description

go get  github.com/metacubex/mihomo@v1.18.5 下载下来的代码 和  https://github.com/MetaCubeX/mihomo/releases/tag/v1.18.5  这的source code 代码不一致，看起来 go get 下载下来的代码版本要落后一点？请问是什么原因

### Reproduction Steps

-

**Comment by xishang0128** [comment]
@starsea go 缓存不会更新，如果重复相同 tag 将会是老版本

**Comment by starsea** [comment]
> @starsea go 缓存不会更新，如果重复相同 tag 将会是老版本

你的意思是你们对同一个tag 发布了多次， golang proxy mod cache 只缓存了第一次的版本是吗？

**Comment by xishang0128** [comment]
@starsea 是
