### ISSUE TITLE
[Bug] clash verge1.6.6，使用v.18.5内核连接到wireguard服务时连接失败，但是使用wireguard或者使用非mate内核连接正常

### ISSUE THREAD

**Issue by youdmeng** [MetaCubeX/mihomo#1355]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [x] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [x] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

11

### Mihomo Version

v.18.5

### Configuration File

```yaml
port: 6890
socks-port: 8890
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
ipv6: true
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] } 
proxies:            
  - name: "home-windows"
    type: wireguard
    server: 1.1.1.1
    port: 8080
    ip: 10.20.20.84 #aka self ip address or address
    # ipv6: your_ipv6 #aka self ipv6 address or address
    private-key: 123=
    public-key: 123=
    preshared-key: 123=
    dns: [223.5.5.5, 119.29.29.29]  
    mtu: 1280
    udp: true           
    reserved: [219,212,139]
```

### Description

连接到wireguard服务时，持续报 context deadline exceeded

### Reproduction Steps

windows下使用clash verge1.6.6，连接到wireguard服务时连接失败，但是使用wireguard或者使用非mate内核连接正常

### Logs

```shell
2024-07-01 14:06:20 INFO - [mihomo]: time="2024-07-01T14:06:20.7205044+08:00" level=debug msg="[WG](home-windows) peer(IJKD…YyDs) - Handshake did not complete after 5 seconds, retrying (try 19)"
2024-07-01 14:06:20 INFO - [mihomo]: time="2024-07-01T14:06:20.7213085+08:00" level=debug msg="[WG](home-windows) peer(IJKD…YyDs) - Sending handshake initiation"
2024-07-01 14:06:26 INFO - [mihomo]: time="2024-07-01T14:06:26.0256033+08:00" level=debug msg="[WG](home-windows) peer(IJKD…YyDs) - Handshake did not complete after 5 seconds, retrying (try 20)"
2024-07-01 14:06:26 INFO - [mihomo]: time="2024-07-01T14:06:26.0256033+08:00" level=debug msg="[WG](home-windows) peer(IJKD…YyDs) - Sending handshake initiation"
2024-07-01 14:06:31 INFO - [mihomo]: time="2024-07-01T14:06:31.225596+08:00" level=debug msg="[WG](home-windows) peer(IJKD…YyDs) - Handshake did not complete after 20 attempts, giving up"
[TCP] dial 🏠 回家 (match IPCIDR/10.10.20.0/16) 127.0.0.1:4097 --> 10.10.20.10:80 error: context deadline exceeded
```

**Comment by xishang0128** [comment]
You are not directly running the core test, and cannot provide support

**Comment by thomasTAT** [comment]
大佬，您的WireGuard配置成功了吗？能否分享一下您的配置文件参考一下？
我的配置虽然能连上，但遇到了一些小问题，想对比看看是否有优化空间。
https://github.com/MetaCubeX/mihomo/discussions/1810

**Comment by youdmeng** [comment]
> 大佬，您的WireGuard配置成功了吗？能否分享一下您的配置文件参考一下？ 我的配置虽然能连上，但遇到了一些小问题，想对比看看是否有优化空间。 [#1810](https://github.com/MetaCubeX/mihomo/discussions/1810)

- name: "home-windows"
    type: wireguard
    server: demo.com
    port: 8866 #aka peer endpoint port
    ip: 10.20.20.84 #aka self ip address or address
    # ipv6: your_ipv6 #aka self ipv6 address or address
    private-key:xxxxx
    public-key:xxxx
    # preshared-key:xxx
    dns: [223.5.5.5, 119.29.29.29]  
    mtu: 1280
    udp: true

**Comment by thomasTAT** [comment]
和你的配置信息基本一致，但不知为何，手机 Clash/WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810


#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT
