### ISSUE TITLE
在 linux上用 请问 Dashboard有现成的吗

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#136]
https://github.com/MetaCubeX/Yacd-meta/actions
https://github.com/MetaCubeX/Razord-meta/actions

这两个里面都显示 Expired无法下载

**Comment by MetaCubeX** [comment]
@GeorgeRudd gh-page 分支

**Comment by MetaCubeX** [comment]
@GeorgeRudd 是的
