### ISSUE TITLE
[Bug]  IPV6 节点延迟异常高 

### ISSUE THREAD

**Issue by GouGoGoal** [MetaCubeX/mihomo#1375]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Win10 21H2

### Mihomo Version

1.18.6

### Configuration File

```yaml
{ name: IPV6节点, type: trojan, server: ipv6.jiedian.com, port: 8080, password: *****, udp: true, tfo: true, sni: sgp.com, skip-cert-verify: true }
```

### Description

客户端使用的Clash for Windows，在使用Clash Premium 内核时，延迟正常。当更换到mihomo 1.18.6 内核后，延迟增加了20倍，经常会超时
日志里显示
connect error: connect failed: dial tcp [2a0e:97c0:7d4:83d5:1567:****:****:****]:8080: i/o timeout

### Reproduction Steps

1

**Comment by wy580477** [comment]
直接跑裸核看看

**Comment by GouGoGoal** [comment]
用命令行内核启动的话，IPv6节点显示超时，同时ClashMetaRev里的IPv6节点延迟在5000+以上，ClashPremium 内核同一个IPv6节点延迟在500以内

**Comment by bc352562984** [comment]
这个问题确实存在的，没人关注吗？

**Comment by daitou05** [comment]
20倍有点夸张，我这边2000多点，我一直以为机场质量差，但其他机场又没有 ipv6...

**Comment by LevineWoo** [comment]
> 这个问题确实存在的，没人关注吗？

很多是用机场的，但机场几乎全是ipv4，甚至即使是自建的都很多是ipv4，用ipv6的挺少的。

**Comment by yueziji** [comment]
确实是，日志里分流已经分完了但加载比别的内核慢一节

**Comment by xishang0128** [comment]
You are not directly running the core test, and cannot provide support
