### ISSUE TITLE
[Bug] Tun Start Error: address family not supported by protocol

### ISSUE THREAD

**Issue by WoLeo-Z** [MetaCubeX/mihomo#1383]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Linux swift3 6.9.7-zen1 #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux

### Mihomo Version

```plain_text
Mihomo Meta 1.18.6 linux amd64 with go1.22.3 unknown time
Use tags: with_gvisor
```

### Configuration File

```yaml
++

# Tun mode
tun:
  enable: true  # enable 'true'
  stack: system  # or 'gvisor'
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

++
```

### Description

Stack: Neither "system" or "gvisor" is working.
Looking into the [wiki](https://wiki.metacubex.one/config/inbound/tun/), also tried options `strict-route` / `route-address` / ... Still this err

PTAL. （应该不是 NixOS 的问题，但是 Arch 系用户貌似没有反馈）
Not good at golang so can‘t pr.

附：
1. fall back to github:nixos/nixpkgs/a6857b00fe466d887d615b33dd262584a066faac （也就是 mihomo v1.18.1）问题仍然存在.

### Reproduction Steps

```zsh
nix-shell -p mihomo
mihomo -v
mihomo -d /etc/mihomo
```

### Logs

```shell
❄️ > dotfiles • 🚀 106ms • 󰘬 master
⊙ journalctl -u mihomo -o cat -e | grep TUN
time="..." level=error msg="Start TUN listening error: start NetworkUpdateMonitor: address family not supported by protocol"
```

**Comment by xishang0128** [comment]
How was it installed? By directly downloading the core binary?

**Comment by WoLeo-Z** [comment]
services.mihomo = {
    enable = true;
    package =  pkgs.mihomo;
    webui = inputs.nur-linyinfeng.packages.x86_64-linux.yacd;
    configFile = "/etc/mihomo/config.yaml";
  };

**Comment by xishang0128** [comment]
> ```nix
>   services.mihomo = {
>     enable = true;
>     package =  pkgs.mihomo;
>     webui = inputs.nur-linyinfeng.packages.x86_64-linux.yacd;
>     configFile = "/etc/mihomo/config.yaml";
>   };
> ```
> 
> Alpha 版本也尝试了（自己打包）不过还是一样 直接运行二进制没试过，稍等

尝试运行二进制,怀疑可能是nix打包造成的,项目action构建用的是go1.22.5,版本对不上

**Comment by WoLeo-Z** [comment]
好像能开启 TUN 了，不过dns好像解析不了，我的问题

**Comment by WoLeo-Z** [comment]
然后我又试了一下 /nix/store/ph9gdr11v4y6szai0093m8kqh3jqknyk-mihomo-1.18.6/bin 里的，也能正常运行，会不会因为 systemd 守护进程没写好

**Comment by WoLeo-Z** [comment]
https://github.com/NixOS/nixpkgs/blob/6794d064edc69918bb0fc0e0eda33ece324be17a/nixos/modules/services/networking/mihomo.nix#L67C11-L67C20

我看着好像也没啥问题。

`sudo /nix/store/ph9gdr11v4y6szai0093m8kqh3jqknyk-mihomo-1.18.6/bin/mihomo -d /etc/mihomo`

这个正常运行

**Comment by WoLeo-Z** [comment]
Fixed. Add `services.mihomo.tunMode = true;`
or set `RestrictAddressFamilies = "AF_INET AF_INET6 AF_NETLINK";`
Thanks a lot.
