### ISSUE TITLE
[Bug] DOMAIN规则没有生效

### ISSUE THREAD

**Issue by ZZH-Finalize** [MetaCubeX/mihomo#1384]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

win11

### Mihomo 版本

Mihomo Meta v1.18.6 windows amd64 with go1.22.4 Mon Jul  1 15:03:47 UTC 2024
Use tags: with_gvisor

### 配置文件

```yaml
rules:
  - DOMAIN, asmr.121231234.xyz, proxy
  - GEOIP, CN, DIRECT
  - MATCH, proxy
```

### 描述

`DOMAIN, asmr.121231234.xyz, proxy`这条规则没有生效, 但从webui上看到clash已经识别了这条规则, 然后访问此网站的时候依然走的是DIRECT而非proxy

```
time="2024-07-12T16:33:37.9193488+08:00" level=info msg="[UDP] 198.18.0.1:62391(spoolsv.exe) --> 192.168.100.24:161 match IPCIDR(192.168.0.0/16) using 🎯 全球直连[DIRECT]"
time="2024-07-12T16:33:38.0745432+08:00" level=info msg="[UDP] 198.18.0.1:64655(msedge.exe) --> asmr.121231234.xyz:443 doesn't match any rule using DIRECT"
time="2024-07-12T16:33:38.2188834+08:00" level=info msg="[TCP] 198.18.0.1:59471(WeChat.exe) --> 120.233.23.111:80 match GeoIP(cn) using 🎯 全球直连[DIRECT]"
```

### 重现方式

a

**Comment by xishang0128** [comment]
我已经阅读了 [文档](https://wiki.metacubex.one/)
![image](https://github.com/user-attachments/assets/55013533-8433-4c17-b1e1-5f02f792cd36)

**Comment by ZZH-Finalize** [comment]
> asmr.121231234.xyz:443 doesn't match any rule using DIRECT

LOG: asmr.121231234.xyz:443 doesn't match any rule using DIRECT

也就是说他并没有因为DOMAIN没有匹配到就走了GEOIP/DIRECT, 也没有被MATCH匹配到走proxy?

**Comment by covenant-stars** [comment]
@ZZH-Finalize DOMAIN, asmr.121231234.xyz, proxy 为什么要加空格

**Comment by ZZH-Finalize** [comment]
> @ZZH-Finalize DOMAIN, asmr.121231234.xyz, proxy 为什么要加空格

是空格的原因吗, 去掉再试试吧, 加空格只是习惯性逗号后加空格

**Comment by ZZH-Finalize** [comment]
我去, 在我的笔记本上有这个问题, 但台式机上就没有, 两边都是使用的我在github上拉下来的配置文件, 我再看下是不是我笔记本哪里的配置有问题

**Comment by covenant-stars** [comment]
那就是和这个一样 udp的回退
如果节点不支持udp,将会继续匹配 #1070

**Comment by ZZH-Finalize** [comment]
> 那就是和这个一样 udp的回退 如果节点不支持udp,将会继续匹配 #1070

谢谢, 我试一下

**Comment by ZZH-Finalize** [comment]
我去, 还真是udp问题, 我台式机上实际上是同时打开了tcp和udp两个链接, tcp的虽然识别到规则了, 但是流量还是走的DIRECT的udp, 谢谢两位的帮助
