### ISSUE TITLE
[Feature] 默认开启sing-mux

### ISSUE THREAD

**Issue by agczsz** [MetaCubeX/mihomo#1389]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

添加prefer-sing-mux字段用于默认开启sing-mux，无法开启的实现自动关闭，减少配置的修改，因为目前没有一家订阅转换支持sing-mux

### Possible Solution

把该项作为通用字段：smux:
  enabled: true
  protocol: smux
  max-connections: 4
  min-streams: 4
  max-streams: 0
  statistic: false
  only-tcp: false
  padding: true
  brutal-opts:
    enabled: true
    up: 50
    down: 100，
当sing-mux检测不通时正常连接

**Comment by xishang0128** [comment]
不会实现,sing-mux应当仅用于自建(机场等一般不会提供,会导致连接错误)

**Comment by agczsz** [comment]
> 不会实现,sing-mux应当仅用于自建(机场等一般不会提供,会导致连接错误)

只是添加附加选项，默认为关闭不就可以了
