### ISSUE TITLE
[Feature] 嗅探skip-domain能否跳过国内规则

### ISSUE THREAD

**Issue by XCJYO** [MetaCubeX/mihomo#1395]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

向日葵远程连接失败,查看日志发现
[Sniffer] Sniff tcp [192.168.11.17:2153]-->[47.96.189.124:443] success, replace domain []-->[k145932321-7c8679e8s7cbd602f.rc.sunlogin.net]
很明显,这里站点sni字段非域名，导致嗅探结果异常
然后是dns解析失败
[warning] | [TCP] dial 🌍 国内媒体 (match RuleSet/ChinaMax) 192.168.11.17:2361 --> k145932321-6a5987f1s6617dc7c.rc.sunlogin.net:443 error: dns resolve failed: couldn't find ip

解决方法 : 

skip-domain:
    '*.rc.sunlogin.net'

即可解决

问题来了,很多国内的IP连接应该是不需要进行域名嗅探的,嗅探国内的IP反而会造成很多问题,是否能够增加个功能一键跳过国内IP和域名的嗅探?

当然绕过大陆可以做到这一点,但毕竟绕过了openclash内核,会让广告过滤规则失效
而且现在meta内核,不开启绕过大陆性能依旧很高
我是r2s,fakeIP混合选择meta网络栈,千兆wifi下实测
关闭绕过大陆,国内跑到900左右
开启绕过大陆,也是900左右

参考:[openclash向日葵问题](https://github.com/vernesong/OpenClash/issues/3229#issue-1679819890)

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/sniff/#override-destination

**Comment by XCJYO** [comment]
> https://wiki.metacubex.one/config/sniff/#override-destination
> 
> 不会考虑支持集合/特定出站不嗅探,嗅探是入站完成的

懂了,多谢

**Comment by zx09** [comment]
大佬我问一下 我openwrt的openclash也是连不上向日葵 我想问问：
skip-domain:
'*.rc.sunlogin.net'
这两行代码加在哪里
