### ISSUE TITLE
[Feature] Support for Xray's KCP(mKCP)

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#1399]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Xray's KCP(mKCP) has unique obfuscations and it's performance is good
Could you please add it to Mihomo?

**Comment by wwqgtxx** [comment]
never

**Comment by Mars160** [comment]
Hysteria or Hysteria2 might be a better choice than KCP and mKCP
