### ISSUE TITLE
[Feature] 有考虑把vless子协议增加xtls-rprx-vision-udp443选项嘛

### ISSUE THREAD

**Issue by AquaSimulacra** [MetaCubeX/mihomo#1404]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望为vless子协议添加xtls-rprx-vision-udp443。目前仅支持xtls-rprx-vision。

**Comment by xishang0128** [comment]
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

呃呃

**Comment by AquaSimulacra** [comment]
不好意思，眼瞎
