### ISSUE TITLE
[Feature] proxy-providers 增加是否使用代理更新的选项

### ISSUE THREAD

**Issue by ZhaoGY-N** [MetaCubeX/mihomo#1418]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

proxy-providers 的配置中，能否增加一个是否使用代理更新的选项？

**Comment by xishang0128** [comment]
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 


https://wiki.metacubex.one/config/proxy-providers/#proxy

**Comment by ZhaoGY-N** [comment]
抱歉，是我看的不仔细了
