### ISSUE TITLE
[Bug] 在alpine Linux下无法运行

### ISSUE THREAD

**Issue by 2314933036** [MetaCubeX/mihomo#1425]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [ ] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Linux

### 系统版本

alpine-standard-3.20.2-x86_64

### Mihomo 版本

![image](https://github.com/user-attachments/assets/cc2fdb83-0cfa-47a0-9e69-d0444259ad35)
这些全部

### 配置文件

```yaml
无
```

### 描述

![image](https://github.com/user-attachments/assets/786ae840-66b7-4d96-b4fc-8d2c0b7551a0)

### 重现方式

直接启动

**Comment by 2314933036** [comment]
补充，加上启动参数也不行
![image](https://github.com/user-attachments/assets/f7837c74-793d-4bab-b9c9-742bf9ab4ed0)

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/faq/faq/#_2

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)

**Comment by 2314933036** [comment]
> https://wiki.metacubex.one/faq/faq/#_2
> 
> * [x]  我已经阅读了 [文档](https://wiki.metacubex.one/)

https://github.com/clash-verge-rev/clash-verge-rev/issues/180
看了这个issue我把所有可能的版本都下了
