### ISSUE TITLE
[Bug] 死循环请求单个节点 (当开启 mobile hotspot热点) 

### ISSUE THREAD

**Issue by lovitus** [MetaCubeX/mihomo#1429]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

10 22H2

### Mihomo Version

latest    1.18.7

### Configuration File

```yaml
tun, 服务模式, 系统代理 , 三个都开了.

和配置文件的节点规则等应该无关
```

### Description

当win10开启 移动热点以后, 会死循环请求某个随机节点,
截图的 8866为一个节点, 实际是只要开热点,就会爆刷类似的日志,但是节点不是固定的.
![image](https://github.com/user-attachments/assets/388db1fd-a98c-4c76-a2a3-4a50607a718e)

### Reproduction Steps

![image](https://github.com/user-attachments/assets/2909f470-b794-4457-b192-18d0fa1a0976)

![image](https://github.com/user-attachments/assets/eba607dd-4399-4929-b0da-0296c7f53826)

**Comment by xishang0128** [comment]
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.

**Comment by xishang0128** [comment]
另外 https://zhuanlan.zhihu.com/p/669487791
