### ISSUE TITLE
[Feature] HTTPUpgrade 支持 0-rtt  配置

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/mihomo#1431]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

请问目前是否支持 HTTPUpgrade 0-rtt 配置

[HTTPUpgrade 0-RTT #3152 ](https://github.com/XTLS/Xray-core/pull/3152)

> 现在在 HTTPUpgrade path 后加上 `?ed=2560` 才会启用 **0-RTT**
>
> WebSocket 0-RTT 的实现原理是 Base64 编码后放入 **header**

**Comment by wwqgtxx** [comment]
https://wiki.metacubex.one/config/proxies/transport/#ws-optsv2ray-http-upgrade-fast-open

**Comment by wwqgtxx** [comment]
是的
