### ISSUE TITLE
[Feature] rule-set可以不用通配符吗

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/mihomo#1439]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

发现ruleset如果是qq.com,只会对qq.com这一个域名生效，想要规则有效必须用通配符+.qq.com。

这个搞主要问题是带通配符后与gfwiist的格式不同，有些用到gfwlist不认通配符

**Comment by xishang0128** [comment]
不可以不用
