### ISSUE TITLE
[Feature] 请求添加 classical behavior 的 mrs format 支持

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#1442]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前mihomo已经支持了`domain/ipcidr behavior`的`mrs format`支持，可以将`yaml/text format`文件转换为`mrs format`，大幅缩小了规则集的占用空间，体验非常良好。

由于`domain behavior`的规则集缺少了一部分的`DOMAIN-KEYWORD`，`DOMAIN-REGEX`规则，是否考虑添加将`classical behavior`的`yaml/text format`文件转换为`mrs format`的功能？

**Comment by xishang0128** [comment]
没法优化数据结构,降低储存也降不了多少,老实用text/yaml

**Comment by callzhang** [comment]
请问mrs的格式解析和生成的代码逻辑在哪里？
