### ISSUE TITLE
关于dns

### ISSUE THREAD

**Issue by Meow7575** [MetaCubeX/mihomo#1443]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望'fake-ip-filter'可以像'nameserver-policy'一样支持规则集

**Comment by wwqgtxx** [comment]
done: https://github.com/MetaCubeX/mihomo/commit/11afb31303a86d5d60ed0a1f2f3ef759e57f2bd9

**Comment by Lovefish** [comment]
> done: [696b75e](https://github.com/MetaCubeX/mihomo/commit/696b75ee375660bb8478ca94fe2f16b8ad2ff3c3) support `ruleset:` and `geosite:` in `fake-ip-filter`

这个版本什么时候更新？
