### ISSUE TITLE
[Bug] 匹配走代理的规则还会用国内 nameserver 解析，并 cache 被污染的 IP

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/mihomo#1446]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

openwrt

### Mihomo Version

Mihomo Meta alpha-gc17d7c0 linux arm64 with go1.22.6 Mon Aug 12 20:13:26 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
  default-nameserver:
    - 123.125.81.6
    - 223.5.5.5

  nameserver:
    - https://123.125.81.6/dns-query
    - 'https://223.5.5.5/dns-query#h3=true'

  fallback:
    - 'tcp://8.8.8.8#PROXY'
    - 'https://1.1.1.1/dns-query#PROXY&h3=true'
```

### Description

文档提到如果匹配到 **代理规则** 会使用远程服务端进行 DNS 解析，并直接走代理。

日志显示还是会用国内的 NS 解析域名，并 cache 污染的地址：

https://wiki.metacubex.one/config/dns/diagram/

![图片](https://github.com/user-attachments/assets/5d68f202-68ec-423f-b652-6542cecbaff7)

``` php
msg="[TCP] 192.168.6.203:53154 --> lh3.googleusercontent.com:443 match RuleSet(www) using PROXY[tuic-jp]"
msg="[TCP] 192.168.6.203:53155 --> lh3.googleusercontent.com:443 match RuleSet(www) using PROXY[tuic-jp]"
msg="[DNS] lh3.googleusercontent.com --> 142.251.43.1"
msg="[DNS] lh3.googleusercontent.com --> 142.251.43.1"
msg="[DNS] lh3.googleusercontent.com --> [142.251.43.1] A from https://223.5.5.5:443/dns-query"
msg="[DNS] resolve lh3.googleusercontent.com A from https://223.5.5.5:443/dns-query"
msg="[DNS] resolve lh3.googleusercontent.com A from https://123.125.81.6:443/dns-query"
msg="[Rule] use default rules"
msg="[Rule] use default rules"
msg="[DNS] ogs.google.com --> [142.251.43.14] A from https://223.5.5.5:443/dns-query"
msg="[TCP] 192.168.6.203:53153 --> ogs.google.com:443 match RuleSet(www) using PROXY[tuic-jp]" <-- 命中代理规则
msg="[DNS] resolve ogs.google.com A from https://123.125.81.6:443/dns-query"
msg="[DNS] resolve ogs.google.com A from https://223.5.5.5:443/dns-query"
msg="[DNS] ogs.google.com --> 142.251.43.14"
msg="[DNS] cache hit ogs.google.com --> [142.251.43.14] A, expire at 2024-08-14 16:49:39"
msg="[Rule] use default rules"
```

### Reproduction Steps

描述

**Comment by xishang0128** [comment]
本地查询与代理无关

**Comment by xishang0128** [comment]
> @xishang0128 `ogs.google.com` 域名命中的是 **走代理 PROXY[tuic-jp]** 规则，但是还是会用 nameserver 来解析，按文档描述，是不应该再用 nameserver 解析了，直接走代理了

本地请求只会用于直连/匹配,能理解?

代理发送的是域名,域名在节点解析

**Comment by xishang0128** [comment]
@lvii redirect/tproxy等也仅限ip传入,如果需要本地不解析,请使用socks/http并且不配置ip规则

**Comment by Vegas7** [comment]
> @lvii redirect/tproxy等也仅限ip传入,如果需要本地不解析,请使用socks/http并且不配置ip规则

原来是这样。
那么现阶段来说，软路由上类clash代理工具基本都基于这些方式，也就是无论规则如何设置，所有域名始终都会在内核解析？
不知道是否有工具可以避免此情况？

**Comment by xiaoziguys** [comment]
可以用nameserver-policy来制定国外dns了
