### ISSUE TITLE
[Bug] windows版本中纯ipv6的hy2类型节点无法连接

### ISSUE THREAD

**Issue by qq565425677** [MetaCubeX/mihomo#1449]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11 

### Mihomo Version

Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:48:59 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
- ip-version: ipv6
  name: hysteria2
  password: user:password
  port: 443
  server: hstr.com
  type: hysteria2
```

### Description

在windows中使用clash verge rev发现纯ipv6的hy2类型节点无法连接。

尝试过把port改成ports，server改成ip，去掉ip-version，都没用。

也在release页面下载了最新稳定版的mihomo-windows-amd64-go121-v1.18.7.zip，使用.\mihomo-windows-amd64-go121.exe -f config.yaml之后，在metacubexd中点击check仍无法显示出延迟信息。

然而在macos，和linux中该节点都可以正常使用。

### Reproduction Steps

直接运行内核并在metacubexd对纯ipv6的hy2类型节点check没有显示
在clash verge rev中则显示error

**Comment by qq565425677** [comment]
另外补充一下，其他协议如trojan和ss，纯ipv6的节点是可以正常连接的

**Comment by qq565425677** [comment]
看过[#1149](https://github.com/MetaCubeX/mihomo/issues/1149)和https://github.com/clash-verge-rev/clash-verge-rev/issues/798#issue-2215593498，里面的方法均无效

**Comment by qq565425677** [comment]
刚才试了下1.18.6和1.18.3的版本，这两个是正常的

**Comment by qq565425677** [comment]
又测了下，1.18.6直接运行内核没问题，在clash verge rev中还是显示error，1.18.3二者均运行正常...

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/68a4e15e-0e5c-4978-9a1d-577478d356fa)
![image](https://github.com/user-attachments/assets/05cd90a5-28f1-45d5-ab34-0f79f69c8100)
![image](https://github.com/user-attachments/assets/8ea3307b-12be-4985-bdac-bea7b4fd78d3)

测试无问题

**Comment by qq565425677** [comment]
应该是最新版本有问题，我这里试了v1.18.7的[mihomo-windows-amd64-v1.18.7.zip](https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-windows-amd64-v1.18.7.zip)和Prerelease-Alpha的[mihomo-windows-amd64-go122-alpha-4c10d42.zip](https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64-go122-alpha-4c10d42.zip)，测试下来无法连接，老版本没有问题。
您的版本不知道是哪一版，不过应该不是最新的alpha-4c10d42

**Comment by qq565425677** [comment]
但是我是直接运行.\mihomo-windows-amd64.exe -f config.yaml之后，在metacubexd中点击check检测的，上条回复中的两个版本没反应，更早的1.18.3就没问题....您要不用我提到的两个版本再试试？是release中最前面的两个版本

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/9a310dab-2ef8-4431-ad8e-b8f159efb2e2)
无问题,请确保不是本地环境的问题,如果无法提供确切证据证明是内核的问题,该issues将被关闭

**Comment by qq565425677** [comment]
我服了，但是好奇怪呀，如果是本地环境问题，不应该出现高版本失败低版本成功的现象吧？我再研究研究，感谢您的回答，以及抱歉耽误您的时间了@xishang0128
