### ISSUE TITLE
[REQUEST] Add support WS path format

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/mihomo#145]
Add support Websocket format like `path: ws://domain.com/path` is possible?
If yes, please add to new feature

**Comment by rexname** [comment]
Gass kan lah oprek dewek

**Comment by llycoris** [comment]
Nunggu suhu pr 😁

**Comment by stealth-sr** [comment]
> Gass kan lah oprek dewek

yahahaha close source

**Comment by rexname** [comment]
> > Gass kan lah oprek dewek
> 
> yahahaha close source

Ho'oh bang suhunya ghak mau nurunin

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
