### ISSUE TITLE
[feature wanted] SNI嗅探仅用于分流

### ISSUE THREAD

**Issue by saeziae** [MetaCubeX/mihomo#147]
sniffing 开启后，会在代理协议中使用域名传递目标主机。
希望能够仅将读出来的域名用于分流，目标 host  仍使用 IP。

**Comment by XhL6996** [comment]
支持，之前因为这个被坑了一波。事情是这样的，我有个域名最开始解析到A主机，后来解析到B主机。但是clash会把A主机的IP还原成域名走代理，代理再解析实际上访问的是B主机。我当时是连SSH，明明输入的是A的IP，登录之后却是B主机。重启clash之后才解决。
