### ISSUE TITLE
[Bug] 无法正确路由IPv6: 2408:824*:511*:2030::1/60这样的ipv6地址

### ISSUE THREAD

**Issue by liumingan** [MetaCubeX/mihomo#1474]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

OpenWrt SNAPSHOT 

### Mihomo Version

alpha-6e04e1e9

### Configuration File

```yaml
空
```

### Description

对于2408:824*:511*:203*::1这样的/60或者
/64ipv6地址，无法正确路由

### Reproduction Steps

在openwrt上和安卓客户端均做过测试，如果不使用插件或者使用插件并打开绕过国内ip，该类/60或者/64的地址都可以正常ssh连接；如果打开插件，让所有流量都经过核心，该类地址都不能连接，openwrt下y提示time out，安卓下的ssh客户端提示，找不到路由

**Comment by xianren78** [comment]
![QQ截图20240828102032](https://github.com/user-attachments/assets/5e407c34-897d-4800-adc9-534d1b379ebb)

**Comment by liumingan** [comment]
win下经过核心
![image](https://github.com/user-attachments/assets/17bf126c-3b49-4cad-8bd7-9b59efe12c5f)

**Comment by liumingan** [comment]
安卓在安装了openwrt插件下：
![image](https://github.com/user-attachments/assets/cb53d9fb-3ff3-4922-8167-cdd73a50c363)
安卓在4g网络下运行插件：
![image](https://github.com/user-attachments/assets/e5aecc14-0540-4816-9d9c-8a5e1d58b970)

**Comment by liumingan** [comment]
使用的是域名，经验证，域名解析正常，获取的ip正确

**Comment by liumingan** [comment]
提供测试地址：myhome20.dynv6.net

**Comment by morytyann** [comment]
@liumingan 之前他来插件群问了，我发现他DDNS的IP是lan的，改成wan的就完全正常，不知道为什么他还要提这个Issue

**Comment by liumingan** [comment]
因为不过核心就正常

**Comment by xishang0128** [comment]
请提供最简可复现配置以及debug日志

**Comment by liumingan** [comment]
配置文件如下：

ymixed-port: 7890
socks-port: 7891 # SOCKS5 代理端口
redir-port: 7893 # 透明代理端口，用于 Linux 和 MacOS
tproxy-port: 7892
allow-lan: true
bind-address: "*" # 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址
authentication: # http,socks 入口的验证用户名，密码
  - "Clash:aK12&345g678"
skip-auth-prefixes: # 设置跳过验证的 IP 段
  - 127.0.0.1/8
  - ::1/128
lan-allowed-ips: # 允许连接的 IP 地址段，仅作用于 allow-lan 为 true, 默认值为 0.0.0.0/0 和::/0
  - 0.0.0.0/0
  - ::/0
# lan-disallowed-ips: # 禁止连接的 IP 地址段，黑名单优先级高于白名单，默认值为空

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: off # strict # off
log-level: silent # 日志等级 silent/error/warning/info/debug
ipv6: true # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
external-controller: 0.0.0.0:9090
# 配置 WEB UI 目录，使用 http://{{external-controller}}/ui 访问
external-ui: ui
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
# 在RESTful API端口上开启DOH服务器！！！该URL不会验证secret， 如果开启请自行保证安全问题 ！！！
# external-doh-server: /dns-query
# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
global-client-fingerprint: random # "chrome","firefox","safari","ios","random","none"
#  TCP keep alive interval
keep-alive-interval: 600
unified-delay: true # 统一延迟
tcp-concurrent: false # false TCP并发
# interface-name: en0 #出站接口
# routing-mark: 6666
hosts:
  cn.bing.com: bing.com
#自定义 geodata url
geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
geo-auto-update: false # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
profile: # 存储 select 选择记录
  store-selected: true
  # 持久化 fake-ip
  store-fake-ip: false # true
tun:
  enable: false
  stack: mixed # gvisor/mixed/system
  dns-hijack:
    - any:53
    - tcp://any:53 # 需要劫持的 DNS
  auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
  device: tun
  mtu: 9000 # 最大传输单元
  gso: true # 启用通用分段卸载，仅支持 Linux
  gso-max-size: 65536 # 通用分段卸载包的最大大小
  auto-redirect: true # false # 自动配置 iptables 以重定向 TCP 连接。仅支持 Linux。带有 auto-redirect 的 auto-route 现在可以在路由器上按预期工作，无需干预。
  # strict-route: true # 将所有连接路由到 tun 来防止泄漏，但你的设备将无法其他设备被访问
  endpoint-independent-nat: false
sniffer:
  enable: false #false or true
  force-dns-mapping: false # true
  parse-pure-ip: true # false # true
  override-destination: true
  sniff: {HTTP: {ports: [80, 8080-8880]}, TLS: {ports: [443, 8443]}, QUIC: {ports: [443, 8443]}}
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
    - '+.apple.com'
dns:
  cache-algorithm: arc
  enable: true
  enhanced-mode: redir-host # redir-host or fake-ip
  prefer-h3: true # 是否开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:1053 # 开启 DNS 服务器监听
  use-hosts: true
  ipv6: true
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.*'
  default-nameserver:
    - 114.114.114.114
    - 119.29.29.29
  # 配置后面的nameserver、fallback和nameserver-policy向dns服务器的连接过程是否遵守遵守rules规则
  # 如果为false（默认值）则这三部分的dns服务器在未特别指定的情况下会直连
  # 如果为true，将会按照rules的规则匹配链接方式（走代理或直连），如果有特别指定则任然以指定值为准
  # 仅当proxy-server-nameserver非空时可以开启此选项, 强烈不建议和prefer-h3一起使用
  # 此外，这三者配置中的dns服务器如果出现域名会采用default-nameserver配置项解析，也请确保正确配置default-nameserver
  respect-rules: false # false  true
  nameserver:
    - 'tls://8.8.4.4'
    - 'tls://one.one.one.one'
    - 'quic://dns.adguard.com:784'
  nameserver-policy:
    'geosite:baidu': '114.114.114.114'
    'geosite:alibaba': '223.5.5.5'
    'geosite:tencent': '119.29.29.29'
    "geosite:category-ads-all": rcode://success
    'geosite:cn,private,category-games@cn':
      - '218.106.127.114'
      - '218.104.111.114'
    #  - 'https://223.6.6.6/dns-query'
    'geosite:geolocation-!cn,google,gfw,youtube,pixiv,bing,twitter,openai':
      - 'tls://1.0.0.1#DNS'
      - '1dot1dot1dot1.cloudflare-dns.com'
      - 'https://dns.google/dns-query#DNS'
      - 'tls://208.67.222.222#DNS'
      - 'https://cloudflare-dns.com/dns-query#DNS'
      - 'https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true'
  proxy-server-nameserver: # 专用于节点域名解析的 DNS 服务器
    - '1.1.1.1'
    - '114.114.115.115'
#    - 'https://doh.pub/dns-query'
ntp:
  enable: true
  write-to-system: false # true
  server: cn.ntp.org.cn
  port: 123
  interval: 600
proxies:
  - {"name": 
proxy-providers:
 

rules:
  # 常见广告域名屏蔽
  - DOMAIN-KEYWORD,admarvel,REJECT
  - DOMAIN-KEYWORD,admaster,REJECT
  # 自定义规则
  - DOMAIN-SUFFIX,dyndns.com,DIRECT
  - DOMAIN-SUFFIX,dynv6.net,DIRECT
  - DOMAIN-SUFFIX,dynv6.com,DIRECT
  - DOMAIN-SUFFIX,GitLab.com,DIRECT
  - DOMAIN-SUFFIX,cloudflare.com,DIRECT
  - DOMAIN-SUFFIX,ip.flares.cloud,DIRECT
  - DOMAIN-SUFFIX,cloudns.net,PROXY
  # GEOSITE规则
  - GEOSITE,private,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,bing,PROXY
  - AND,((NETWORK,UDP),(DST-PORT,443),(GEOSITE,youtube)),REJECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,biliintl,PROXY
  - GEOSITE,openai,OpenAI
  - GEOSITE,gfw,PROXY
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  #GEOIP规则
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,Telegram,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - DST-PORT,80/8080/443/8443,PROXY,no-resolve
  - MATCH,Other,no-resolve

**Comment by liumingan** [comment]
[warning] | [TCP] dial DIRECT (match DomainSuffix/dynv6.net) [2408:824e:5116:2030:c91a:4832:d854:d8df]:50630 --> myhome20.dynv6.net:22 error: connect failed: dial tcp [2408:824e:5307:96c0::1]:22: i/o timeout

**Comment by xishang0128** [comment]
@liumingan 请提供"最简可复现配置"而不是一大堆对于debug无用的配置

**Comment by liumingan** [comment]
> 请提供最简可复现以及配置调试日志
我的配置已经贴出来了
大侠可以用自己的配置ssh连接一下myhome20.dynv6.net,很容易就复现了，看看是不是不通过核心可以连接，通过核心就无法连接

**Comment by liumingan** [comment]
> @liumingan 请提供"最简可复现配置"而不是一大堆对于debug无用的配置

最简配置就是不用任何配置，直接用自己的配置去连接，看是不是通过核心了就不可以连接，不通过核心就可以连接

**Comment by xishang0128** [comment]
> > @liumingan 请提供"最简可复现配置"而不是一大堆对于debug无用的配置
> 
> 最简配置就是不用任何配置，直接用自己的配置去连接，看是不是通过核心了就不可以连接，不通过核心就可以连接

![image](https://github.com/user-attachments/assets/f42985cf-064a-4107-a46a-e74ca93d5c48)
![image](https://github.com/user-attachments/assets/6bc89427-8c08-4f56-a158-cadbfa461a19)

**Comment by xishang0128** [comment]
盲猜内核绑定wan接口导致无法连接lan,自行分流到lan

**Comment by liumingan** [comment]
> 盲猜内核绑定wan接口导致无法连接lan,自行分流到lan
绑定到lan？？？要连接的是远程ssh，不是本地的，分流到lan，那还可以连接上外网？流程是这样：
本地路由器ssh→远程路由器（myhome20.dynv6.net)   ,不开插件→可通； 开插件不过内核→可通；开插件过内核→不通

**Comment by xishang0128** [comment]
不知道,没法复现,没救,另外你说了插件,这不是直接运行内核造成的问题,内核不负责解决
