### ISSUE TITLE
[bug] tun 模式开启 IPv6 的情况下未代理 IPv6

### ISSUE THREAD

**Issue by loveqianool** [MetaCubeX/mihomo#148]
我在安卓使用 [ClashM](https://github.com/adiprasetya/ClashM) 连接
因为我的服务端 IPv4 不通，需要使用 IPv6 连接，而未开启 IPv6 会连接不上 IPv6 的服务端。
但是开启 IPv6 发现它只代理了 IPv4，所有 IPv6 都会直连。

**Comment by yang05051** [comment]
我也发现了这样的问题

**Comment by yang05051** [comment]
探索了一下，这种问题会发生在在Merge里面定义了DNS的情况下，关闭Merge可以避免这个问题
猜测是DNS设置不当的问题，我并不清楚是为什么 😂
