### ISSUE TITLE
[Bug] external-ui report 404  and   yacd web  report CROS,  how  i  can  use  web ui???  i need  help!!!

### ISSUE THREAD

**Issue by CoderCore** [MetaCubeX/mihomo#1484]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### System Version

Docker Container

### Mihomo Version

Mihomo Meta v1.18.7

### Configuration File

```yaml
*******
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
*******

or

*******
external-controller: 0.0.0.0:9090
secret: ""
external-ui: /root/.config/ui
*******
```

### Description

404

### Reproduction Steps

I use  mihomo docker on routeros container.
I try to use yacd web or  metacubex  web UI,but both get error!
![2](https://github.com/user-attachments/assets/097399af-9ab9-43fb-b287-684b0313da06)
![3](https://github.com/user-attachments/assets/2c13be2c-df4d-4d7a-8906-2564d19e7cf2)
I try to use external-ui: /root/.config/ui  , but  get 404 error 
![1](https://github.com/user-attachments/assets/7dd7d405-1683-4a50-a809-4a14ac6c0622)
![4](https://github.com/user-attachments/assets/c37e813a-cdfd-4e69-a765-6be2e90df2c8)

I just want to use web ui  to manage, who can help me? I need help!!!

**Comment by xishang0128** [comment]
Please run the core test directly and provide the log

**Comment by CoderCore** [comment]
> Please run the core test directly and provide the log
I try  to run it on debian container, run ok!
Maybe  docker's image problem..
The image i use   is   izumiko/mihomo:latest....


The issue  can be closed...
