### ISSUE TITLE
[Bug] 使用clash核心连接clash dashboard时只能显示概览与连接 随后显示Unauthorized

### ISSUE THREAD

**Issue by GYF0814** [MetaCubeX/mihomo#1498]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Windows

### System Version

Windows 11 23H2

### Mihomo Version

v1.18.8

### Configuration File

```yaml
mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:4503
secret: e819ad02-4d54-4dd5-8032-19c4a51ac1ca
ipv6: false
```

### Description

当config.yaml中secret为空时，连接clash web时一切正常 但当config.yaml中secret不为空时，连接clash dashboard（地址与secret均正确时）只能显示概览和连接栏，其余栏均无法显示，且在一段时间后（很快）显示Unauthorized
![图片](https://github.com/user-attachments/assets/5cab67bb-5b65-4b90-b44d-fbe1fa708e56)
使用任意clash dashboard均能复现

### Reproduction Steps

在config.yaml中存在secret且不为空 连接任意clash dashboard（如https://yacd.haishan.me）即可复现

**Comment by xishang0128** [comment]
认证过不去当然Unauthorized,自行填写secret

**Comment by GYF0814** [comment]
> 认证过不去当然Unauthorized,自行填写secret

地址与secret均正确时。。。

**Comment by xishang0128** [comment]
> > 认证过不去当然Unauthorized,自行填写secret
> 
> 地址与secret均正确时。。。

使用curl请求并贴出输出
