### ISSUE TITLE
[Feature] DNS ECS support

### ISSUE THREAD

**Issue by huber1234** [MetaCubeX/mihomo#1501]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

I hope to add a parameter after the DNS module nameserver to support ECS, Maybe like this

  nameserver:
  - https://8.8.8.8/dns-query#proxy&ecs=1.1.1.1
  
. Cooperate with the proxy to remotely resolve all  domain names, so that the problem of DNS leakage can be better avoided.

**Comment by wwqgtxx** [comment]
done https://github.com/MetaCubeX/mihomo/commit/914e93429b4999d55b1f98afc411e4b72b57d8c8

**Comment by Magic989** [comment]
好像只有谷歌的 ECS 体验还可以，不过就这个也够了
```
# 深圳网段(120.76.0.0/14) 杭州网段(223.4.0.0/14) 成都网段(47.108.0.0/15) 上海网段(47.100.0.0/14) 青岛网段(47.104.0.0/15) 北京网段(101.200.0.0/15)
      - 'https://dns.google/dns-query#Proxy&ecs=120.76.0.0/14&ecs-override=true'
```

**Comment by huber1234** [comment]
> 好像只有谷歌的 ECS 体验还可以，不过就这个也够了
> 
> ```
> # 深圳网段(120.76.0.0/14) 杭州网段(223.4.0.0/14) 成都网段(47.108.0.0/15) 上海网段(47.100.0.0/14) 青岛网段(47.104.0.0/15) 北京网段(101.200.0.0/15)
>       - 'https://dns.google/dns-query#Proxy&ecs=120.76.0.0/14&ecs-override=true'
> ```

yeah, I test it like this, it works very well

**Comment by AngelontheRoad** [comment]
我想问下，这里的`proxy`是`proxy-groups`中的某个`name`吗？因为我看文档里说`优先使用已有代理，如果不存在该名称的代理则指定接口连接`。
