### ISSUE TITLE
[Bug] cmfa从2.10.2开始，节点用不了

### ISSUE THREAD

**Issue by kkyf09** [MetaCubeX/mihomo#1510]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [X] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Android

### System Version

鸿蒙4.2.0

### Mihomo Version

cmfa 2.10.2

### Configuration File

```yaml
1
```

### Description

节点是sing-box服务端，部署在freebsd14上，节点类型有vmess，hy2，tuic等，从cmfa2.10.2开始，节点就连不上，2.10.2以下的版本连接使用正常，手机操作系统为鸿蒙4.2.0

### Reproduction Steps

同上：
手机系统：鸿蒙4.2.0
cmfa：2.10.2以上包含2.10.2
服务端：freebsd14部署sing-box

**Comment by xishang0128** [comment]
https://github.com/MetaCubeX/mihomo/issues/1049

**Comment by kkyf09** [comment]
> #1049

这个问题我猜测是内核更新引起的，因为基于mihomo新内核的flclash也有这个问题

**Comment by xishang0128** [comment]
> > #1049
> 
> 这个问题我猜测是内核更新引起的，因为基于mihomo新内核的flclash也有这个问题

请确保运行内核也有该问题,否则不要报告给内核仓库

**Comment by kkyf09** [comment]
> > > #1049
> > 
> > 
> > 这个问题我猜测是内核更新引起的，因为基于mihomo新内核的flclash也有这个问题
> 
> 请确保直接运行内核也有该问题,否则不要报告给内核仓库

请问下windows跑裸核有教程吗
