### ISSUE TITLE
[Bug] cannot turn off `auto-route` when using tun interface

### ISSUE THREAD

**Issue by Hyffer** [MetaCubeX/mihomo#1513]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [ ] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

Ubuntu 24.04.1 LTS x86_64

### Mihomo Version

Mihomo Meta alpha-e33d4a4 linux amd64 with go1.23.1 Thu Sep 12 03:21:27 UTC 2024
Use tags: with_gvisor

### Configuration File

```yaml
mixed-port: 7890
external-controller: 127.0.0.1:9090
tun:
  enable: true
  auto-route: false
  auto-redirect: false
```

### Description

tun device named Meta is created as expected, but route table also get modified which should not happen according to user manual.

### Reproduction Steps

launch mihomo with the above config file

### Logs

```shell
mihomo log:
INFO[2024-09-15T20:36:18.238302817+08:00] Start initial configuration in progress
INFO[2024-09-15T20:36:18.238447008+08:00] Geodata Loader mode: memconservative
INFO[2024-09-15T20:36:18.238475639+08:00] Geosite Matcher implementation: succinct
INFO[2024-09-15T20:36:18.23870989+08:00] Initial configuration complete, total time: 0ms
INFO[2024-09-15T20:36:18.238969652+08:00] RESTful API listening at: 127.0.0.1:9090
INFO[2024-09-15T20:36:18.250724916+08:00] Sniffer is closed
INFO[2024-09-15T20:36:18.250835542+08:00] Mixed(http+socks) proxy listening at: 127.0.0.1:7890
WARN[2024-09-15T20:36:18.251135019+08:00] [TUN] default interface changed by monitor,  => wlp0s20f3
INFO[2024-09-15T20:36:18.253933679+08:00] [TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: false, auto redir: false, ip stack: gVisor
INFO[2024-09-15T20:36:18.255982843+08:00] Start initial Compatible provider default

tun interface:
15: Meta: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 198.18.0.1/30 brd 198.18.0.3 scope global Meta
       valid_lft forever preferred_lft forever
    inet6 fdfe:dcba:9876::1/126 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::98d0:131e:3017:60c9/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

part of route table:
default dev Meta table 2022 metric 1024 pref medium
```

**Comment by Hyffer** [comment]
oops.
And yes, problem also exists for ipv4.

It has been a while since then. So is this an expected behavior now? If so, is there a workaround to get it turned off?

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/e430f924-0790-4144-abef-9b1ac1034cf7)
![image](https://github.com/user-attachments/assets/718c68e4-d386-4b34-93f9-aa36613e1c39)
In my environment, I cannot reproduce the issue. Is this problem reproducible only on Ubuntu?

**Comment by Hyffer** [comment]
@xishang0128 what is your linux distro? that is astonishing.

**Comment by xishang0128** [comment]
> @xishang0128 what is your linux distro? that is astonishing.

Arch Linux

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/65eaab28-8931-4025-9565-a47628e835c7)
![image](https://github.com/user-attachments/assets/c123fda1-2ff8-40f4-8762-0fb0d5f71931)
Testing with the Ubuntu 24.04.1 ISO showed no issues.

**Comment by Hyffer** [comment]
thanks very much!

I am switching to mihomo from the very old clach. There's a lot changed and my config is broken.

At the very beginning I saw `default dev Meta table 2022 metric 1024 pref medium` in route table (as posted above) I was misdirected that route table got touched. But route table 2022 actually is not uesd by any rule. It was actually DNS resolution being messed up so i cannot connect to internet. Thanks again for helping and I might take more time to fix the config and spin it up XD
