### ISSUE TITLE
[Feature] 304 ETag support for both proxy provider and rules provider

### ISSUE THREAD

**Issue by SukkaW** [MetaCubeX/mihomo#1529]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

As a popular Surge / Mihomo / sing-box rules maintainer, my domain, `ruleset.skk.moe`, receives about 6.9 million requests, and consumes about 180 GiB of CDN bandwidth per month.

<img width="973" alt="image" src="https://github.com/user-attachments/assets/687ef202-bf33-4c56-a9c6-3272dc02d180">

<img width="972" alt="image" src="https://github.com/user-attachments/assets/bd0552a1-078e-48f6-9940-93a0a361eaa0">

Adding 304 + `If-None-Match` support for unchanged providers (both rules provider and proxy providers) would be beneficial for both rule maintainers and users.

### Possible Solution

`ruleset.skk.moe`, `cdn.jsdelivr.net`, and `raw.githubusercontent.com` (and its reverse proxy) all return the `ETag` response header, which can be used for HTTP 304 negotiation.

Mihomo already implements a cache of sorts (for Fake IPs). It is possible to add a new KV (with the specified path or the hash as the key, and the ETag as the value) to the existing cache. When updating providers, include the request header `If-None-Match` with the stored ETag value (if there is any). If a 304 status code is returned by the remote, skip the update.

**Comment by xishang0128** [comment]
done
https://github.com/MetaCubeX/mihomo/commit/047177bd18e2a19e7b9d6f16f7bc3928778aecc3

**Comment by wwqgtxx** [comment]
finish in:
https://github.com/MetaCubeX/mihomo/commit/5d242510c8caf8ecbe41ee6e68d3b692a29bb50b
https://github.com/MetaCubeX/mihomo/commit/b7cb6774bf4d07bfb0bd23d8070447573f3386ef
