### ISSUE TITLE
[Feature] 关于 DNS 的 respect-rule

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#1535]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我原本以为这个功能是会按请求的域名分流，
试了一下结果并不是，
那我没理解错的话这是按 DNS 服务器地址的分流对吧？

我配置里目前是把所有分流规则都套到 rule-set 里
然后把所有分流规则 在 dns nameserverpolicy 那里重新写一遍
还是希望能添加按目标域名分流DNS的功能
配置就能精简很多

**Comment by HozumiMoa** [comment]
nameserver-policy 就是按域名分流吧，支持 geosite 和 rule-set

**Comment by wwqgtxx** [comment]
简单来说，rules里面的规则不仅仅匹配域名，也匹配进程名、端口号等等，而且域名还有可能是sniff嗅探得到的，但DNS模块却拿不到这么多的元数据，所以直接生搬硬套会产生很多很困惑的情况（比如出现了rules根据端口号匹配到某个proxy出站，但是nameserver-policy却匹配到另一个dns server去了）

respect-rule只是让dns服务器本身的链接（即1.1.1.1/223.5.5.5这些链接）遵循rules出站，而不是想原版clash那样粗暴的直连

让你在nameserver-policy中重写一遍分流规则就是要让你清楚明白你自己在做什么（即只能匹配域名规则）
