### ISSUE TITLE
[Feature] 支持以 URL 做配置文件参数启动

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#1536]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

比如:
Mihomo.exe -d \ -f "http:\192.168.1.222\Profile\Default.yaml"

**Comment by wwqgtxx** [comment]
请自行通过curl或则wget解决

**Comment by Brbrbr1995** [comment]
@wwqgtxx 
我也试过
这样每次更新配置都要重启后端很麻烦
核心直接支持的话直接在面板 reload config 就好

**Comment by wwqgtxx** [comment]
实际上直接远程加载完整配置文件非常不安全，你应该使用proxy/rule providers替代，而不是反复重载完整配置

**Comment by Brbrbr1995** [comment]
已经在用了节点和规则都在provider里，
都是在局域网里多设备共享的，
就是windows不能用 URL， 要手动更新

**Comment by wwqgtxx** [comment]
@Brbrbr1995 什么叫windows不能使用url？

**Comment by Brbrbr1995** [comment]
这样:
Mihomo.exe -d \ -f "http:\192.168.1.222\Profile\Default.yaml"

**Comment by wwqgtxx** [comment]
那和windows有什么关系

**Comment by Brbrbr1995** [comment]
希望能像直接这样启动
别的设备都能用url订阅
windows web面板在浏览器里不能吧

**Comment by wwqgtxx** [comment]
你真的这么想要url订阅请使用第三方GUI客户端，反正内核不会支持该功能

**Comment by Brbrbr1995** [comment]
😥
