### ISSUE TITLE
[Feature] 新手有点不太理解这句话的意思

### ISSUE THREAD

**Issue by fyhong** [MetaCubeX/mihomo#1548]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

[https://wiki.metacubex.one/config/proxy-providers/content/#uri](url)
这里说 YAML/uri/base64不可写在同一文件,uri/base64不需要proxies:字段,直接书写即可
这到底是什么意思？ 我这样写，直接是报错的。有没有哪位大老给个详细一点的配置教一下
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxy-providers:
  ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss1
  ss://YWVzLTI1Ni1nY206bWV0YUAxMjcuMC4wLjE6NDQz#ss2

**Comment by xiandu999-yu** [comment]
![image](https://github.com/user-attachments/assets/18c33dd0-4d8a-46e9-bc86-76e0c9ab3a22)
是写在这个对应文件里的...

**Comment by xishang0128** [comment]
issues不是给你问问题的,去discussions
