### ISSUE TITLE
[Feature] can't initial GeoIP: can't download MMDB: context deadline exceeded

### ISSUE THREAD

**Issue by lihongzy** [MetaCubeX/mihomo#1560]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在Ubuntu中使用mihomo内核配置代理的时候can't initial GeoIP: can't download MMDB: context deadline exceeded 求解

**Comment by Landau1994** [comment]
you can manually download it, and run again
