### ISSUE TITLE
[Feature] 支持 mieru 代理协议

### ISSUE THREAD

**Issue by enfein** [MetaCubeX/mihomo#1563]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我是 [mieru](https://github.com/enfein/mieru) 代理软件的作者 enfein。

mieru 用户如果需要使用路由规则等高级功能，需要将 mieru 客户端连接到 v2ray / clash / sing-box 的 socks5 出站。

在 ClashMeta 内核中直接支持 mieru 代理协议，有几点好处：

1. 减少运行两个应用程序的额外开销，降低网络延迟。
2. 为 mieru 带来 TUN 等高级功能。
3. 丰富第三方支持 mieru 代理的图形界面应用和安卓程序。

### Possible Solution

我将在 mieru 中提供一个集成的 API 库，并且在 ClashMeta 中实现对 mieru 协议的适配。

**Comment by snakem982** [comment]
这个好啊，在ClashMeta中实现 [adper](https://github.com/MetaCubeX/mihomo/tree/Alpha/adapter) 接口貌似就可以了
期待大佬的实现，提出pull request
