### ISSUE TITLE
[Bug] exclude-filter节点过滤使用正则表达式产生一个问题

### ISSUE THREAD

**Issue by rsgdn** [MetaCubeX/mihomo#1564]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

Linux

### System Version

ImmortalWrt 23.05.2

### Mihomo Version

alpha-fc9d5cf

### Configuration File

```yaml
exclude-filter: "(?i)(?<!\.)[2-9]{1}[0-9]?\.?[0-9]?[x×]|(?<!\.)[1]{1}[0-9]?\.?[6-9]?[x×]"
```

### Description

预期通过配置文件中代理合集里exclude-filter使用正则表达式排除满足关键字节点，但是启动报错发现未知转义符，我之前在subconverter使用是没问题

### Reproduction Steps

无

### Logs

```shell
time="2024-10-03T21:22:26.276236638+08:00" level=fatal msg="Parse config error: yaml: line 11: found unknown escape character"
```

**Comment by xishang0128** [comment]
转义需使用\\而不是\
