### ISSUE TITLE
[Bug] direct节点的tfo为True时,无法联网

### ISSUE THREAD

**Issue by dycwuxing** [MetaCubeX/mihomo#1568]
### Verify steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and understand the meaning of all configuration items I have written, avoiding a large number of seemingly useful options or default values.
- [ ] I have not reviewed the [documentation](https://wiki.metacubex.one/) and resolve this issue.
- [X] I have not searched the [Issue Tracker](……/)  for the problem I am going to raise.
- [X] I have tested with the latest Alpha branch version, and the issue still persists.
- [X] I have provided server and client configuration files and processes that can reproduce the issue locally, rather than a desensitized complex client configuration file.
- [X] I have provided the simplest configuration that can reproduce the error I reported, rather than relying on remote servers, TUN, graphical client interfaces, or other closed-source software.
- [X] I have provided complete configuration files and logs, rather than providing only parts that I believe are useful due to confidence in my own intelligence.

### Operating System

MacOS, Windows

### System Version

MacOS13 Win11

### Mihomo Version

alpha-c63a851

### Configuration File

```yaml
以下节点配置,TUN下无法正常访问国内网络
proxies:
- {"name":"直连","type":"direct","ip-version":"ipv4-prefer","udp":true,"tfo":true,"mptcp":true}
```

### Description

在TUN模式下,如果"tfo":true,提示"invalid argument",没有返回fakeip是因为filter添加了黑名单
proxies:
- {"name":"直连","type":"direct","ip-version":"ipv4-prefer","udp":true,"tfo":true,"mptcp":true}
level=debug msg="[DNS] cache hit www.baidu.com --> [110.242.68.3 110.242.68.4] A, expire at 2024-10-05 17:02:17"
level=debug msg="[DNS] cache hit www.baidu.com --> [2408:871a:2100:2:0:ff:b09f:237 2408:871a:2100:3:0:ff:b025:348d] AAAA, expire at 2024-10-05 17:02:43"
level=warning msg="[TCP] dial 🎯全球直连 (match RuleSet/ChinaMax_Domain) [fdfe:dcba:9876::1]:62509(Microsoft Edge Helper) --> www.baidu.com:443 error: dial tcp 110.242.68.4:443: invalid argument"

在TUN模式下,如果"tfo":false,正常访问
proxies:
- {"name":"直连","type":"direct","ip-version":"ipv4-prefer","udp":true,"tfo":false,"mptcp":true}
level=debug msg="[DNS] cache hit www.baidu.com --> [2408:871a:2100:3:0:ff:b025:348d 2408:871a:2100:2:0:ff:b09f:237] AAAA, expire at 2024-10-05 17:49:21"
level=debug msg="[DNS] resolve www.baidu.com A from https://180.184.2.2:443/dns-query"
level=debug msg="[DNS] resolve www.baidu.com A from https://223.6.6.6:443/dns-query"
level=debug msg="[DNS] resolve www.baidu.com AAAA from https://180.184.2.2:443/dns-query"
level=debug msg="[DNS] resolve www.baidu.com AAAA from https://223.6.6.6:443/dns-query"
level=info msg="[TCP] 28.0.0.1:57516(Microsoft Edge Helper) --> www.baidu.com:443 match RuleSet(ChinaMax_Domain) using 🎯全球直连[直连]"

### Reproduction Steps

当direct节点配置tfo:true时

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/da7091f2-ed9d-4dc8-8d52-cdb4b6e9ae16)
![image](https://github.com/user-attachments/assets/2b72e511-0a04-4cbe-b3a7-42e7483b95a1)
![image](https://github.com/user-attachments/assets/6d7f9495-5eca-433a-bcfc-52955b9d2c06)
测试无问题,请确保你的环境支持tfo
