### ISSUE TITLE
[Bug] 为什么空IP会匹配 NOT((!(GeoIP,cn)))这个规则

### ISSUE THREAD

**Issue by LittleRey** [MetaCubeX/mihomo#1578]
### Verify steps

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我未仔细看过 [文档](https://wiki.metacubex.one/) 并解决问题
- [X] 我未在 [Issue Tracker](……/) 中寻找过我要提出的问题
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器、TUN、图形界面客户端或者其他闭源软件。
- [X] 我提供了完整的配置文件与日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。

### 操作系统

Windows

### 系统版本

Windows 10 x64

### Mihomo 版本

v1.18.9

### 配置文件

```yaml
rules:

 - NOT,((GEOIP,CN)),国外流量
 - MATCH,国内流量
```

### 描述

nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools error: couldn't find ip"
nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools:443 match NOT((!(GeoIP,cn))) using 国外流量[[Trojan] 🇯🇵 日本06

为什么明明是空IP,会匹配match NOT((!(GeoIP,cn)))这个规则

### 重现方式

设置规则为

 - NOT,((GEOIP,CN)),国外流量
 - MATCH,国内流量 
 
 访问nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools即可复现

### 日志

```shell
time="2024-10-09T21:16:27.5860691+08:00" level=debug msg="[DNS] cache hit nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools --> [] A, expire at 2024-10-09 22:16:25"
time="2024-10-09T21:16:27.5860691+08:00" level=debug msg="[DNS] cache hit nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools --> [] AAAA, expire at 2024-10-09 22:16:25"
time="2024-10-09T21:16:27.5860691+08:00" level=debug msg="[DNS] resolve nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools error: couldn't find ip"

time="2024-10-09T21:16:27.7106416+08:00" level=info msg="[TCP] 127.0.0.1:60231(chrome.exe) --> nwo28qntlui.nxdomain-watch-29447051.go-unsigned-ipv4.dnscheck.tools:443 match NOT((!(GeoIP,cn))) using 国外流量[[Trojan] 🇯🇵 日本06丨25倍计费丨✈️Ⅱ]"
```

**Comment by xishang0128** [comment]
预期行为,任意非geoip cn都能匹配not((geoip,cn))

**Comment by laggardkernel** [comment]
感觉这不是很对，NXDOMAIN 含义是域名不存在没有解析，表示网站不存在。可以在规则里匹配 NXDOMAIN 并拒绝吗，不知道该怎么处理这种情况。

**Comment by laggardkernel** [comment]
表达的不是很清晰，我想问的是如何在规则中匹配 NXDOMAIN，并 block 掉连接。

这里的问题是 NXDOMAIN 是 DNS 一种响应，没有 IP 返回。clash/mihomo IP 规则不知道怎么匹配这种情况，现在匹配不到会回落到 MATCH，如果 MATCH 走代理，会把 HTTP 请求转发给代理。

> The DNS protocol [[RFC1035](https://datatracker.ietf.org/doc/html/rfc1035)] defines response code 3 as "Name Error",
   or "NXDOMAIN" [[RFC2308](https://datatracker.ietf.org/doc/html/rfc2308)], which means that the queried domain name
   does not exist in the DNS.

**Comment by laggardkernel** [comment]
> 你应该是想要解析失败直接通过 match 的一个 feature。

@Skyxim 是的，DNS 的 NXDOMAIN 响应意思不是解析失败，而是经解析对应域名不存在（没有对应 IP）。比如用户错拼了网址，在非 Fake-IP 模式下，浏览器会处理这个 DNS 响应，提示用户。例如这里的 [Chrome NXDOMAIN 提示页面](https://www.google.com/search?&q=chrome+nxdomain&udm=2)。

在使用 Fake-IP 模式下，由于浏览器拿到 IP 先建立 HTTP 连接，不会提示用户。我想应该由 clash 处理，而现有 IP, DOMAIN 规则也匹配不了这种情况，最终只能被 MATCH 捕获，继续处理 HTTP 请求。

**Comment by laggardkernel** [comment]
> 可能在客服端存在无效域名，但是在服务器端存在。

正常 DNS  解析成功的状态码是 0 NOERROR。你说的情况更像是对应 DNS 影响码中的 SERVFAIL（处理请求失败）, REFUSED（拒绝请求）。而 NXDOMAIN 意思并不是服务器不知道结果。意义应该是不同的。
