### ISSUE TITLE
会不会考虑为代理组做新的自动策略

### ISSUE THREAD

**Issue by justdoiting** [MetaCubeX/mihomo#158]
目前已经有url-test，fallback，load-balance，只能说这些策略对于使用自建节点或者高端机场的用户来说是如虎添翼，但对于使用垃圾多机场或者白嫖节点池或是用那种月抛鸡建的公益机场来说，这3个策略并没有理想的效果。简单来说，如果节点质量差，就目前使用测延迟的策略来说，体验不好甚至有点本末倒置。

所以我在想会不会有一种新的策略来改善这种问题

下面就是我的想法，新策略我定义为“preferred”，即优选。和上次的上天功能差不多，仍是先对代理组内的节点进行url延迟测试，然后取延迟最低的3个节点进行下载速度测试，下载测速方式是用这个节点去下载一个5MB的文件，关于全球节点公平的文件这点，我觉得GitHub可以一试，链接（https://raw.githubusercontent.com/BitDoctor/speed-test-file/master/5mb.txt），3x5x86400/600=2160，这么一看可能会觉得一天会花掉很多流量，但是这个策略是为多个机场准备的，假设这个用户有3个机场，按我见过的最垃圾的机场来算，一个机场只有2个节点，那总共6个节点，2160/6=360，这是比较极端的了。加上lazy，只要这个节点在用，那么就不测，这样一天下来，一个机场所用于测速的流量将≤360，如果用节点池的话，完全没有流量这方面的担忧，那些公益机场，一个月也有50GB的流量，50×1024/360≈142(天)，一个50G的机场就能测142天。

这里是我设想的配置写法：
- name: "preferred-auto"
    type: preferred         #通过httping URL，测出节点的延迟值
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    # lazy: true
    # disable-udp: true
    # filter: 'HK' 

还有就是延迟与下载速度的权重和选择节点的问题：延迟方面我是这样想的，0-50→1  50-100→0.95  100-150→0.90 50ms的推进，0.05分的推进，速度方面则是，0-5mbps→0.05  5-10mbps→0.10  10-15mbps→0.15  5mbps的推进，0.05分的推进

例：
节点1    524ms，24.80Mbps  0.5x0.25=0.125
节点2   901ms，19.02Mbps    0.1x0.2=0.02
节点3   740ms，24.29Mbps   0.3x0.25=0.075

节点1的得分最高，所以选节点1
preferred一轮后，自动选择节点1，这个策略不说可以100%选择最优的节点，70%还是有的

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
