### ISSUE TITLE
[BUG] 负载均衡失败 5 次不会更换节点

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#160]
通过观察日志得出，如果出现以下错误，失败 5 次后不会更换节点：

1. connect error: EOF
2. error: context deadline exceeded
3. 待观察

**Comment by Skyxim** [comment]
@sowahaha 预期情况，负载均衡 不太适用，后面可能会改掉切换逻辑

**Comment by eightsheep67** [comment]
url test 怎么配置能优化

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
