### ISSUE TITLE
[Feature] 代理集筛选会区分大小写不方便

### ISSUE THREAD

**Issue by xgitl** [MetaCubeX/mihomo#1601]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述
代理集筛选会区分大小写不方便
比如使用排除关键字碰到字母会区分大小写，^((?!期|WANG|订|官).)*$，wang这样的小写不会被排除

**Comment by xishang0128** [comment]
自行学习正则表达式
