### ISSUE TITLE
[Bug] Abnormal network speed in TUN mode / TUN模式下网速异常

### ISSUE THREAD

**Issue by infrost** [MetaCubeX/mihomo#1606]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我仔细看过 [文档](https://wiki.metacubex.one/) 并未解决问题
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的问题，并且没有找到
- [X] 我是中文用户，而非其他语言用户
- [X] 我已经使用最新的 Alpha 分支版本测试过，问题依旧存在
- [X] 我提供了可以在本地重现该问题的服务器、客户端配置文件与流程，而不是一个脱敏的复杂客户端配置文件。
- [X] 我提供了可用于重现我报告的错误的最简配置，而不是依赖远程服务器或者堆砌大量对于复现无用的配置等。
- [X] 我提供了完整的日志，而不是出于对自身智力的自信而仅提供了部分认为有用的部分。
- [X] 我直接使用 Mihomo 命令行程序重现了错误，而不是使用其他工具或脚本。

### 操作系统

Windows

### 系统版本

Windows 11 23H2%24H2

### Mihomo 版本

``` bash
Mihomo Meta v1.18.9 windows amd64 with go1.23.1 Sun Sep 29 09:46:42 UTC 2024
Use tags: with_gvisor
```

> 此外，当前alpha版本的内核也有该问题
> Additionally, the current alpha version of mihomo also has this issue

### 配置文件

```yaml
不需要配置文件，默认配置下随便使用一组代理均出现该问题
No configuration file is needed, the problem occurs when using any set of proxies in the default configuration.
```

## 写在最前
这个是一个很奇怪的问题，不确定是否每一台电脑都可以复现，且并不能在程序`Debug Level`的日志中看出问题来。
目前的情况是我手中在用的笔记本可以稳定复现该问题，但是运行几乎相同的后台程序的另一台笔记本（同样的系统版本）则似乎无此问题，我会继续关注。

- **能够确定是mihomo内核的问题**，这是因为使用各版本的下游UI（包括web控制器）开启mihomo内核的服务模式后启用`TUN`，问题均会出现，而使用`系统代理`模式则不会。
- 初步排除系统问题和硬件问题/网络驱动问题，同一硬件启动另一硬盘上的系统不会有问题，但是启用`mihomo-TUN`后则出现该问题，系统网络驱动原出厂版本和最新版本都试了。

### **已知开启`TUN`模式后，经过一段时间，网速会严重下降。**

理论上程序不会接管本地流量，但是观察到局域网传输（包括ftp, smb等服务）速度同样出现下降的情况
具体为：
- 如果使用有线网络，原速度为100MB/s，速度下降至30MB/s
- 如果使用无线网络，原速度为70-80MB/s，速度下降至7-9MB/s
- 下两张图分别为正常无线速度和问题出发后的无线速度对比
![Screenshot 2024-08-26 120006](https://github.com/user-attachments/assets/def7b7b9-fad1-417f-ab43-ade9e9d9f13f)
![Screenshot 2024-08-22 183120](https://github.com/user-attachments/assets/d5b8aaae-cf5e-4174-91c8-2b9bd1675338)

- 下降后的速度可能会在一个范围内明显抖动
   尤其是内网，该问题较为明显，下图为有线（理论连接速度1Gbps）的掉速情况
![Screenshot 2024-08-26 032821](https://github.com/user-attachments/assets/8b5e2226-4a12-4fcb-9e53-c1b49729efad)

- **无论是否走代理，无论内外网，降速问题均存在**
   下图是外网明显降速的情况（排除硬盘/CPU瓶颈）
![Screenshot 2024-08-23 003126](https://github.com/user-attachments/assets/efc67d5f-21e3-4c40-be33-d4bf193b8616)

- 如果网络本身较慢（如本身就低于10MB/s），则该问题不明显，难以察觉。

> 观察到问题不会立即出现，但是网络质量/节点质量差/切换WIFI似乎会加快问题出现的速度
> 可能您注意到以上图片下载的并不是同一个文件，这是尽量避免系统缓存对测试造成的干扰。

## 恢复正常的办法
- 注销当前用户重新登录
- 注意，问题出现后在Windows的`服务`里终止`mihomo`的进程并不能让网络恢复，执行`sudo netsh winsock reset`也是没有作用的。

## 触发方式
- 特定的电脑
- `mihomo`内核以服务模式运行后，开启`TUN`模式接管所有流量

### 日志

```shell
程序看起来并没有抛出异常，`Debug-level`都是正常的代理获取/切换/URL访问等内容。
跟此前提到的一样，理论上程序不会接管的本地流量也出现降速，让我想不明白原因。
该问题已经困扰我很久，如果需要提供更详细的信息，请联系我。
```

**Comment by xishang0128** [comment]
@infrost 如果

## 触发方式 
- 特定的电脑 

那么,这就是PC的问题而不是mihomo的问题,请提供通用的可复现方式
