### ISSUE TITLE
[Feature] Expanding InUser or adding InAuthUser in metadata

### ISSUE THREAD

**Issue by xzycn** [MetaCubeX/mihomo#1624]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [ ] 我是中文用户，而非其他语言用户

### 描述

Hi, we see there has a InUser in metadata struct，but sometimes we need know what's password in incoming connection not only username.

Can we get a authuser like below from metadata,thanks.
```go
type AuthUser struct {
	User string
	Pass string
}
```

**Comment by xzycn** [comment]
@xishang0128 
Hi, what's the problem here?

**Comment by xishang0128** [comment]
@xzycn 使用了中文模板
