### ISSUE TITLE
[Feature] 建议修改lan-allowed-ips默认值为常见局域网ip地址

### ISSUE THREAD

**Issue by Mars160** [MetaCubeX/mihomo#1640]
### Verification Steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [X] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [X] I am a non-Chinese user.

### Description

ipv4:
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16

ipv6:
fc00::/7

防止不懂的小白开放被扫到后被滥用

**Comment by Mars160** [comment]
@gg4924 
我这种半吊子就是:-(

**Comment by gg4924** [comment]
> @gg4924 我这种半吊子就是:-(

那你也是愿意学习的人啊，现在已经知道怎么配置了吧。像你一样愿意学习的人应该都会看文档进行配置，自然就会了解这些，不愿意了解这些的人就直接用别人的工具好了。

**Comment by Mars160** [comment]
@gg4924 有道理，同时谢谢你的认可
