### ISSUE TITLE
[Feature] 代理集合proxy-providers:增加复写多路复用等更多内容

### ISSUE THREAD

**Issue by SatenRuiko-Lv0** [MetaCubeX/mihomo#1648]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

https://wiki.metacubex.one/config/proxy-providers/
文档中override:不支持覆写类似host，cipher:zero等内容，请求增加更多可覆写的内容。
比如
override: {
  host:xxx
  cipher: zero,
  smux: {
     enabled: true
     protocol: smux
     max-connections: 16
     min-streams: 4
     statistic: false
     only-tcp: true
     padding: true
     }
}

**Comment by xishang0128** [comment]
@SatenRuiko-Lv0 host等不属于通用配置,smux需要服务端支持,支持的一般都会直接写有,所以不会支持

**Comment by SatenRuiko-Lv0** [comment]
> @SatenRuiko-Lv0 host等不属于通用配置,smux需要服务端支持,支持的一般都会直接写有,所以不会支持

好的明白了，感谢解答
