### ISSUE TITLE
[Feature] 最近的更新不能用tun网卡当dns了吗

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/mihomo#1653]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

之前一直用198.18.0.1当dns服务器，挺方便的，现在dns指向他没响应了

这么好的特性怎么就没了呢

**Comment by psqtdhx** [comment]
fakeIP，不是还在吗？

**Comment by Bitcion** [comment]
> fakeIP，不是还在吗？

单纯tun模式下的虚拟网卡

**Comment by xishang0128** [comment]
tun的dns监听是fakeip-range地址+1,如198.18.0.2
