### ISSUE TITLE
添加DNS缓存功能

### ISSUE THREAD

**Issue by SnowCore8** [MetaCubeX/mihomo#1659]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

建议添加dns缓存功能，
目前我在使用normal模式
希望能在本地缓存dns的解析结果二次利用这样能减少访问会话数，
希望能优化aarch64核心的tun接口占用问题
关闭之后无法再次开启需要重启核心才行

**Comment by xishang0128** [comment]
默认缓存

**Comment by SnowCore8** [comment]
> 默认缓存

但是这个文件是缓存到哪里呢？我并没有发现cache.db的大小在增加 我尝试过解析大量域名没有发现缓存到哪个文件

**Comment by SnowCore8** [comment]
> > 但是这个文件是缓存到哪里呢？我并没有发现cache.db的大小在增加 我尝试过解析大量域名没有发现缓存到哪个文件
> 
> 域名解析应该是缓存到内存里了，cache.db的内容是持久保存的，而域名解析不存这里

其实我的想法是 将缓存保存到cache.db 然后第二次启动就将缓存读取到内存中 可能是考虑到小内存设备吧
