### ISSUE TITLE
[Feature] 建议新增默认出站

### ISSUE THREAD

**Issue by SixGodSGD** [MetaCubeX/mihomo#1665]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

可以在代理出站中选择默认选择某一个出站。并且我还希望加入，当出站没有节点时，能够自行选择是direct还是reject

**Comment by covenant-stars** [comment]
@SixGodSGD 默认是第一个策略组的第一个节点  可以在策略组中添加一个direct的节点 没获取到节点的时候默认就是direct
而且灵活应用pass规则可以完全实现你想要的功能
