### ISSUE TITLE
DNS缓存到本地

### ISSUE THREAD

**Issue by SnowCore8** [MetaCubeX/mihomo#1680]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

建议添加dns缓存保存到本地并在二次启动加载入内存的功能，
目前我在使用normal模式
希望能在本地缓存dns的解析结果二次利用这样能减少访问会话数，

**Comment by xishang0128** [comment]
无意义,缓存遵守ttl,存本地过一会也会过期
