### ISSUE TITLE
[Feature] 希望可以将 mitm 功能合并到主分支

### ISSUE THREAD

**Issue by Luoxin** [MetaCubeX/mihomo#1700]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

mitm 特性分支已经两年多未更新了，但是这个功能本身还是十分有用的，希望可以更新一下该分支并且合并到主分支

**Comment by xaotag** [comment]
有什么新功能
