### ISSUE TITLE
[Feature] 使用代理更新 geosite 数据

### ISSUE THREAD

**Issue by RebelliousWhiz** [MetaCubeX/mihomo#1709]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

mihomo 社区的各位好。

经查询，目前 geosite 应该是通过直连下载数据，不支持内核发起请求通过 proxy 下载。

目前 rule-set 可以通过指定 proxy 进行下载。是否可以考虑配置将 geoip 也通过 proxy 下载？

这样可以避开下载地址被 gfw 问题，只要代理可以通，就能通过 proxy 连接 github 下载。

**Comment by MDZZ-123** [comment]
开TUN模式应该可以代理

**Comment by RebelliousWhiz** [comment]
开 TUN 模式对路由器性能并不是特别友好，所以并没有尝试...

**Comment by xiandu999-yu** [comment]
![image](https://github.com/user-attachments/assets/87f317d0-a856-4fc9-b848-93903ca5a6ba)
不是可以自定义下载地址吗？
![image](https://github.com/user-attachments/assets/7de65499-5e9d-4b35-93ae-1f0c5c9378cb)
![image](https://github.com/user-attachments/assets/a0378da2-bf3c-48b6-b605-7a5b02e3962b)
而且好像规则也管的啊？

**Comment by RebelliousWhiz** [comment]
有可能是 OpenWrt-mihomo 的逻辑，如本地无 GeoIP 相关文件，会直连获取。实测该问题影响不大，我改了 Config 也没有调用 Geosite，问题关闭。
