### ISSUE TITLE
[Feature] 能更新一下subconverter的fork吗，从yaml文件转换nodes会缺少vless节点

### ISSUE THREAD

**Issue by yiqifengba** [MetaCubeX/mihomo#1710]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

目前只可以将vless节点转换成yaml配置文件，但是将yaml配置文件转换节点会缺少vless节点

**Comment by yiqifengba** [comment]
subconverter还有就是谷歌翻译直连的规则还没删除，在rules\DivineEngine\Surge\Ruleset\Unbreak.list

**Comment by xishang0128** [comment]
无关内核
