### ISSUE TITLE
[Feature] nameserver-policy 支持 rule-set

### ISSUE THREAD

**Issue by qasd93991** [MetaCubeX/mihomo#1712]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

现在 nameserver-policy 只支持 geosite，希望可以支持 rule-set

**Comment by letianle** [comment]
这个可以给出一个示例吗

**Comment by wwqgtxx** [comment]
23年就支持的功能跑这来发什么issue
