### ISSUE TITLE
[Feature] dialer-proxy 能否支持 proxy groups

### ISSUE THREAD

**Issue by miaojior** [MetaCubeX/mihomo#1717]
### Verification Steps

- [X] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [X] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [ ] I am a non-Chinese user.

### Description

让一个proxy group支持 dialer-proxy  列如下面的配置
- name: group1
    type: select
    use:
      - Overseasv6
      - Overseasv4
    dialer-proxy: dialer
    
  - name: dialer
    type: select
    use:
      - Overseasv6
      - Overseasv4

对客户端机器来说第一层代理往往是固定的 而落地代理需要选择 这样可以无需一一配置 并且如果proxys来自于远程代理也可创建dialer

**Comment by E021ntox** [comment]
@wwqgtxx @xishang0128 请再次考虑，一个proxy-group和另一个proxy-group组成代理链，这个是非常重要的基础功能
