### ISSUE TITLE
[Feature] 为tun添加exclude-process选项

### ISSUE THREAD

**Issue by lonble** [MetaCubeX/mihomo#1719]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

目前可以通过一些选项跳过tun路由，比如`exclude-uid`。
希望能添加`exclude-process`，通过进程匹配跳过路由，这样有两点好处：
1. 提高某些程序的网络性能，比如BT下载（顺便也能防止BT的大量连接污染日志）、游戏
2. 让网络工具可以正常使用，比如ping、dig

**Comment by Jerry4159** [comment]
我也有这样的需求，我不清楚现在是否已经有方法，至少我的搜索带我来到了这个issue...

**Comment by xishang0128** [comment]
做不到,iproute2没法识别process
