### ISSUE TITLE
[Feature] 设置了direct-nameserver直连域名为什么还走nameserver？

### ISSUE THREAD

**Issue by 7461151** [MetaCubeX/mihomo#1732]
### Verification Steps

- [ ] I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
- [ ] I have searched for the feature request I want to propose in the [Issue Tracker](……/) and did not find it
- [ ] I am a non-Chinese user.

### Description

设置了direct-nameserver直连域名为什么还走nameserver？

**Comment by cutbuzz** [comment]
> ### Verification Steps
> * [ ]  I have read the [documentation](https://wiki.metacubex.one/) and confirmed that this feature is not implemented
> * [ ]  I have searched for the feature request I want to propose in the [Issue Tracker](%E2%80%A6%E2%80%A6/) and did not find it
> * [ ]  I am a non-Chinese user.
> 
> ### Description
> 设置了direct-nameserver直连域名为什么还走nameserver？

请问找到原因了吗？我目前也遇到这个问题....
