### ISSUE TITLE
[Feature] powerpc32/64位架构支持

### ISSUE THREAD

**Issue by lijiext** [MetaCubeX/mihomo#1734]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

手头上有powerpc 32位架构的上古防火墙设备Sophos RED 15，请求内核支持或增加编译说明文档

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/552bebec-5be3-4293-8eb3-9672887f06dc" />

**Comment by xishang0128** [comment]
@lijiext golang不支持ppc 32位
