### ISSUE TITLE
[Feature] 关于代理节点排序问题。

### ISSUE THREAD

**Issue by Review977** [MetaCubeX/mihomo#1735]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

使用include-all引入多个机场订阅后，会把节点安装名称强制排序，能否把这一参数加一个可选项呢？使节点可以安装机场给定的默认排序去呈现。

**Comment by xishang0128** [comment]
不能,需要特定排序请自行手动引入

**Comment by ilovelxy** [comment]
> ### 验证步骤
> 
>     * [x]  我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
> 
>     * [x]  我已在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中寻找过我要提出的功能请求，并且没有找到
> 
>     * [x]  我是中文用户，而非其他语言用户
> 
> 
> ### 描述
> 
> 使用include-all引入多个机场订阅后，会把节点安装名称强制排序，能否把这一参数加一个可选项呢？使节点可以安装机场给定的默认排序去呈现。

+1 很需要这个功能 请问你解决了吗？
