### ISSUE TITLE
[Feature] Proxy-Provider 使用的 URI 参数与 mihomo 原生 yaml 参数的映射关系文档

### ISSUE THREAD

**Issue by leic4u** [MetaCubeX/mihomo#1738]
### 验证步骤

- [X] 我已经阅读了 [文档](https://wiki.metacubex.one/)，确认了该功能没有实现
- [X] 我已在 [Issue Tracker](……/) 中寻找过我要提出的功能请求，并且没有找到
- [X] 我是中文用户，而非其他语言用户

### 描述

Mihomo 支持在 Proxy-Provider 中使用 `yaml / uri / base64` 三种格式的文件，在文档中可以找到说明： https://wiki.metacubex.one/config/proxy-providers/content/#__tabbed_1_2

但是节点 URI 中的各个参数与 mihomo 原生 yaml 格式配置的参数对应关系没有说明文档，我尝试在 Github 仓库里面搜索 `uri` `proxy-provider` `hysteria2` `vless` 等关键字也没有搜到。

能否补充一下相关文档？或者能帮忙指出在哪里可以查询这个映射关系，我可以来补充文档 PR 。

**Comment by xishang0128** [comment]
@leic4u 不会维护uri对应的内容,这部分算是被废弃的东西(仅保留兼容)

**Comment by leic4u** [comment]
> @leic4u 不会维护uri对应的内容,这部分算是被废弃的东西(仅保留兼容)

好的，理解。那方便指出下兼容代码在哪里吗，我自己学习下，我没找到兼容代码在哪😅

**Comment by leic4u** [comment]
已在此处找到将 URI 解析为 yaml 原生配置的代码： https://github.com/MetaCubeX/mihomo/blob/Meta/common/convert/converter.go 

简单整理了下映射关系，供大家参考（！注意：该功能已废弃，不可过分依赖该功能！）：
其中解析 `vless` 协议的代码很少，应该大部分解析的参数和 `vmess`协议是一样的。

### 1. hysteria

| URI 参数名      | 转换后参数名     |
| --------------- | ---------------- |
| hysteria        | type             |
| name            | name             |
| hostname        | server           |
| port            | port             |
| peer            | sni              |
| obfs            | obfs             |
| alpn            | alpn             |
| auth            | auth_str         |
| protocol        | protocol         |
| up / upmbps     | up               |
| down / downmbps | down             |
| insecure        | skip-cert-verify |

### 2. hysteria2

| URI参数名     | 转换后参数名     |
| ------------- | ---------------- |
| hy2 hysteria2 | type             |
| name          | name             |
| hostname      | server           |
| port / none   | port / 443       |
| obfs          | obfs             |
| obfs-password | obfs-password    |
| sni           | sni              |
| alpn          | alpn             |
| insecure      | skip-cert-verify |
| password      | password         |
| pinSHA256     | fingerprint      |
| down          | down             |
| up            | up               |

### 3. tuic

| URI参数名          | 转换后参数名          |
| ------------------ | --------------------- |
| tuic               | type                  |
| name               | name                  |
| hostname           | server                |
| port               | port                  |
| -                  | udp                   |
| password           | password              |
| username           | uuid/token            |
| congestion_control | congestion-controller |
| alpn               | alpn                  |
| sni                | sni                   |
| disable_sni        | disable-sni           |
| udp_relay_mode     | udp-relay-mode        |

### 4. trojan

| URI参数名     | 转换后参数名      |
| ------------- | ----------------- |
| trojan        | type              |
| name          | name              |
| hostname      | server            |
| port          | port              |
| password      | password          |
| -             | udp               |
| allowInsecure | skip-cert-verify  |
| sni           | sni               |
| alpn          | alpn              |
| type          | network           |
| ws            | ws-opts           |
| grpc          | grpc-opts         |
| path          | path              |
| headers       | headers           |
| serviceName   | grpc-service-name |
| fp   | fingerprint                |


### 5. vless

| URI参数名 | 转换后参数名 |
| --------- | ------------ |
| vless     | type         |
| flow      | flow         |

### 6. vmess

| URI参数名         | 转换后参数名                 |
| ----------------- | ---------------------------- |
| vmess             | type                         |
| auto / encryption | cipher                       |
| net               | network                      |
| aid               | alterId                      |
| name              | name                         |
| add               | server                       |
| port              | port                         |
| id                | uuid                         |
| -                 | udp                          |
| -                 | xudp                         |
| tls               | tls                          |
| -                 | skip-cert-verify             |
| sni               | servername                   |
| net               | network                      |
| alpn              | alpn                         |
| http              | http-opts                    |
| h2                | h2-opts                      |
| ws / httpupgrade  | ws-opts                      |
| grpc              | grpc-opts                    |
| host              | host                         |
| path              | path                         |
| headers           | headers                      |
| ed                | max-early-data               |
| eh                | early-data-header-name       |
| httpupgrade       | v2ray-http-upgrade           |
| -                 | v2ray-http-upgrade-fast-open |
| host              | host                         |
| path              | path                         |
| headers           | headers                      |
| path              | grpc-service-name            | 

### 7. ss

| URI参数名          | 转换后参数名 |
| ------------------ | ------------ |
| ss                 | type         |
| name               | name         |
| hostname           | server       |
| port               | port         |
| username           | cipher       |
| password           | password     |
| udp-over-tcp / uot | udp-over-tcp |
| plugin             | plugin-opts  |
| -                  | udp          |
| mode / obfs        | mode         |
| host / obfs-host   | host         |
| path               | path         |
| tls                | tls          |

### 8. ssr

| URI参数名      | 转换后参数名   |
| -------------- | -------------- |
| ssr            | type           |
| remarks        | name           |
| host           | server         |
| port           | port           |
| method         | cipher         |
| password       | password       |
| obfs           | obfs           |
| protocol       | protocol       |
| -              | udp            |
| obfs-param     | obfs-param     |
| protocol-param | protocol-param |
