### ISSUE TITLE
[REQUEST] Tun 增加 post-up 参数

### ISSUE THREAD

**Issue by soffchen** [MetaCubeX/mihomo#183]
现在 tun 模式支持 auto-route，但是对于一些场景，需要自己分流的情况下，在 tun 起来之后执行一些路由规则，有 post-up 参数的话比较方便，例如
```
post-up: "ip r ad default dev Meta t 110"
```
因为 tun 起来比较不好从外部来监测，没起来之前执行不了这种命令，停掉之后又会被删掉，所以内置一个 post-up 会比较好。

请参考。

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
