### ISSUE TITLE
Xray-xtls-tcp “ISRG Root X1” certificate is not standards compliant

### ISSUE THREAD

**Issue by WaytrueDeng** [MetaCubeX/mihomo#196]
Shown as the tittle, how to solve it? I use the trustasia's one-year free cert, could you please support?

**Comment by Skyxim** [comment]
@WaytrueDeng You can try a fullchain certificate on the server, or use fingerprints to aid verification.
I don't have time recently. It may take a few days to fix this known problem.

**Comment by WaytrueDeng** [comment]
> 

Oh, Thanks, but What I used is already the fullchain cert. Maybe I should learn to how to use the fingerprints

**Comment by shallbytwo** [comment]
> @WaytrueDeng Meta supports certificate fingerprinting and certificate verification
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/5987f8e3b5d489c577328c4cbc147432cb45a498/docs/config.yaml#L31
> 
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/5987f8e3b5d489c577328c4cbc147432cb45a498/docs/config.yaml#L319
> 
> And does your device trust the root certificate of this certificate?

实测可以解决问题，但是证书续期后，fingerprint会变，这样得重新获取指纹再更新配置文件，些许繁琐。还是希望能尽快修复这个bug。

**Comment by Skyxim** [comment]
@shallbytwo 具体操作系统以及版本 还有证书信息

**Comment by shallbytwo** [comment]
> @shallbytwo 具体操作系统以及版本 还有证书信息

macOS13.1 客户端用的clash verge的最新Meta内核。服务器证书是acme.sh签的zerossl家。

**Comment by Skyxim** [comment]
@shallbytwo 检查证书的验证时间是多少，Not Before 和 Not After

**Comment by Skyxim** [comment]
openssl x509 -noout -text -in cert.pem
使用这个截图，怕泄漏域名，自己域名打码

**Comment by shallbytwo** [comment]
> @shallbytwo 检查证书的验证时间是多少，Not Before 和 Not After

<img width="513" alt="image" src="https://user-images.githubusercontent.com/36500518/211818478-9345e1c4-3be5-4170-8672-5ab0867fe8b2.png">

**Comment by shallbytwo** [comment]
> > @shallbytwo 检查证书的验证时间是多少，Not Before 和 Not After
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/36500518/211818478-9345e1c4-3be5-4170-8672-5ab0867fe8b2.png">

使用的是全链证书。不知道哪里出了问题

**Comment by ulion** [comment]
同样的问题，问题是出在使用provider功能订阅某个url，获取该url的时候报这个错误，而这个url使用chrome是可以正常访问到的，该网址的证书也在有效时间内

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。

如果你有需要请遵守模版开启新的issues

Considering that this issue did not use the correct template format, we decided to close it.

If you need to, please follow the template to open new issues
