### ISSUE TITLE
通过 api/configs 接口更新配置文件时不能开启 geoip.dat 支持

### ISSUE THREAD

**Issue by riverscn** [MetaCubeX/mihomo#197]
详情见 https://github.com/zzzgydi/clash-verge/issues/212

**Comment by riverscn** [comment]
curl.exe -H "Content-Type:application/json" -X PATCH --data '{\"geodata-mode\":\"true\"}' http://127.0.0.1:9090/configs

也是没用的……

**Comment by xishang0128** [comment]
geodata-mode值只在初始化使用,patch更改是无效的,请在配置直接开启
