### ISSUE TITLE
【Feature】Sniffer能否增加IPV4优先的相关配置

### ISSUE THREAD

**Issue by LarkinZero** [MetaCubeX/mihomo#199]
双栈网络下，有些域名ipv4是通的，ipv6不通，能否新增相应配置，对特定域名配置为只返回IPV4的DNS解析结果。
相应的，如果某些域名只希望访问其IPV6地址，可以也能通过这个配置实现。
进阶的，甚至可以做成非国内IP段的域名，强制使用IPV4地址，不使用IPV6地址。

**Comment by kkkgo** [comment]
建议fallback到第三方可以自定义disable ipv6的dns server，比如dnscrypt

**Comment by kkkgo** [comment]
> 建议fallback到第三方可以自定义disable ipv6的dns server，比如dnscrypt

不过这样有一个问题，有些地址是IPV6 ONLY的国外网站，用国内IPV6是可以联通的，而代理不支持IPV6，这个就没办法解决了。
当nameserver DNS解析出国内IPV4/国内IPV6时，返回nameserver的值（这个目前可以实现）；
当nameserver DNS解析出国外IPV4时，返回fallback的值（这个目前可以实现）；
当nameserver DNS解析出国外IPV4/IPV6时，返回IPV4 fallback的值（这个目前可以用第三方DNS实现）；
当nameserver DNS和fallback DNS都解析出国外IPV6 only时，返回IPV6 fallback的值（这个目前没法实现）；
因此我建议增加一个策略，比如fallback_ipv4_prefer，接受从fallback的值，存在双栈的时候过滤V6的结果，V6 only的时候返回V6结果。

**Comment by hplee0120** [comment]
+1 ，有prefer ipv4之后就可以抛弃mosdns了

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
