### ISSUE TITLE
更新到1684756后进不去PUBGM和Tik Tok等限制大陆地区的软件

### ISSUE THREAD

**Issue by Mydreams-awa** [MetaCubeX/mihomo#200]

**Comment by MetaCubeX** [comment]
@Mydreams-awa 代理ip被封禁了吧？

**Comment by Mydreams-awa** [comment]
> @Mydreams-awa 代理ip被封禁了吧？

并没有，我回退到a9694fc版本就可以进

**Comment by Mydreams-awa** [comment]
俺不造啊，emm，tun模式？

**Comment by MetaCubeX** [comment]
> 俺不造啊，emm，tun模式？

节点是什么协议？

**Comment by Mydreams-awa** [comment]
vmess这些嘛？![Screenshot_2022-10-01-22-47-58-839_com.dashboard.kotlin.jpg](https://user-images.githubusercontent.com/79519077/193415083-1399c3e8-40d4-44c1-a300-4c3394b4534f.jpg)

**Comment by Mydreams-awa** [comment]
不管什么节点都进不去PUBGM

**Comment by MetaCubeX** [comment]
@Mydreams-awa e1ec4a2， 82c9a1a， b133bc5。逐个试试

**Comment by Mydreams-awa** [comment]
试啥🌚🌚

**Comment by MetaCubeX** [comment]
@Mydreams-awa 以上三个版本

**Comment by Mydreams-awa** [comment]
不好意思，现在还在打CSGO

**Comment by Mydreams-awa** [comment]
晚一点试

**Comment by Mydreams-awa** [comment]
咋下？🌚🌚

**Comment by MetaCubeX** [comment]
@Mydreams-awa 用新版瞧瞧……

**Comment by Mydreams-awa** [comment]
![Screenshot_2022-10-01-23-49-48-429_com.miui.home.jpg](https://user-images.githubusercontent.com/79519077/193417482-87f7a4f8-b90d-4534-9922-a71c429efb1b.jpg)

**Comment by Mydreams-awa** [comment]
[TCP] dial Domestic (match GeoSite(tiktok)) to gecko16-platform-useast5.us.tiktokv.com:443 error: dual stack tcp shake hands failed
报错信息是这样？

**Comment by Mydreams-awa** [comment]
@MetaCubeX 我刚刚才发现，规则里让Tik Tok走直连，然后我把那行删掉就可以刷了，不好意思让你忙活那么久

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
