### ISSUE TITLE
关于支持ss2022的多用户模式

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/mihomo#210]
目前测试下来，似乎还不支持ss2022的多用户模式。
ss2022多用户配置案例：
https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022

**Comment by moranno** [comment]
> @moranno 直接写多用户中的password就行了,服务端多用户又不需求客户端配置

我反复验证了下，不是clash meta的问题，应该是图形化客户端的问题，使用clash verge不行，Openclash可以。

另外服务端多用户，客户端也需要配置：
"password": "{{ server psk }}:{{ user psk }}"

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
