### ISSUE TITLE
能否支持Mitm功能，进行url重写，可以参考下Adguard home的mim

### ISSUE THREAD

**Issue by LittleRey** [MetaCubeX/mihomo#217]

**Comment by llity** [comment]
能支持这个无敌了

**Comment by ccmuyuu** [comment]
@llity 看分支

**Comment by llity** [comment]
谢谢，看见了

**Comment by leeaash** [comment]
怎么用?

**Comment by llity** [comment]
多久合并到主支就好了。mitm对去软件内广告还是不错的

**Comment by CHIZI-0618** [comment]
@llity 我孤陋寡闻了？ AdGuardHome 啥时候支持 MITM 了？

**Comment by llity** [comment]
> @llity 我孤陋寡闻了？ AdGuardHome 啥时候支持 MITM 了？

home确实不行，希望mitm功能能合并到主分支。

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
