### ISSUE TITLE
 是否考虑支持naiveProxy

### ISSUE THREAD

**Issue by feidaodu** [MetaCubeX/mihomo#223]
现实原因，其它都被识别了。。封了不少。
是不是考虑，支持NaiveProxy，这东东试了一下，还挺快的。。也简单。

**Comment by Job28703** [comment]
支持naiveProxy！！

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
