### ISSUE TITLE
SSR订阅通过proxy-provider导入后部分节点缺失

### ISSUE THREAD

**Issue by sjtuross** [MetaCubeX/mihomo#225]
经排查发现，缺失的节点分享URL中都含有`_`，替换成`/`之后就能正常base64解码了

应该是分享URL生成的时候，做了urlSafe的操作，把`+`和`/`分别替换成了`-`和`_`，在base64解码之前要先替换回来

**Comment by bsdcpp** [comment]
同样问题，至今没解决啊

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
