### ISSUE TITLE
订阅中含有hysteria节点通过proxy-provider转换失败

### ISSUE THREAD

**Issue by sjtuross** [MetaCubeX/mihomo#226]
原始URI
`hysteria://example.com:2083?protocol=udp&auth=123456&peer=example.com&insecure=0&upmbps=100&downmbps=100&alpn=h3&obfs=xplus&obfsParam=123456#remarks`

转换成订阅中的base64
`aHlzdGVyaWE6Ly9leGFtcGxlLmNvbToyMDgzP3Byb3RvY29sPXVkcCZhdXRoPTEyMzQ1NiZwZWVyPWV4YW1wbGUuY29tJmluc2VjdXJlPTAmdXBtYnBzPTEwMCZkb3dubWJwcz0xMDAmYWxwbj1oMyZvYmZzPXhwbHVzJm9iZnNQYXJhbT0xMjM0NTYjcmVtYXJrcw==`

订阅中含这个节点就无法导入

**Comment by LaelLuo** [comment]
像是obfs的问题 我也遇到了提示 missing obfs password

**Comment by jasinliu** [comment]
这个问题目前有问题，还没有被关注到，请问目前有解决方案吗

**Comment by LaelLuo** [comment]
> 这个问题好像目前仍然存在，还没有被关注到，请问目前有解决方案吗

可以试试删除节点中的obfs配置

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
