### ISSUE TITLE
能否支持hysteria协议的wechat-video传输协议？这样对于服务器而言会变得更加安全可靠。感谢感谢！！！

### ISSUE THREAD

**Issue by fenger7** [MetaCubeX/mihomo#227]

**Comment by qist** [comment]
to rr3---sn-a5mekn6k.googlevideo.com:443 error: faketcp is not supported on this platform

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
