### ISSUE TITLE
tun 模式连接 wifi 没网

### ISSUE THREAD

**Issue by 0730aa** [MetaCubeX/mihomo#234]
用 tun 模式，当网络切换为 wifi 的时候，会没网，wifi 关掉换流量马上可以
![Screenshot_20221102_090640](https://user-images.githubusercontent.com/97997625/199372287-3c43d037-a5eb-476a-b5de-f8a3fe13e623.jpg)

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
