### ISSUE TITLE
【BUG】Not an executable file after unzipping

### ISSUE THREAD

**Issue by gimgoo** [MetaCubeX/mihomo#238]
Why do I get a document instead of an executable after downloading and unzipping

I downloaded it twice with the same result

![image](https://user-images.githubusercontent.com/31849284/199944405-796a9e0b-894d-4f29-8b2c-b017d820e236.png)

![image](https://user-images.githubusercontent.com/31849284/199945461-3914a924-86d1-431c-a342-da93845d2e64.png)

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
