### ISSUE TITLE
多次速度测试发现最新版内核使用Hysteria协议访问速度相较v2rayN明显下降，老版Clash.Meta内核速度下降不明显。

### ISSUE THREAD

**Issue by fenger7** [MetaCubeX/mihomo#240]
v2rayN
![f539ca651b4db1df2e5761a896e9f60](https://user-images.githubusercontent.com/11532918/200012867-96a0be2a-123c-41d6-b690-095599a147a8.jpg)

**Comment by fenger7** [comment]
Clash for Windows
![03c0acdeb99f714c4ce9639521bc1ee](https://user-images.githubusercontent.com/11532918/200013044-2d4ab5d3-ce48-49f0-bb2f-a88bf78bdfe7.jpg)

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
