### ISSUE TITLE
win7 sp1 如下錯誤提示？哪位大神有解決方案

### ISSUE THREAD

**Issue by alsojin0806** [MetaCubeX/mihomo#242]
![YGB R8K$~0M30 RCBTFW O0](https://user-images.githubusercontent.com/3974508/200152175-980ddef9-0fb8-4822-aa0f-9b54ab6e46be.png)

**Comment by alsojin0806** [comment]
看見這個問題 https://github.com/xjasonlyu/tun2socks/issues/157也沒下文？

**Comment by alsojin0806** [comment]
> 看見這個問題 [xjasonlyu/tun2socks#157](https://github.com/xjasonlyu/tun2socks/issues/157)

沒下文

**Comment by ccdd4ever** [comment]
需要安装系统补丁

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
