### ISSUE TITLE
dual stack tcp shake hand failed

### ISSUE THREAD

**Issue by 0730aa** [MetaCubeX/mihomo#245]
![Screenshot_20221106_210125](https://user-images.githubusercontent.com/97997625/200226122-8a073a3b-416a-4c17-b316-d2667b8802ac.jpg)
这个问题一般是什么原因？我的一个规则集只要选直连就会这样，好像很多直连都会这样，但是我选择过代理就不会显示 握手失败，这是什么回事？有解决方法吗？

**Comment by baraja** [comment]
#253

**Comment by auqhjjqdo** [comment]
我也是1.13直连就tcp握手失败，1.12正常连接

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
