### ISSUE TITLE
延时测试问题

### ISSUE THREAD

**Issue by 0730aa** [MetaCubeX/mihomo#251]
在代理组里我引用你们之前提到 lazy: false 了
并且时间设置在 1个小时 自动测试，但是启动已经一个小时过去了，面板节点还是灰色，不知道自动选择节点还起不起作用
启动时间 7:02，到 8:30 还是灰色
基本一整天都是灰色，我已经好久没看到绿色了
![a570b5af98d7f39](https://user-images.githubusercontent.com/97997625/200708309-5531ed31-9880-425e-b992-62fe3804eb00.jpg)
![5ee980c4ae266ddd](https://user-images.githubusercontent.com/97997625/200708343-495a080d-071f-43a3-94bb-4a2cca4e18e8.jpg)
![Screenshot_20221109_083822](https://user-images.githubusercontent.com/97997625/200708372-08aabd96-66bd-4ac4-9271-39fa5dfd46a1.jpg)

用的最新内核，最新面板

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
