### ISSUE TITLE
增加类似 surge skip-proxy 或 Clash for Windows bypass 跳过指定域名和网段的非 HTTP 请求

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/mihomo#252]
Hi

能否增加类似 surge 和 [Clash for Windows](https://docs.cfw.lbyczf.com/) 跳过自定义的**网段**（类似 **内网**）和 **域名** 请求的功能

直接跳过 **办公网**、**内网** 环境  **非 `http://` 协议** 请求：

- `wss://`
- Kafka
- grpc
- ...

https://github.com/scomper/Surge/blob/master/surgeNew.conf

``` ini
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost,*.local
```

https://docs.cfw.lbyczf.com/contents/bypass.html

```yaml
bypass:
  - "example.com"
  - 127.0.0.1
  - ...
```

感谢

**Comment by Skimmle** [comment]
Tun 配置暂时没暴露 exclude，现在只支持 include
~~Surge 的 skip-proxy 是正对系统代理设置的，和 tun 无关~~
