### ISSUE TITLE
Hysteria [端口跳跃/多端口](Port Hopping)

### ISSUE THREAD

**Issue by Job28703** [MetaCubeX/mihomo#258]
clash_meta:
Describe the Feature
长时间单端口 UDP 连接容易被运营商封锁/QoS 的问题

Describe the Solution
封锁/QoS 的问题。
clash_meta 的客户端都没有很好的支持这一功能

Describe Alternatives
Hysteria 修改 UDP
设置udp链接自动过期时间，
然后会话平滑转移到新链接，
然后就可以避免某个链接被qos

Additional Context
clash_meta 的客户端
Hysteria 修改 UDP

**Comment by Job28703** [comment]
麻煩更新 Hysteria！！
謝謝！

**Comment by geoleonsh** [comment]
#269

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
