### ISSUE TITLE
大佬,不支持naive协议啊

### ISSUE THREAD

**Issue by CciniSix** [MetaCubeX/mihomo#262]
大佬,不支持naive协议啊

**Comment by fredericky123** [comment]
求支持

**Comment by istek** [comment]
求支持naive协议

**Comment by Job28703** [comment]
求支持

**Comment by tgNotHouse** [comment]
求支持

**Comment by jtzhpf** [comment]
求支持

**Comment by Miroxyz** [comment]
求支持

**Comment by A-Pupils-form-china** [comment]
求支持

**Comment by Rosabis** [comment]
求支持

**Comment by PuerNya** [comment]
@Rosabis 这里引用一下 sing-box 项目开发者的原文

*Naive 出站*
*NaïveProxy 的主要功能是 chromium 的网络栈，仅实现它的传输协议是舍本逐末的。*

**Comment by Rosabis** [comment]
> @Rosabis 这里引用一下 sing-box 项目开发者的原文
> 
> _Naive 出站_ _NaïveProxy 的主要功能是 chromium 的网络栈，仅实现它的传输协议是舍本逐末的。_

我能做的并不多，是机场决定的

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
