### ISSUE TITLE
Tun + autoroute不能正确连接本地的socks代理

### ISSUE THREAD

**Issue by lchannng** [MetaCubeX/mihomo#263]
Alpha：2a8e1778ad1d7b507e432f659407d76dffcaacb8 编译的
运行环境：opwnwrt 22.03.2

interface:
wan: x.x.x.x
br-lan: 172.17.2.1
Meta: 198.18.0.1 # tun

openwrt上开了一个socks5代理, listen br-lan: 172.17.2.1:9999

https://github.com/MetaCubeX/Clash.Meta/blob/Meta/component/dialer/dialer.go#L111
开tun + autoroute + auto-detect-interface，dialer绑定在wan上，这个时候不能连接br-lan的代理

报错
> connect error: dual stack tcp shake hands failed

**Comment by lchannng** [comment]
traceroute了一下，是走wan的gateway出去了，跑远了，永远都连不上br-lan的...

**Comment by leeaash** [comment]
找打一个很土鳖的办法，写一个本地接口的proxy, 然后利用rule强制流量走此proxy

  -
    name: HOME
    type: select
    interface-name: br-lan
    proxies:
      - DIRECT

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
