### ISSUE TITLE
hysteria, 用户在首次链接的时候报WARNING[TCP] dial GENERAL (match Match()) to zerossl.crt.sectigo.com:80 error: CRYPTO_ERROR (0x12a): x509: “USERTrust ECC Certification Authority” certificate is not standards compliant

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/mihomo#265]
使用hysteria，证书为可信CA颁发的ECC证书，不跳过证书验证，部分用户在首次链接的时候，日志报错：
`WARNING[TCP] dial Doggygo (match Match()) to zerossl.crt.sectigo.com:80 error: CRYPTO_ERROR (0x12a): x509: “USERTrust ECC Certification Authority” certificate is not standards compliant`
多尝试链接几次后成功。

过一段时间（一般为半天到1天）后再次链接，又出现上面的报错。再次尝试几次链接后又正常。

尝试跳过证书验证，则不会报错。

请指点排查方向，或造成此问题的原因？感谢！

**Comment by miku1958** [comment]
我也有遇到, 之前用原生clash + vmess的时候不会, 但之前没有配置tls, 怀疑原版clash就有问题

**Comment by fannwong001** [comment]
貌似用openssl自己生成的证书速度最快。用acme的卡。建议对证书格式适配多一些或者说明一下应该用哪些工具生成哪些格式的。

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
