### ISSUE TITLE
核心报错 

### ISSUE THREAD

**Issue by eamon-cai** [MetaCubeX/mihomo#267]
内核版本 1.13.2
未开tun
大概五六个小时就会崩溃一次
panic: runtime error: slice bounds out of range [400:42]

goroutine 106802 [running]:
internal/poll.(*FD).Write(0xc003fa3680, {0xc006056000, 0x2a, 0x8000})
	internal/poll/fd_windows.go:703 +0x435
net.(*netFD).Write(0xc003fa3680, {0xc006056000?, 0xc007fd1ba8?, 0xc8a526?})
	net/fd_posix.go:96 +0x29
net.(*conn).Write(0xc0001b4220, {0xc006056000?, 0x1010000c7a74d?, 0x11be3be5908?})
	net/net.go:195 +0x45
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Write(0xc004ff87a0, {0xc006056000?, 0x15bdde0?, 0xc005bb0a01?})
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:48 +0x2e
io.copyBuffer({0x18c8be0, 0xc005bb0a10}, {0x18c8bc0, 0xc005bb0a20}, {0x0, 0x0, 0x0})
	io/io.go:429 +0x204
io.Copy(...)
	io/io.go:386
github.com/Dreamacro/clash/common/net.Relay({0x18d96c8?, 0xc0046c4900}, {0x11be3cd9258?, 0xc004ff87a0})
	github.com/Dreamacro/clash/common/net/relay.go:21 +0x18e
github.com/Dreamacro/clash/tunnel.handleSocket({0x18d0d80?, 0xc006fda870?}, {0x11be3cd9258, 0xc004ff87a0})
	github.com/Dreamacro/clash/tunnel/connection.go:63 +0x45
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x18d0d80, 0xc006fda870})
	github.com/Dreamacro/clash/tunnel/tunnel.go:375 +0xdd9
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:149 +0x71

**Comment by eamon-cai** [comment]
崩溃前 大量error: dual stack dial failed:context deadline exceeded报错 然后
panic: runtime error: slice bounds out of range [50:24]

goroutine 631478 [running]:
internal/poll.(*FD).Write(0xc0019afb80, {0xc000dec000, 0x18, 0x1000})
	internal/poll/fd_windows.go:703 +0x435
net.(*netFD).Write(0xc0019afb80, {0xc000dec000?, 0x8?, 0xc006c0eca8?})
	net/fd_posix.go:96 +0x29
net.(*conn).Write(0xc000206110, {0xc000dec000?, 0xfff0e?, 0xc002bee920?})
	net/net.go:195 +0x45
crypto/tls.(*Conn).write(0xc006c0ea80, {0xc000dec000?, 0x5?, 0x1000?})
	crypto/tls/conn.go:922 +0x108
crypto/tls.(*Conn).writeRecordLocked(0xc006c0ea80, 0x15, {0xc006c0edac, 0x2, 0x10})
	crypto/tls/conn.go:990 +0x354
crypto/tls.(*Conn).sendAlertLocked(0xc006c0ea80, 0x0)
	crypto/tls/conn.go:823 +0x5f
crypto/tls.(*Conn).closeNotify(0xc006c0ea80)
	crypto/tls/conn.go:1372 +0xe7
crypto/tls.(*Conn).Close(0x24?)
	crypto/tls/conn.go:1341 +0x69
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Close(0xc002bee960)
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:57 +0x42
github.com/Dreamacro/clash/tunnel.handleTCPConn.func2({0xd85f70?, 0xc002bee960?})
	github.com/Dreamacro/clash/tunnel/tunnel.go:375 +0x27
github.com/Dreamacro/clash/tunnel.handleTCPConn({0xd77b80, 0xc00da1a930})
	github.com/Dreamacro/clash/tunnel/tunnel.go:398 +0xf0b
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:159 +0x71

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
