### ISSUE TITLE
普通tcp流量经过clash后被转化为mptcp，导致一些网站无法访问

### ISSUE THREAD

**Issue by vumb5j** [MetaCubeX/mihomo#268]
环境：华硕AX56U路由器，梅林固件386.7_2
版本：clash-armv7 Aplha版
配置：iptables/tproxy/redir-host，可通过[shellclash](https://github.com/juewuy/ShellClash)重现

问题描述：

配置透明代理后，无法访问 [https://www.52pojie.cn](https://www.52pojie.cn)（一直处于等待状态），经tcpdump抓包后发现该流量经过clash后被转化为mptcp流量，然而目标网站不支持mptcp，关闭路由器mptcp后解决。

临时解决方案：
`echo 0 > /proc/sys/net/mptcp/mptcp_enabled`

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。

如果你有需要请遵守模版开启新的issues

Considering that this issue did not use the correct template format, we decided to close it.

If you need to, please follow the template to open new issues
