### ISSUE TITLE
希望增加naiveproxy协议支持

### ISSUE THREAD

**Issue by magicmatt2020** [MetaCubeX/mihomo#273]
试用了naiveproxy速度，稳定性很好，客户端逐渐都支持了，希望clash meta也能支持

**Comment by Xwler** [comment]
别想了，不可能的

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.

**Comment by Buer-Nahida** [comment]
> 考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。
> 
> 如果你有需要请遵守模版开启新的 issues。
> 
> Considering that this issue did not use the correct template format, we decided to close it.
> 
> If you need to, please follow the template to open new issues.

@xishang0128 Mihomo项目删Issue的标准是什么？我提的关于NaiveProxy支持的，为何都被删？甚至被删除时我没有受到任何邮件通知，我邮件通知开着的，并且也没有点Unsubscribe按钮，这意味这仓库所有者/协作者没有说明任何原因就删除了我的Issue，我确定我的Issue里没有任何不和谐/企图挑起对立的语言，NaiveProxy支持就算不想支持就close with not planned就可以了吧？没必要删Issue吧？
