### ISSUE TITLE
简单的 failover 机制

### ISSUE THREAD

**Issue by josh-chan** [MetaCubeX/mihomo#278]
跟目前的 fallback 不一样，目前几种 group: url-test, fallback, load-balance 有一个问题（也许必须）就是会泄漏组内所有代理, 因为会定期 check 所有代理服务器。

是否可以增加一种简单的机制，暂时叫 failover, 当当前 proxy 连接失败时，自动切换到列表的下一个 proxy, 但是不需要定期 check 每个 proxy 是否可用/快！

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
