### ISSUE TITLE
vmess-ws path

### ISSUE THREAD

**Issue by goldadigida** [MetaCubeX/mihomo#279]
I found a problem in clash, clash meta, and singbox when using vmess-ws with this configuration

proxies:
  - {name: HERZA, server: id1-temp.v2-ray.com, port: 80, type: vmess, uuid: xxxxxxxxx, alterId: 0, cipher: auto, tls: false, network: ws, ws-opts: {path: /worryfree/?u=vgaiao&p=6384f7766be43, headers: {Host: tsel.me}}, udp: true}

but this problem doesn't happen in v2ray or xray

similar problem https://github.com/Dreamacro/clash/pull/2213
But this is not fix my issue

Hope someone help me

Thanks

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
