### ISSUE TITLE
是不是开了Sniffer没必要开dns

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/mihomo#280]
路由器上挂了smardns，试着关了clash的内置dns
发现一切都正常，域名也能传递到clash分流

有什么潜在风险吗

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
