### ISSUE TITLE
openclash dev 75 支持了hysteria端口跳跃的配置，但是无法启用

### ISSUE THREAD

**Issue by eightsheep67** [MetaCubeX/mihomo#284]
openclash最新dev 75
metacore最新alpha
hysteria core服务端客户端均为最新

但是配置如果增加了ports，hopping interval就会无法连接。
配置就是增加
ports: 47000-48000
hopping interval: 180

这样写法可以吗？

**Comment by ID404** [comment]
遇到同样的问题，配置完端口后提示：
level=fatal msg="Parse config error: proxy 1: key 'port' missing"

**Comment by xishang0128** [comment]
@ID404 内核并没有支持端口跳跃

**Comment by eightsheep67** [comment]
> @ID404 内核并没有支持端口跳跃

ALPHA内核支持了呀，但是看PR里好像是有点问题。

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
