### ISSUE TITLE
Hysteria协议使用代理下载文件，中途暂停下载，再继续下载会断流。

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/mihomo#295]
如果在下载中途暂停，然后再继续下载，大概下载个几十MB不等，就会出现断流；服务端能持续收到客户端的消息，但无法继续下载（断流的状态）。

使用hy原版客户端则不会出现断流的情况。

图片是服务端日志：
![image](https://user-images.githubusercontent.com/77610980/206956863-eeb15635-e2aa-403e-bc00-e22e19292e07.png)

**Comment by fannwong001** [comment]
小火箭也这样

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
