### ISSUE TITLE
clash本机网卡有两个IP场景情况下，clash不可用

### ISSUE THREAD

**Issue by githublovered** [MetaCubeX/mihomo#300]
指定了网卡,然后拿网卡的地址没有考虑，导致功能失效
![20221214-160255](https://user-images.githubusercontent.com/12123404/207540134-53c4195f-ed2c-4b16-93d4-b53508a141cd.jpg)

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
