### ISSUE TITLE
请问 nameserver-policy 支持单一域名由多个dns并发查询吗

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/mihomo#307]
```   
  nameserver-policy:                
   'services.googleapis.cn': '1.1.1.1#auto'
```

**Comment by Skyxim** [comment]
@GeorgeRudd 基本与 clash 原本逻辑无差别

**Comment by fredericky123** [comment]
同期待 并发解析

**Comment by fredericky123** [comment]
@GeorgeRudd 请问解决了吗

**Comment by fredericky123** [comment]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/13982749/217995219-676a769b-0e06-45ba-8d97-5162bf8801ef.png">
你是用的alpha版本吗 我为啥还不能配置呢

**Comment by fredericky123** [comment]
我需要这样配置，不能用-“” 分行，否则会提示上图的分行错误
<img width="286" alt="image" src="https://user-images.githubusercontent.com/13982749/217996659-b3f0f462-c1d0-4adb-ab0b-619aa113979a.png">
