### ISSUE TITLE
能不能给个选项，fallback组才丢弃ipv6的dns解析

### ISSUE THREAD

**Issue by a904055262** [MetaCubeX/mihomo#323]
这样国内就能保留IPV6了，国外回落ipv4可以走代理。

**Comment by qist** [comment]
我用https://github.com/AdguardTeam/AdGuardHome 关闭IPV6 然后https+cdn 代理httpdns

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
