### ISSUE TITLE
[Feature Request] Add support AND/OR/NOT in RULE-SET

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/mihomo#325]
Is it possible to add AND/OR/NOT features to RULE-SET (classical/rule-providers)

**Comment by samlux04** [comment]
Yeah I need it too. For example I want to build games.yaml
It's too crowded to put everything in main config. 
```yaml
payload: 
  - AND,((DST-PORT,30008),(NETWORK,UDP))
```

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
