### ISSUE TITLE
更新版本后clash进程导致CPU占用100%

### ISSUE THREAD

**Issue by msbtx** [MetaCubeX/mihomo#331]
更新1.14版本后，在路由器上的clash日志里看到疯狂刷出访问国内IP（CN配置直连），试图进行TCP连接，端口绝大部分是26881，还有一小部分是55925，结果都是connect: connection refused，同时路由器的CPU占用达到了100%。

不确定是否是因为更新版本导致的，因为今天刚好更新了clash.meta的版本，发现网速特别慢，就看了一下，CPU占用100%。发现这个问题后怀疑geoip数据库错误，更新了一下ipip数据库，仍然存在该问题：

![image](https://user-images.githubusercontent.com/6949433/211616569-01e95cc4-d90e-48ed-b91e-f0461e46b89b.png)

**Comment by msbtx** [comment]
网上查了一下，是搜狗输入法的东西，尝试输入法设置里进行升级，提示联网不成功；
尝试开关clash并清除PC的DNS缓存，问题仍然存在；
把PC重启之后尝试升级输入法，联网OK了，然后看日志就没这个打印了。
看起来是输入法APP的问题？

**Comment by msbtx** [comment]
看了一个小时的奈飞，CPU再次占用100%。上一个版本没有这个问题，升级前后配置没有改变，看起来较大概率是新版本引入的问题

**Comment by hkthomas** [comment]
debian 11 自编译 1.10 也遇到相同问题。release里的没有遇到过，

**Comment by msbtx** [comment]
将内核降级到1.13.2，挂测了一天，没有问题。将内核升级到刚刚更新的1.14.1，一个半小时候复现CPU 100%问题

**Comment by cubemaze** [comment]
@msbtx 把进程规则关了

**Comment by msbtx** [comment]
> @msbtx 把进程规则关了

不好意思，进程规则是指什么？

**Comment by msbtx** [comment]
> @msbtx find-process-mode: off

感谢回答，我下班试了一下，设置好之后，更新了一下英雄联盟，不到5分钟CPU就100%了，即使没有任何流量也无法恢复正常。
另外你说的这个似乎跟PROCESS-NAME规则有关，我的配置里面没有设置这样的规则。

我昨天把fallback dns使用节点解析取消了，并把fallback-filter的geosite取消了，挂了一天也没有问题。看起来是1.14和1.14.1的dns相关代码改动导致的这个问题。

**Comment by cubemaze** [comment]
> > @msbtx find-process-mode: off
> 
> 感谢回答，我下班试了一下，设置好之后，更新了一下英雄联盟，不到5分钟CPU就100%了，即使没有任何流量也无法恢复正常。 另外你说的这个似乎跟PROCESS-NAME规则有关，我的配置里面没有设置这样的规则。
> 
> 我昨天把fallback dns使用节点解析取消了，并把fallback-filter的geosite取消了，挂了一天也没有问题。看起来是1.14和1.14.1的dns相关代码改动导致的这个问题。

异常部分的配置方便发出来吗

**Comment by msbtx** [comment]
> > > @msbtx find-process-mode: off
> > 
> > 
> > 感谢回答，我下班试了一下，设置好之后，更新了一下英雄联盟，不到5分钟CPU就100%了，即使没有任何流量也无法恢复正常。 另外你说的这个似乎跟PROCESS-NAME规则有关，我的配置里面没有设置这样的规则。
> > 我昨天把fallback dns使用节点解析取消了，并把fallback-filter的geosite取消了，挂了一天也没有问题。看起来是1.14和1.14.1的dns相关代码改动导致的这个问题。
> 
> 异常部分的配置方便发出来吗

经过测试，主要是被红色标记的这三处会导致这个问题。手动切换3是一个select的proxy-groups，目前选择的是一个trojan grpc节点

![image](https://user-images.githubusercontent.com/6949433/212459119-5c5b186c-fb1b-48f0-a53c-3bf97b69aad2.png)

**Comment by tgNotHouse** [comment]
@msbtx  几天前注释了dns相关配置后，就再也没有出问题了吗。这段时间还有动其他配置了吗？

**Comment by msbtx** [comment]
> @msbtx  几天前注释了dns相关配置后，就再也没有出问题了吗。这段时间还有动其他配置了吗？

红色配置去掉之后一直都没有出现了

**Comment by tgNotHouse** [comment]
目前我观察是在dns配置里使用trojan代理解析域名会出现这种问题，ssr这种并不会

**Comment by remedynotavailable** [comment]
the problem is with grpc. regardless of the protocol. vmess, vless, trojan. I tried all. reading the code I notice it doesn't use full grpc go library but own tiny grpc over existing h2 library. maybe something not implemented fully, dunno.

**Comment by zhy1378** [comment]
我的 ClashX 版本是 1.118.1.1, 也有CPU占用率飙升到100%只能重新启动 ClashX 的情况。
我的电脑是 MacBook Pro 2019，操作系统是 Mac Sonoma 14.4.1

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
