### ISSUE TITLE
Feature request: Add client IP's subnet indication in dns field

### ISSUE THREAD

**Issue by Natsuki-Kaede** [MetaCubeX/mihomo#342]
Is it possible to add client IP address indication in dns field?
It would be better if they could be set separately in fallback and nameserver or every single server.

**Comment by Magic989** [comment]
Now we can try using sing-box to achieve this goal. They have added client_subnet to optimize CDN distribution performance. However, I also hope that mihomo can support this feature!

[sing-box.dns.rules.client_subnet](https://sing-box.sagernet.org/configuration/dns/rule/#rewrite_ttl:~:text=in%20DNS%20responses.-,client_subnet,Will%20overrides%20dns.client_subnet%20and%20servers.%5B%5D.client_subnet.,-Address%20Filter%20Fields)

**Comment by hu3rror** [comment]
+1

**Comment by ncpmeplmls0614** [comment]
求大神支持，这样国内CDN就顺畅了

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
