### ISSUE TITLE
no fullcone with shadowtls

### ISSUE THREAD

**Issue by fsheidaiee** [MetaCubeX/mihomo#344]
Hi
when changing the proxy to shadowtls fullcone is gone and it says udp is blocked.
please fix this
thanks

**Comment by H1JK** [comment]
You can try `udp-over-tcp`. Note that this feature needs server support.

**Comment by fsheidaiee** [comment]
> You can try `udp-over-tcp`. Note that this feature needs server support.

no luck
I think fullcone is corrupted after an update

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
