### ISSUE TITLE
sniffer和PROCESS-NAME对于走udp协议都支持不佳？

### ISSUE THREAD

**Issue by bash99** [MetaCubeX/mihomo#359]
443端口的quic协议，希望能嗅探到域名不走代理，发现没法配置。

ProcessName里面设置了verysimple，但是发出的udp仍然走代理，日志里面看不见PROCESS-NAME.

现在只好指定ip来跳过去。

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
