### ISSUE TITLE
重载配置文件CPU满占用+内存泄漏

### ISSUE THREAD

**Issue by lisansas** [MetaCubeX/mihomo#368]
内核版本：clash.meta-windows-amd64-alpha-cbc217e.zip和稳定版AMD64皆有此问题。

点的次数越多，内存泄漏越多，甚至可以把我的32g内存撑爆。

用了proxy-providers和rule-providers

**Comment by Skyxim** [comment]
点是指？

**Comment by lisansas** [comment]
> 点是指？

我是直接跑核心的 在dashboard的网页版里配置点reload 重载配置文件 这个时候就会卡顿上30秒左右 内存占用会增加800M左右？

而在这个30秒内连续点击，则会把内存撑爆

**Comment by skill7899** [comment]
一样的BUG

**Comment by IriKaQ** [comment]
我这儿有同样的问题。
不同的是我跑在 freebsd （OPNsense）上，连续运行一天后，内存占用会超过 1G （从 top RES）甚至直接 OOM（从控制台 log）。
怀疑有内存泄漏。

**Comment by sjhsbhqf** [comment]
我也有这个问题啊，突然涨到800MB了，把我吓一跳

**Comment by lbcake** [comment]
https://github.com/MetaCubeX/mihomo/issues/1250

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
