### ISSUE TITLE
IPV6在Meta v1.14.1非常慢，但在v1.13.2速度正常

### ISSUE THREAD

**Issue by SuperChenSSS** [MetaCubeX/mihomo#373]
有遇到相同问题的朋友吗? 我是ARMV7路由代理发现的

**Comment by Daring522** [comment]
我也是 meta卡得一笔啊 百度都打不开

**Comment by cleanery2022** [comment]
> 有遇到相同问题的朋友吗? 我是ARMV7路由代理发现的



> 我也是 meta卡得一笔啊 百度都打不开

`dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  use-hosts: true
  fake-ip-filter: ['+.lan', '+.local', '+.mshome', 'www.msftconnecttest.com', 'www.msftncsi.com', 'dns.msftncsi.com', 'dns.pub', 'dns.alidns.com', 'resolver1.opendns.com', 'detectportal.firefox.com', 'dmd.metaservices.microsoft.com', '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.stun.*.*.*.*.*', '*.n.n.srv.nintendo.net', '+.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.*.xboxlive.com', '*.msftncsi.com', '*.msftconnecttest.com', 'connect.rom.miui.com', '+.gstatic.com', 'lens.l.google.com', '*.mcdn.bilivideo.cn', 'WORKGROUP', '*']
  fake-ip-range: 28.0.0.1/8
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://1.12.12.12/dns-query'
  default-nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://1.12.12.12/dns-query'
  # 新配置 clash.meta v1.14.2 config changes
  nameserver-policy:
    "geosite:cn": 
      - 'https://223.5.5.5/dns-query'   # alidns
      - 'https://1.12.12.12/dns-query'   # dns.pub
  nameserver:
    - 'tcp://185.222.222.222#dns'  # dns.sb
    - 'tcp://94.140.15.15#dns'     # adguard
    - 'tcp://8.8.4.4#dns'          # google`

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
