### ISSUE TITLE
搭配 ShellClash 使用时机场密码更换后 proxy-providers 里 yaml 文件内的密码无法同步

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/mihomo#395]
### Clash.Meta 版本：  
v1.14.1
### ShellClash 版本：  
v1.7.0
### 问题：
ShellClash 使用 Clash.Meta 核心，采用 proxy-providers 添加订阅，如果修改了机场密码（非订阅链接），不管是使用 ShellClash-6-4 更新订阅，还是通过面板-代理-Proxy Provider 的更新，都无法同步 proxy-providers 中 path 里的 yaml 文件内的 password，如图：  
![photo_2023-02-18_16-57-09](https://user-images.githubusercontent.com/45238096/219851788-b9dfb765-e663-40a9-a354-6fba0dbbff13.jpg)

### 临时解决方法：
需要将/data/clash/proxies 里的文件全部删除，重启 ShellClash 服务，然后进入面板-代理-Proxy Provider 进行更新

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
