### ISSUE TITLE
[bug] hosts only support set to 127.0.0.1

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/mihomo#404]
I'm using clash hosts but not running with another ip

Example:
```yaml
hosts:
  'google.com': 123.123.123.123
```

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
