### ISSUE TITLE
PASS 策略允许指定跳过次数

### ISSUE THREAD

**Issue by xkww3n** [MetaCubeX/mihomo#408]
有以下规则：
```yaml
rules:
- RULE-SET,Exceptions,PASS
- RULE-SET,Protection,Protection
- RULE-SET,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Final
```
其中，Protection 指定粗略的顶级域名进行拦截（如 `+.ad-example.com`），Exceptions 则将部分域名中提供正常服务的二级域名解除拦截（如 `homepage.ad-example.com`）
正常来说，Exceptions 规则组内的域名应当跳至第三行才能起到例外作用，但事实上则会跳到第二行，导致依然被拦截。

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
