### ISSUE TITLE
[BUG]搭配openclash使用tun模式会出现启动失败

### ISSUE THREAD

**Issue by Felix-Koh** [MetaCubeX/mihomo#421]
openclash使用meta内核,运行模式为tun,在启动时常常会遇到[tun接口启动失败,尝试重启内核],一般会自动重启一次meta内核后正常开启,偶尔会重启两次后正常开启.使用p核则无此问题.

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
