### ISSUE TITLE
Listeners 流量入站里 socks/http 可以添加用户名密码认证吗?

### ISSUE THREAD

**Issue by sougouzhinan** [MetaCubeX/mihomo#425]
![image](https://user-images.githubusercontent.com/36944588/222945781-3cd8ac18-c559-4223-bc9d-676514ec54ec.png)

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
