### ISSUE TITLE
[Feature] Add a certain "stickiness" to fallback proxy group

### ISSUE THREAD

**Issue by VZiChoushaDui** [MetaCubeX/mihomo#432]
**Problem description**

Suppose we have a fallback proxy group with two servers A and B, and with health check interval of 60 seconds. We prefer users to connect to A when it's available.

Now, let's suppose on a certain network, server A is suffering from many packet losses, but not completely blocked, and only 10% of health check pings go through successfully.

Upon a failed health check of A, proxy group switches to server B. But then, as 10% of health check pings for A are successful, there's a 10% chance on each health check interval that fallback sees A as available and switches back to A.

Now, user will have a very poor connection to server A until the next health check interval or for the timeout period of the connection to A, where it will be switching back to B again. This oscillation can occur in the lifetime of the Clash for user in this network, resulting in an unreliable connection.

Obviously, the url-test proxy group can't help in this scenario either, because the reliability of the connection might not have a correlation with its ping time, and also we can't set priority for url-test group.

**Possible solution**

A solution to this might be an optional property for the fallback proxy group, requiring multiple consecutive health check successes before switching back to a higher priority server. (And possibly also multiple consecutive failures before switching to a lower priority server, for the opposite scenario)

If such option exists, in the described scenario, after user switches to B, it will need for example 3 positive health checks in a row from server A before switching back to A, and as it's unlikely to happen in this scenario, user will remain on server B on this network, but finally will switch back to A whenever a *reliable* connection to A is possible.

**Comment by Skyxim** [comment]
@VZiChoushaDui The health check is based on http/https, and there is no packet loss rate.

**Comment by Skyxim** [comment]
The test node delay and node selection are now in the separation logic, and it is not timely to wait for A to recover multiple intervals. The fallback logic will be downgraded after many failures in a short period of time. If it fails due to packet loss, you can continue to use B

**Comment by Skyxim** [comment]
@Skyxim A Trying to connect is almost equal to trying multiple times as you say ping.

**Comment by VZiChoushaDui** [comment]
@Skyxim Thanks for your quick response.

The issue arises on switching back up to a higher priority server (A), when a health check succeeds for A (randomly, due to high packet loss many packets to A fail, but sometimes a health check can go through).

If I understand correctly, the single successful health check of A marks it as `alive`, and then as it has the highest priority, it will get selected until the next failure.


Our observation is that RULE mode with fallback causes an unreliable connection in this environment (where A is unstable but B is stable, and A has a higher priority in Fallback), and manually selecting B significantly improves the reliability; which resulted in this hypothesis. There might be another reason for this as well, but I can't think of any yet.

**Comment by VZiChoushaDui** [comment]
@mozilla-firefox URL-Test check (even with multiple requests) wouldn't help this scenario, as it does not have a priority mechanism.

But a similar underlying issue might be causing the inaccuracy in the issue you mentioned.

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
