### ISSUE TITLE
不知道match了什么规则

### ISSUE THREAD

**Issue by alfredtofu** [MetaCubeX/mihomo#435]
我在rules第一条设置了`DOMAIN-SUFFIX,3gppnetwork.org,us-07`，但是看log的时候发现`ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org:500 match  using Proxy`，请问这是匹配了什么规则？以及为啥我设置的规则不生效

**Comment by IriKaQ** [comment]
你写了一个域名后缀匹配规则，你访问的域名刚好匹配。这个没什么问题呀

**Comment by CStyleIO** [comment]
手机卡问题，这测试了几天。各种异常。就是udp 500 4500。不清楚为什么开了tun就不行了

**Comment by TeaWu** [comment]
> > 手机卡问题，这测试了几天。各种异常。就是udp 500 4500。不清楚为什么开了tun就不行了
> 
> @IriKaQ 是这个，没搞懂为什么，udp 500的不行

这个问题解决了吗

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
