### ISSUE TITLE
Listeners的用法请教

### ISSUE THREAD

**Issue by klgd** [MetaCubeX/mihomo#445]
我想通过不同的端口对应不同的节点，通过listeners是可以指定proxy，但是吧 节点有时候有不稳定的情况，这时指定具体的proxy就不是很合适了，请问有什么方式能动态地对应节点呢？

**Comment by Skyxim** [comment]
@klgd proxy 可以指定策略组

**Comment by xishang0128** [comment]
@klgd 和rules一样,proxy可以用proxies或者proxy groups

**Comment by xishang0128** [comment]
@klgd listeners:

  - name: mixed1
    type: mixed
    port: 20001
    proxy: listen1
proxy-groups:

  - name: listen1
    type: select
    proxies:
      - DIRECT
      - proxy1

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
