### ISSUE TITLE
关于override-destination启用的时候，分流逻辑请教

### ISSUE THREAD

**Issue by alecthw** [MetaCubeX/mihomo#451]
开启override-destination时，是使用嗅探的域名发起访问。

在opencalsh上使用的时候，当匹配结果为Direct的时候，是否也是使用域名在发起访问，还是使用客户端的请求的IP作为访问目标？

**Comment by Skyxim** [comment]
@alecthw direct 当然只有用 IP 访问了

**Comment by Skyxim** [comment]
@alecthw override-destination 替换目标，会在连接使用，代理就是把嗅探的发给服务器，直连就是用这个进行解析连接

**Comment by alecthw** [comment]
@Skyxim 感谢这么快回复！ 不好意思，还得再请教下。
还是当override-destination开启的时候，匹配direct，应该是哪种情况？
1. clash是用内置的dns再解析一次嗅探出的域名，然后发起连接
2. 直接使用客户端请求中的ip发起连接

**Comment by Bitcion** [comment]
> @alecthw override-destination 替换目标，会在连接使用，代理就是把嗅探的发给服务器，直连就是用这个进行解析连接

我最近一直有一个错误：
Mar 21 12:09:35 【clash】:  time="2023-03-21T04:09:35.725330548Z" level=error msg="[Sniffer] [149.154.175.55] may not have any sent data, Consider adding skip"

看这个ip是telegram，初步才想是telegram的ip配置了tls，然后前置分流dns解析时候，可能把纯ip送进了clash。
看了下 sniffer.sniff优先级太高，所以把参数换成了老参数，同时跳过了telegram的sni，似乎是临时解决了问题，还没长期测试。

如果我的猜想正确的话，如果是sniffer.sniff，解决这类问题（因为偶尔出现的不止是telegram，还有github）。应该如何设置跳过参数

**Comment by xishang0128** [comment]
@Bitcion https://github.com/MetaCubeX/Clash.Meta/blob/0336435ebc4346597a2d571999f780dd98418145/docs/config.yaml#L139
配置skip-domain

**Comment by Bitcion** [comment]
> @Bitcion
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/0336435ebc4346597a2d571999f780dd98418145/docs/config.yaml#L139
> 
> 
> 配置skip-domain

  ## 对嗅探结果进行跳过
  # skip-domain:
  #   - Mijia Cloud
  # 需要嗅探协议
  # 已废弃，若 sniffer.sniff 配置则此项无效


误会了，以为最后一个注解是给 skip-domain 的。也就是说

**Comment by xishang0128** [comment]
@Bitcion 最后一个注释是给下一行的

**Comment by Bitcion** [comment]
> @Bitcion 最后一个注释是给下一行的

没有啥参数能全局解决这个问题的呢，毕竟telegram只是比较常见，也有其他ip有这个问题。
或者以后新增一个参数，遇到“ may not have any sent data”自动sniffer跳过

**Comment by Skyxim** [comment]
@Bitcion 这个错误可能在客服端发送到 meta 失败时就产生（当然可能存在某个协议不由客服端发起链接）。在内部会有个禁止列表，包括但不限于这个错误 5 次嗅探失败，将在本次运行时禁用对这个地址的嗅探（也许后面会优化这个判断，让这个地址有机会再次尝试）

**Comment by Skyxim** [comment]
@Bitcion 和 DNS 关系不大

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
