### ISSUE TITLE
【bug】vmess grpc模式链接失败

### ISSUE THREAD

**Issue by breaking153** [MetaCubeX/mihomo#455]
配置文件：
{name: lizard 2, server: bmw.xx.xx, port: 2087, type: vmess, uuid: xxxxxx, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: grpc, servername: bmw.xx.xx, grpc-opts: {grpc-service-name: /}, udp: true}
Test-Connection:
![图片](https://user-images.githubusercontent.com/49428332/226511810-c273cd3d-541a-4e85-87bb-8f8eb1603524.png)
全都是vmess-grpc协议，建议严查

**Comment by ash0080** [comment]
```
{
    name: "[VMess] ", 
    server: 
    port: 
    client-fingerprint: chrome, 
    type: vmess, 
    uuid: 
    alterId: 0, 
    cipher: auto, 
    tls: true, 
    xudp: false, 
    tfo: true, 
    skip-cert-verify: true, 
    network: grpc, 
    servername: "", 
    grpc-opts: {
        grpc-mode: none, 
        grpc-service-name: 
    }, 
    udp: true
}

```
我也是, VMESS全都连不上, 这问题有解么?

**Comment by ash0080** [comment]
#1077

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
