### ISSUE TITLE
代理接管的直连,如何开启优先HTTP/3

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#456]
设置示例只有DNS prefer-h3,请问如何设置直连的域名优先使用h3

目前使用的WIN10, Chrome版本111,全局代理,使用Clash.Meta的mixed-port, F12打开看https://www.litespeedtech.com 网络协议是H2,这个网站经过Clash.Meta走的直连.
![http111](https://user-images.githubusercontent.com/19746145/226579379-d9a56854-6940-4ce9-b6b5-d1d663acd05b.png)

**Comment by Skyxim** [comment]
@ysdstm 系统代理不可能出现 h3 至少现在不可能

**Comment by Larvan2** [comment]
@ysdstm 可以用tun模式

**Comment by ysdstm** [comment]
> @ysdstm 系统代理不可能出现 h3 至少现在不可能

我描述有误,全局代理下的规则模式,直连访问的https://www.litespeedtech.com/

我是看DNS能走H3直连 dns.google和cloudflare-dns,所以问问http模式下的直连能否也优先尝试H3

**Comment by Skyxim** [comment]
> 

不可能

**Comment by xishang0128** [comment]
如果你用的是系统代理,那不可能支持http/3,系统的http代理不支持udp,chrome等浏览器的socks5也不支持udp,需要http/3需要开tun

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
