### ISSUE TITLE
[bug] infinite loop happened when the DNS's `ProxyAdapter` match the `nameserver-policy`

### ISSUE THREAD

**Issue by dyxushuai** [MetaCubeX/mihomo#459]
```
nameserver-policy:
    'geosite:!cn': # if example.com match this policy
      - 'tls://8.8.8.8:853#PROXY'

proxies:
	- name: "PROXY"
	   server: example.com
```
when `example.com` match the `geosite:!cn` rule, will cause an infinite loop.

https://github.com/MetaCubeX/Clash.Meta/blob/8293b7fdae91114329849fbf5f49ce738329ab97/dns/resolver.go#L224-L227
because the resolver needs check policy first

**Comment by Skyxim** [comment]
@dyxushuai Provides full configuration and logging

**Comment by dyxushuai** [comment]
It will never use the `r.main` resolver.

**Comment by dyxushuai** [comment]
Temp solution :
```
nameserver-policy:
	'example.com': 114.114.114.114 # any dns target without proxy adapter
    'geosite:!cn': # if example.com match this policy
      - 'tls://8.8.8.8:853#PROXY'

proxies:
	- name: "PROXY"
	   server: example.com
```

**Comment by Skyxim** [comment]
5737fbc2
Try setting up a `proxy-server-nameserver`

**Comment by johntaiko** [comment]
> [5737fbc](https://github.com/MetaCubeX/Clash.Meta/commit/5737fbc23cad0ac84f86d0e00002a6031c55ee6b) Try setting up a `proxy-server-nameserver`

I think this change can work as well
