### ISSUE TITLE
内存占用异常

### ISSUE THREAD

**Issue by xmengnet** [MetaCubeX/mihomo#462]
使用一段时间后内存越来越大
[heap.txt](https://github.com/MetaCubeX/Clash.Meta/files/11050093/heap.txt)

**Comment by xmengnet** [comment]
> @xmengnet 是否尝试过今天的 alpha

这跟alpha版本有什么关系吗？今天的alpha版本修复了什么？

**Comment by Skyxim** [comment]
> > @xmengnet 是否尝试过今天的 alpha
> 
> 
> 
> 这跟alpha版本有什么关系吗？今天的alpha版本修复了什么？

今天有尝试修复过 gVisor 导致的内存问题

**Comment by yiiyahui** [comment]
> > > > @xmengnet 是否尝试过今天的 alpha
> > > 
> > > 
> > > 这跟alpha版本有什么关系吗？今天的alpha版本修复了什么？
> > 
> > 
> > 今天有尝试修复过 gVisor 导致的内存问题
> 
> 试用了一天，现在内存是350M左右，比之前的好不少

我去，试用了半天，本来想问问占用150M是不是有点多了，没想到。。。。

**Comment by Skyxim** [comment]
@yiiyahui http://${controller-api}/debug/pprof/heap?raw=true

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
