### ISSUE TITLE
docker hub的image不能运行

### ISSUE THREAD

**Issue by jwfang** [MetaCubeX/mihomo#463]
/ # /clash
/bin/sh: /clash: not found
/ # ldd /clash
        /lib/ld-linux-aarch64.so.1 (0x7fa66c0000)
Error loading shared library libresolv.so.2: No such file or directory (needed by /clash)
        libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0x7fa66c0000)
        libc.so.6 => /lib/ld-linux-aarch64.so.1 (0x7fa66c0000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /clash)
Error relocating /clash: __printf_chk: symbol not found
Error relocating /clash: __vfprintf_chk: symbol not found
Error relocating /clash: __fprintf_chk: symbol not found
Error relocating /clash: __res_search: symbol not found
/ # uname -a
Linux 9a5620f5f2c4 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 Linux
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.2
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
