### ISSUE TITLE
请问日志中的这种现象是什么原因出现的。

### ISSUE THREAD

**Issue by CStyleIO** [MetaCubeX/mihomo#468]
# Capture on 2023-03-26 19:46:22.043
19:46:24.029 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 127.0.0.1:34542(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:25.649 Warning: [TCP] dial DIRECT (match Process/com.microsoft.skydrive) 172.19.0.1:34592(com.microsoft.skydrive) --> 172.217.163.42:443 error: connect failed: dial tcp 172.217.163.42:443: i/o timeout | connect failed: no ip address
19:46:26.105 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 127.0.0.1:34554(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:29.041 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 172.19.0.1:48346(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:30.661 Warning: [TCP] dial DIRECT (match Process/com.microsoft.skydrive) 172.19.0.1:49942(com.microsoft.skydrive) --> 142.251.43.10:443 error: connect failed: dial tcp 142.251.43.10:443: i/o timeout | connect failed: no ip address
19:46:31.122 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 172.19.0.1:48354(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:34.055 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 127.0.0.1:34570(com.zhihu.android) --> 106.11.61.135:443 error: connect failed: dial tcp 106.11.61.135:443: i/o timeout | connect failed: no ip address
19:46:35.836    Info: [TCP] 172.19.0.1:36044(com.facebook.services) --> 31.13.67.33:443 match Process(com.facebook.services) using US
19:46:36.142 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 127.0.0.1:34576(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:39.063 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 172.19.0.1:45600(com.zhihu.android) --> 106.11.61.135:443 error: connect failed: dial tcp 106.11.61.135:443: i/o timeout | connect failed: no ip address
19:46:41.153 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 172.19.0.1:48388(com.zhihu.android) --> amdcopen.m.taobao.com:443 error: connect failed: dial tcp 203.119.214.17:443: i/o timeout | connect failed: no ip address
19:46:46.170 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 127.0.0.1:34616(com.zhihu.android) --> 106.11.61.135:443 error: connect failed: dial tcp 106.11.61.135:443: i/o timeout | connect failed: no ip address
19:46:50.229    Info: [TCP] 127.0.0.1:34624(com.einnovation.temu) --> us.pftk.temu.com:443 match DomainSuffix(temu.com) using US
19:46:51.183 Warning: [TCP] dial DIRECT (match Process/com.zhihu.android) 172.19.0.1:45640(com.zhihu.android) --> 106.11.61.135:443 error: connect failed: dial tcp 106.11.61.135:443: i/o timeout | connect failed: no ip address

是我设置的DNS问题？规则问题？还是clash.meta目前的正常情况。

**Comment by ArchGuyWu** [comment]
请提供你的clash 配置

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
