### ISSUE TITLE
[Feature] geo database 自动更新

### ISSUE THREAD

**Issue by lhbdhr** [MetaCubeX/mihomo#520]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望能支持geo database自动更新，我看之前有人提过issue，但是最后不了了之。
这个功能还挺好的，我建议可以放到Todo List嘛，
先解决优先级高的，这个问题优先级低，但是说不定谁有空就做了呢？

**Comment by lhbdhr** [comment]
另外，能否支持geo更新走proxy？

**Comment by mirthfulLee** [comment]
看[官方wiki](https://wiki.metacubex.one/en/config/general/#auto-update-geo), 这个功能目前应该是已经实现了. 这个issue可以close了.
