### ISSUE TITLE
请问下自定义嗅探要怎么设置

### ISSUE THREAD

**Issue by spirytuslove** [MetaCubeX/mihomo#54]
openclash用了meta内核ps5的nat检测一直失败 用的是混合模式 之前不用meta内核没有这个问题 请问下要怎么设置自定义嗅探让ps5nat能正常

**Comment by MetaCubeX** [comment]
原版内核检测是否正常？ 协议是否支持？

**Comment by spirytuslove** [comment]
原版内核fakeip下用的tun混合模式 ps5nat能识别出类型2 换了meta内核就不行 是不是我得设置下自定义嗅探 如果需要 请问下要怎么设置

**Comment by Skyxim** [comment]
@spirytuslove 没需求关系嗅探

**Comment by spirytuslove** [comment]
> 

那就很奇怪啊 我openclash之前tun混合是可以正常识别nat类型的 用meta内核就检测失败

**Comment by MetaCubeX** [comment]
@spirytuslove 关闭嗅探呢？

**Comment by Skyxim** [comment]
@spirytuslove 完全没有nat？ udp还是通的么

**Comment by spirytuslove** [comment]
我晚上回去试试关闭嗅探再反馈  感谢

**Comment by spirytuslove** [comment]
我试了下关了嗅探也还是nat检测失败 只有关了meta内核用原版内核可以检测出类型2

**Comment by Skyxim** [comment]
![45CBEA37-D751-4B08-BDC5-C38BF045BDF6](https://user-images.githubusercontent.com/70276018/167321370-b2d33b59-b764-418f-b240-aad35a1eafe8.jpeg)
![3826A272-13AC-4995-A3F8-84F6D676CAC6](https://user-images.githubusercontent.com/70276018/167321373-3938f58c-3316-4718-a283-3e8b11992809.jpeg)

分别是直连和trojan的udp 运行在tun gv下 开了嗅探

**Comment by MetaCubeX** [comment]
> 我试了下关了嗅探也还是nat检测失败 只有关了meta内核用原版内核可以检测出类型2

具体用的什么协议？

**Comment by Skyxim** [comment]
@MetaCubeX 具体协议，使用的tun还是tproxy

**Comment by spirytuslove** [comment]
![CFADC622-C896-48B0-8E0B-85B21F613831](https://user-images.githubusercontent.com/64483414/168403599-5033878f-e5be-4e55-b153-ad55d2f6c22a.png)
用的这个tun混合

**Comment by spirytuslove** [comment]
节点用ss和vmess都试过了 开meta就nat检测失败

**Comment by Skyxim** [comment]
@spirytuslove 切换成redir+兼容试试

**Comment by spirytuslove** [comment]
刚切换到redir兼容模式和tun混合都试了下 还是都失败

**Comment by Skyxim** [comment]
redir-host+兼容，有空我测试下其他的，你说的失败的udp完全不同，还是nat type不对
<img width="363" alt="image" src="https://user-images.githubusercontent.com/70276018/168404620-e035017c-3593-4ae1-8c43-098dc2fa0a86.png">
![telegram-cloud-document-5-6338944920815928930](https://user-images.githubusercontent.com/70276018/168404627-0d9b9c38-9b3b-4b62-8621-cdc417f6d545.jpg)

**Comment by Skyxim** [comment]
@Skyxim 还有测试过直连没

**Comment by spirytuslove** [comment]
直连中午我试试 nat类型失败我是用的ps5里面自带的检测 检测不出来类型2 检测显示就是nat失败 不用meta用原版内核是直接能检测出类型2

**Comment by spirytuslove** [comment]
测试了下直连依然nat检测失败
