### ISSUE TITLE
[Feature] 控制ipv6解析结果过滤

### ISSUE THREAD

**Issue by makaspacex** [MetaCubeX/mihomo#551]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前ipv6的dns过滤采用一刀切的形式，阻止了所有ipv6解析，没有细致的过滤功能（可能是我不会用），也应该是有解决方案的比如使用自己搭建的dns或者自己写dns服务器（如python），但这样不能很方便的跨设备和单设备使用。很多时候ipv6的解析结果依然是需要的，全部阻止会导致一些依赖ipv6的应用功能异常，也没办法针对ipv6进行网络优化。流量分流代理并不能解决问题，因为很多节点没有ipv6，代理仅ipv6站点或指定的ipv6地址时会出问题。

曾探索过配合adguardhome和smartdns，均不能很好的控制ipv6解析结果的过滤，比如离开局域网后就不能使用了，每个场景重复配置。所以还是需要clash直接支持，不受使用场景的限制，也能降低使用门槛。

尚不清楚这个功能的难度和工作量，想贡献pr，奈何go不熟悉，水平也太菜，希望社区能考虑这个feature。

### Possible Solution

可能的比较好的ipv6过滤解决方案是：
1、增加ipv6过滤的白名单和黑名单模式
2、规则过滤使用现有的dns规则功能即可

**Comment by xianren78** [comment]
smartdns可以完美解决这个问题，要把smartdns的上游设为openclash 127.0.0.1:7874
