### ISSUE TITLE
[Feature] 支持 SSH Outbound

### ISSUE THREAD

**Issue by lyc8503** [MetaCubeX/mihomo#554]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

能否实现 SSH 出站，这样可以方便的连接到服务器所在的内网？

类似 sing-box 这里的表现 https://sing-box.sagernet.org/configuration/outbound/ssh/

**Comment by kkksa528** [comment]
好东西，虽然稍微有点鸡肋但可以有，绝对用得到

**Comment by chenzaichun** [comment]
期待这个功能，这样就不用手动启动一个ssh了。

**Comment by xaotag** [comment]
有点意思

**Comment by lxr2** [comment]
这个超有用的！特别是远程办公的时候！！

**Comment by xaotag** [comment]
> 期待这个功能，这样就不用手动启动一个ssh了。

问一下兄弟，这个功能有什么用吗？

**Comment by chenzaichun** [comment]
> > 期待这个功能，这样就不用手动启动一个ssh了。
> 
> 问一下兄弟，这个功能有什么用吗？

比如在其他服务有ip白名单的情况下（自己的本地公网ip经常换），通过服务器上的ssh直接forward过去。
