### ISSUE TITLE
[Feature] 让 `PROCESS-PATH` 允许部分匹配

### ISSUE THREAD

**Issue by tzfljuv** [MetaCubeX/mihomo#592]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

`PROCESS-PATH` 需要使用进程的完整路径。有时候一个应用程序包含很多不同的可执行文件，并且这些文件还可能随着程序更新而不断改动。把每个可执行文件全部列入规则非常地低效。

我想要的匹配： 

- `C:\Program Files\Docker\Docker`： 该目录及其所有子目录的所有可执行文件，这包含了：
    - `C:\Program Files\Docker\Docker\Docker Desktop.exe`
    - `C:\Program Files\Docker\Docker\resources\com.docker.backend.exe`

---

另一个问题是：在 Windows 平台， `PROCESS-PATH` 规则需要使用（对部分用户而言难以理解的）真实路径才能匹配成功。

- 例如： **`\Device\HarddiskVolume4`**`\Program Files\...` （匹配成功）

- 用户认为的路径： **`C:`**`\Program Files\...` （匹配失败）

文件系统的真实路径可能会在系统重启之后改变顺序（特征类似于 `/dev/sdX`），不像盘符具有持久性。

这个问题与上面那个问题有关联，因此而放到一起。

### Possible Solution

对于 Windows 路径不能使用盘符这个问题，可以尝试先将盘符解析成真实路径，再进行匹配。

**Comment by lxy35326** [comment]
> `PROCESS-PATH` 规则需要使用（对部分用户而言难以理解的）真实路径

请问这个真实路径是什么？怎样能得到呢？

**Comment by Accademia** [comment]
希望PROCESS-PATH至少能和windows下的环境变量配合，现在很多程序都再装在如下路径：

C:\Users\用户名\AppData\Local\Programs
C:\Users\用户名\AppData\Roaming

尤其是以中国大陆各种流氓公司的程序居多（估计是为了方便：热升级、热更新），比如：微云、百度网盘、阿里云盘、城通网盘、115网盘，等等。这些软件，为了流氓热更新，滥用Windows开发规范，不让自己的程序安装在Program Files文件夹。

所以，支持 环境变量，势在必行

**Comment by wwqgtxx** [comment]
- Windows路径不能使用盘符问题已经修复https://github.com/MetaCubeX/mihomo/commit/1b527fd494e8b2ad713ea0afcf9af485d452d61c https://github.com/MetaCubeX/mihomo/commit/0ab73a9beb7a5700ffa8e5b2c8188bb4bb8c8e3f
- 最新alpha已经增加正则匹配规则 https://github.com/MetaCubeX/mihomo/commit/1bc3c16b5938706fb8e5c576ecf62999fbd8ffc2
