### ISSUE TITLE
[Feature] SRC-GEOIP

### ISSUE THREAD

**Issue by sleepm** [MetaCubeX/mihomo#635]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

监听入站规则用的到
自己手动修改
/rules/parser.go
/rules/common/geoip.go
编译了下，能成
我 go 水平有限，自己够用，就不献丑了。。

**Comment by xishang0128** [comment]
已添加,该issues将被关闭
