### ISSUE TITLE
[Feature] Timeout for URL-Test

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/mihomo#663]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Hello
Please add option to have a timeout for URL-Test groups
currently CM will wait for a config for 1 minute or more even when the config is dead
thanks

**Comment by leftcausedit** [comment]
It will wait 65535ms. I think it's not necessary, 5000ms seems enough.
