### ISSUE TITLE
[Feature] override_android_vpn

### ISSUE THREAD

**Issue by hour-keeper** [MetaCubeX/mihomo#669]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望能添加类似 sing-tun 的 override_android_vpn 一样的功能，可以实现 adguard 的 vpn 模式与 clash-meta tun 共存

**Comment by Benyamin-Tehrani** [comment]
It seems that OverrideAndroidVPN is enabled here https://github.com/MetaCubeX/mihomo/blob/3676d1b79fe8567c9375d3e812f84eb683c8f77d/listener/sing_tun/server.go#L281 in default.

**Comment by hour-keeper** [comment]
> It seems that OverrideAndroidVPN is enabled here
> 
> https://github.com/MetaCubeX/mihomo/blob/3676d1b79fe8567c9375d3e812f84eb683c8f77d/listener/sing_tun/server.go#L281
> in default.

Thank you.
