### ISSUE TITLE
长连接 keep alive 导致持续耗电问题

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/mihomo#715]
在 Openclash 下面看到一个 **长连接 keep alive** 导致耗电增加的问题，希望开发者关注一下，感谢！

原 issue 有更多 debug 信息：https://github.com/vernesong/OpenClash/issues/2614

> clash meta 内核会每隔 30s 分别向客户端和服务端发送 keep alive 包，对应于这里的代码：
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/adapter/outbound/util.go#L25C3-L25C3
> 
> ``` go
> func tcpKeepAlive(c net.Conn) {
> 	if tcp, ok := c.(*net.TCPConn); ok {
> 		_ = tcp.SetKeepAlive(true)
> 		_ = tcp.SetKeepAlivePeriod(30 * time.Second)
> 	}
> }
> ```
> 
> clash config 很简单，只有 mixed-port: 7890 一行，重现步骤是本地首先通过 nc 监听 45678 端口，然后再通过 clash socks5 代理连接该端口，我这边观察到的是 30s 一次的 keep alive 包，如图所示：
>
> ![clash-keep-alive-interval](https://user-images.githubusercontent.com/4557341/258353473-ac117216-ab05-4a65-aa82-5906b416502f.png)
> 
> 这些 keep alive 包会不断唤醒手机，我想这应该就是在 Apple Push/Google FCM 等 **长连接** 经过 clash 时，手机会不断耗电的原因。不管规则判定是直连还是通过远程节点连接，只要由 clash 内核发出连接皆会如此。

**Comment by Larvan2** [comment]
https://github.com/golang/go/issues/62254

**Comment by maxfun0** [comment]
fcm为啥不走直连呢

**Comment by yyysuo** [comment]
> 

https://github.com/MetaCubeX/Clash.Meta/commit/73fa79bf3f508159311839dc7e295070180c80da
https://github.com/MetaCubeX/Clash.Meta/commit/1d4af2d92bcae7ec394830e58435ded6454882ef

大佬，您的这2个commit是设置了可配置项目，并默认为15s对吗，我如何在openclash中配置这个长连接的时间？

**Comment by Larvan2** [comment]
参考[此处](https://github.com/MetaCubeX/Clash.Meta/blob/a1eab125ee29cc4d858f454af9200a2f2455240e/docs/config.yaml#L54C24-L54C24)

> > 
> 
> [73fa79b](https://github.com/MetaCubeX/Clash.Meta/commit/73fa79bf3f508159311839dc7e295070180c80da) [1d4af2d](https://github.com/MetaCubeX/Clash.Meta/commit/1d4af2d92bcae7ec394830e58435ded6454882ef)
> 
> 如何在openclash中配置这个长连接的时间？

**Comment by LovelyToaster** [comment]
> 参考[此处](https://github.com/MetaCubeX/Clash.Meta/blob/a1eab125ee29cc4d858f454af9200a2f2455240e/docs/config.yaml#L54C24-L54C24)
> 
> > > 
> > 
> > 
> > [73fa79b](https://github.com/MetaCubeX/Clash.Meta/commit/73fa79bf3f508159311839dc7e295070180c80da) [1d4af2d](https://github.com/MetaCubeX/Clash.Meta/commit/1d4af2d92bcae7ec394830e58435ded6454882ef)
> > 如何在openclash中配置这个长连接的时间？

你好，我这样配置后似乎不起作用，抓包测试后依旧是15s
![image](https://github.com/MetaCubeX/Clash.Meta/assets/92214385/481acbfa-b410-40ed-a111-11055f2ad38c)
![image](https://github.com/MetaCubeX/Clash.Meta/assets/92214385/b23c9a45-512a-44b7-9861-5b96331870c2)

**Comment by LovelyToaster** [comment]
> > 参考[此处](https://github.com/MetaCubeX/Clash.Meta/blob/a1eab125ee29cc4d858f454af9200a2f2455240e/docs/config.yaml#L54C24-L54C24)
> > > > 
> > > 
> > > 
> > > [73fa79b](https://github.com/MetaCubeX/Clash.Meta/commit/73fa79bf3f508159311839dc7e295070180c80da) [1d4af2d](https://github.com/MetaCubeX/Clash.Meta/commit/1d4af2d92bcae7ec394830e58435ded6454882ef)
> > > 如何在openclash中配置这个长连接的时间？
> 
> 你好，我这样配置后似乎不起作用，抓包测试后依旧是15s ![image](https://user-images.githubusercontent.com/92214385/270224722-481acbfa-b410-40ed-a111-11055f2ad38c.png) ![image](https://user-images.githubusercontent.com/92214385/270224833-b23c9a45-512a-44b7-9861-5b96331870c2.png)

但是我直接修改这里再编译却正常😂
![image](https://github.com/MetaCubeX/Clash.Meta/assets/92214385/873281cf-d7a6-48cf-bc30-66122902d4fc)

**Comment by Larvan2** [comment]
试试[这个提交](https://github.com/MetaCubeX/Clash.Meta/commit/8929432879254378ed49b4a76f079b148cea6a9d)编译出来的行不行

**Comment by LovelyToaster** [comment]
> @LovelyToaster 试试[这个提交](https://github.com/MetaCubeX/Clash.Meta/commit/fdd327d58da49b0bf21b0908bc7e3d475eae63a3)编译出来的行不行

现在可以了，谢谢

**Comment by stevejohnson7** [comment]
此问题看起来已解决？如果没有需要进一步改进的话可以close

**Comment by Larvan2** [comment]
这个issue可以用于跟踪go官方库的更新，以便更进新api使用，暂不需要关闭

**Comment by Vulcankta** [comment]
[net: add KeepAliveConfig and implement SetKeepAliveConfig](https://github.com/golang/go/commit/d42cd452dcca76819dd385a7775f8453d6255dbd)
有計劃跟進嗎?

**Comment by zhoulj82** [comment]
> [net: add KeepAliveConfig and implement SetKeepAliveConfig](https://github.com/golang/go/commit/d42cd452dcca76819dd385a7775f8453d6255dbd) 有計劃跟進嗎?

go1.23 版本才会有这个更新，估计今年 8 月才能发布 1.23 吧。

**Comment by HydroH** [comment]
Go 1.23已更新，请问是否有计划跟进？

**Comment by ZhuangJiayu** [comment]
所以当前1.19.4版本内核的TCP keep alive interval这个字段还需要做配置吗？如果需要的话具体怎么配比较合适呢？抱歉重开此问题，恳请各位大佬不吝赐教
