### ISSUE TITLE
openclash使用最新版本meta内核,内网的规则设为直连，此时，内网ssh无法访问，显示连接被关闭。

### ISSUE THREAD

**Issue by hiyuxiang** [MetaCubeX/mihomo#75]
openclash使用最新版本meta内核,内网的规则设为直连，此时，内网ssh无法访问，显示连接被关闭，上一版本meta内核时没问题。

**Comment by kunish** [comment]
过去这么久了，还能复现么

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
