### ISSUE TITLE
[Feature] bind-address 支持绑定到多个地址 

### ISSUE THREAD

**Issue by loveqianool** [MetaCubeX/mihomo#775]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望能 bind-address: "192.168.1.1/24, 10.0.0.1/24"

**Comment by fillpit** [comment]
设置为 bind-address: "*" 不就好了嘛

**Comment by LovelyToaster** [comment]
防火墙禁止外部连接不就行了
