### ISSUE TITLE
clash meta 在和openvpn在mac下一起使用时断联

### ISSUE THREAD

**Issue by sunnoy** [MetaCubeX/mihomo#800]
macos下meta是经过了什么处理么使用同样使用clash客户端在使用openvpn的情况下测试情况如下：
使用 clashX pro 然后使用vpn客户端 tunnelblick 一段时间后出现重连日志为
Inactivity timeout (--ping-restart), restarting

使用clashX meta 客户端就不会出现重连，目前已经切换为该客户端

想知道meta做了什么处理？

找了下代码针对icmp 没有发现特别的处理呢？

![WX20231016-174602@2x](https://github.com/MetaCubeX/Clash.Meta/assets/19342276/cc0a6871-b190-4366-bbf2-b1126ca01088)

**Comment by laggardkernel** [comment]
以下结果基于 enhanced-mode tun 模式使用情况。

使用 fake-ip 模式就会断联，不管是 clash-meta 还是 clash-premium 都有这种情况。

使用 redir-host 时，需要指定 interface-name 为 openvpn utun 的 DIRECT，而不是直接 DIRECT。（fake-ip 下可以直接 DIRECT。)

```yaml
- name: UTUN3
  type: select
  interface-name: utun3
  proxies:
  - DIRECT
```

redir-host + DIRECT (without interface-name) 会报错 dial tcp {ip}: io timeout.

clash-premium 使用 redir-host + interface-name DIRECT 后一切正常。但是 clash-meta 使用 redir-host + interface-name DIRECT 会报错 interface-name not found.

目前 openvpn tun, clash tun 共存的话，只能选 clash-premium + redir-host.


---

OpenVPN Inactivity timeout 原因未知。一开始我以为和 DNS 有关，因为我的配置 `remote host port` host DNS 解析 ttl 是 600，正好符合我遇到的每 10m openvpn 无响应重连。但是

1. clash-(meta/premium) debug 日志中看到了 10m 后 DNS 解析成功有返回结果
2. 把 `remote host port` 换成 `remote ip port` 仍旧每 10m 断联一次。

所以感觉又不是 DNS 解析的问题。

**Comment by sunnoy** [comment]
我的一直是 fake ip 加 tun 不断 奇怪

**Comment by Ssiswent** [comment]
你好，请问你在macOS上是如何使用服务的呢，我看wiki似乎只有Linux的运行教程
https://wiki.metacubex.one/startup/service/

**Comment by laggardkernel** [comment]
@Ssiswent 利用 macOS launchd 启动服务，由于需要 root 权限运行才能开启 tun，需要把定义的 plist 放到 `/Library/LaunchDaemons/`.

launchctl 启动服务，设置 DNS 192.18.0.2（实际上是 clash 默认 hijack-dns 192.18.0.2:53 的请求），设置系统代理。

使用 Homebrew 的话，clash 启动可以参考我的 homebrew tap. 但由于需要 root 启动，每次启动后要运行 brew fix-perm all 修正 Homebrew 文件权限。（如果你不明白这是为什么，请不要使用我的 tap 启动 clash，以免导致 Homebrew 报错无法使用。而是自己手写 launchd plist）。

<details>

<summary>Homebrew 启动 clash</summary>

```sh
brew tap laggardkernel/tap
brew install clash-meta-bin
# start service
sudo brew services start clash-meta-bin; brew fix-prem all
# stop
sudo brew services stop clash-meta-bin; brew fix-perm all
```

</details>

<details>

<summary>DNS, Proxy 等设置代码</summary>

```sh
# setup dns, proxy
PROXY_BYPASS_DOMAINS=(
  "127.0.0.0/8"
  "192.168.0.0/16"
  "10.0.0.0/8"
  "172.16.0.0/12"
  "100.64.0.0/10"
  "localhost"
  "*.lan"
  "*.local"
  "*.crashlytics.com"
  "www.baidu.com"
  "yunbusiness.ccb.com"
  "*.edu.cn"
  "*.evernote.com"
  "*.yinxiang.com"
)
networksetup -setdnsservers "Wi-Fi" 198.18.0.2
networksetup -setsearchdomains "Wi-Fi" "lan"
networksetup -setsocksfirewallproxy "Wi-Fi" "127.0.0.1" "8889"
networksetup -setproxybypassdomains "Wi-Fi" "${PROXY_BYPASS_DOMAINS[@]}"
networksetup -setsocksfirewallproxystate "Wi-Fi" "on"

# unset
networksetup -setdnsservers "Wi-Fi" 114.114.114.114
networksetup -setsearchdomains "Wi-Fi" "lan"
networksetup -setproxybypassdomains "Wi-Fi" ""
networksetup -setsocksfirewallproxystate "Wi-Fi" "off"
```

</details>
