### ISSUE TITLE
[Feature] A socks5 port to bypass traffic like DIRECT mode? 

### ISSUE THREAD

**Issue by Azadzadeh** [MetaCubeX/mihomo#816]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Assuming we are using TUN mode + hijacked DNS. In this mode, all traffic is controlled by Clash.Meta.
we can bypass traffic to a domain or ip by setting a rule and using DIRECT.

my question: how to expose a certain port so all traffic going through it is bypassed like DIRECT? so i mean, in this TUN mode, all traffic is handled by Rule. I want a socks5 port that always behaves like DIRECT.

**Comment by xishang0128** [comment]
https://github.com/MetaCubeX/Clash.Meta/blob/79626189f33631dc6bcd7d6503e2b2a5ff509453/docs/config.yaml#L889 `proxy: DIRECT`

**Comment by xishang0128** [comment]
@Azadzadeh Yes, clash meta can act as a proxy server for some protocols

**Comment by xishang0128** [comment]
> @Azadzadeh Yes, clash meta can act as a proxy server for some protocols

You can refer to https://wiki.metacubex.one/config/inbound/ and https://wiki.metacubex.one/config/inbound/hysteria2, which are still being improved and are not available in English.

**Comment by xishang0128** [comment]
> Also, there is an ambiguity about [inbound TUN](https://github.com/MetaCubeX/Clash.Meta/blob/79626189f33631dc6bcd7d6503e2b2a5ff509453/docs/config.yaml#L980) and general [top-level TUN](https://github.com/MetaCubeX/Clash.Meta/blob/79626189f33631dc6bcd7d6503e2b2a5ff509453/docs/config.yaml#L91). What does setting them both, mean in practice?
They are equivalent, just set one of them

**Comment by xishang0128** [comment]
> @xishang0128 and upstream Clash doesn't support this "acting as proxy server in server-side"? https://dreamacro.github.io/clash/configuration/inbound.html#inbound


The upstream only supports socks/http and does not support the encrypted proxy protocol. socks/http is not safe on public networks.

**Comment by xishang0128** [comment]
@Azadzadeh No need to worry about this. If security issues arise, clash.meta will promptly update the protocol. If it's a minor issue, clash.meta may not be updated soon, or it may not be updated at all (clash.meta may not be affected by minor issues that occur upstream)

**Comment by stevejohnson7** [comment]
Solved. So close it
