### ISSUE TITLE
安卓端绕过内网地址规则不工作

### ISSUE THREAD

**Issue by xxooxxooxx** [MetaCubeX/mihomo#830]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

安卓端（13），绕过内网地址规则不工作

rules:
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  -

**Comment by Skyxim** [comment]
@xxooxxooxx 请提供日志记录，是否匹配成功，抑或是最终匹配了什么

**Comment by xxooxxooxx** [comment]
[TCP] 172.19.0.1:46072(pl.solidexplorer2) --> desktop-o821117:445 match Match using auto[PROXY3]

solidexplorer 是一个安卓下的文件管理器，配置SMB资源，写的是IP地址，日志里用的主机名，所以没有DIRECT。

**Comment by Skyxim** [comment]
具体为什么得到的是一个 hostname 这就要问你那个软件了，或者其他地方有设置（大概里是个代理软件）
你这个使用了 hostname 如果代理软件查询不到这个 hostname 的 IP 自然会走到最后的 MATCH
你需要保证你配置的上游 DNS 或者 hosts 中存在这个对应关系
