### ISSUE TITLE
无法与原版一样与ADguard共存

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#845]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

原版clash是可以与adguard共存的，而clashmeta，在导入附带用于clash的adguard的DNS时会失败（https://sub.xeton.dev/?config=https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/default_with_clash_adg.yml ）是通过这个API转换的，希望可以适配一下

**Comment by llity** [comment]
> ### Verify steps
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的请求 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related feature request.
> * [x]   我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue.
> 
> ### Description
> 原版clash是可以与adguard共存的，而clashmeta，在导入附带用于clash的adguard的DNS时会失败（[sub.xeton.dev/?config=https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/default_with_clash_adg.yml](https://sub.xeton.dev/?config=https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/default_with_clash_adg.yml) ）是通过这个API转换的，希望可以适配一下
> 
> ### Possible Solution
> _No response_

怎么配置能共存呢？谢谢
