### ISSUE TITLE
[Feature] 支持 域名关键字 通配 和 程序关键字 通配

### ISSUE THREAD

**Issue by maxming2333** [MetaCubeX/mihomo#846]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前有一个强烈的诉求
就是以某个字符串为关键字（比如品牌名称 baidu、ali、163，因为一般品牌都会申请很多相似域名，很多都给企业内网使用），只要命中了，就走对应的 DNS，形如：

以 [minimatch](https://github.com/isaacs/minimatch#minimatch) 形式命名
```yaml
nameserver-policy:
  '*baidu*': ['dhcp://en0', 'dhcp://en1'] # 表示匹配只要域名中含有 baidu 关键字的域名，a.b.c.baidu、a.f.baiduai.cc、a.f.eebaiduai.cc、a.xxbaiduxx.haha.com
  '*.ali*': ['dhcp://en0', 'dhcp://en1'] # 表示匹配包含 .ali 的域名，a.b.c.alibaba.com、a.b.c.alimama.com.cn
```

同理，`PROCESS-NAME` 也需要这种功能
```yaml
rules:
- PROCESS-NAME,foo,Proxy # 只要程序名称包含 foo 这个字符串即可
```

或者使用正则，在加载配置后，直接缓存对应正则对象，这样就不用每次流量进来都需要 new 一次正则对象了，提升域名匹配性能

-----------------

文档：
- glob: https://rgb-24bit.github.io/blog/2018/glob.html
- minimatch: https://github.com/isaacs/minimatch#minimatch

**Comment by Paulgudring** [comment]
Feature 2 will be of great help.

I use a diy rule-set `direct`(classical one, which consists of domain and geo rules) for proxy-direct routing and dns diversion. It works well.

I add wechat mini program (WeChatAppEx.exe) process rule. Most of the website domains it accesses are not covered by geosite, and I don't want dns-resolve. I supposed it conform with the [nameserver-policy usage of rule-set](https://wiki.metacubex.one/config/rules/rule-provider/#rule-set). But it doesn't work. I figured out it is because nameserver-policy usage of classical rule-set is to unfold the domain and geo rules while other rules is unsupported.

Is it possible to implement the feature of supporting more types of rules (port, process) in nameserver-policy? This would help make meta(mihomo, now) the most powerful proxy & dns-resolve tool.

**Comment by Skyxim** [comment]
PROCESS-NAME 是无法实现的，需要获取流量来源程序，一般 DNS 来源皆为系统

**Comment by dycwuxing** [comment]
我之前一直在用ruleset做一些细化的分流，但是1.17开始失效了，你可以试试1.16的

**Comment by Skyxim** [comment]
引入一个 DOMAIN-REGEX 算了，不过的确非常影响性能，分流也能用

**Comment by maxming2333** [comment]
以下规则里面，包含一个 零宽字符，可以看看
```yaml
rules:
- PROCESS-NAME,kkkkk​ Helper,Office
```

**Comment by dycwuxing** [comment]
> ```yaml
> rule-providers
> ```

请问你用的是哪个版本号的核心?1.17吗?

**Comment by dycwuxing** [comment]
> 我是被这段注释启发滴 @dycwuxing https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml#L262-L264

谢谢,这个功能确实很早就支持了,但我自己测试下来,1.17是没生效,如果换成geosite:cn就没问题,所以想和你确认下大概的版本~

2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from tls://1.1.1.1:853 
2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from tls://1.1.1.1:853 
2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from https://1.1.1.1:443/dns-query 
2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from https://1.0.0.1:443/dns-query 
2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from https://1.0.0.1:443/dns-query 
2023-12-04 16:35:58 INFO - [clash]: [37mDEBU[0m[2023-12-04T16:35:58.696764+08:00] [DNS] resolve www.baidu.com from https://1.1.1.1:443/dns-query 



dns:
  nameserver:
  - https://1.1.1.1/dns-query#🐟漏网国外
  - https://1.0.0.1/dns-query#🐟漏网国外
  - tls://1.1.1.1#🐟漏网国外
   nameserver-policy:
    rule-set:ChinaMax_Classical:
    - tls://223.5.5.5:853
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
rule-providers:
   ChinaMax_Classical:
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml
    path: ./rule_provider/clash/ChinaMax_Classical.yaml
    type: http
    behavior: classical
    interval: 3600
    format: yaml
![image](https://github.com/MetaCubeX/mihomo/assets/44988562/ed24cad7-9782-4c59-bd3a-1c3aebc50212)

**Comment by maxming2333** [comment]
> 其实第一个，我已经通过另外的方法实现了，就是使用 `rule-providers`
> 
> config.yaml 内容：
> 
> ```yaml
> dns:
>   nameserver-policy:
>     'rule-set:tencent': ['dhcp://en0', 'dhcp://en1', '10.1.2.3', '10.4.5.6'] # 因为有 rule-set 这个操作，所以可以使用 rule-providers 来实现功能
> 
> rules:
> - RULE-SET,tencent,Office # 这里主要是触发 rule-providers 的下载行为，并且也可以把命中的规则分流到 Office 对应的 proxies 里面
> 
> rule-providers:
>   tencent:
>     type: http
>     behavior: classical
>     url: http://127.0.0.1:8013/tencent.yaml
>     path: ./Rules/tencent
>     interval: 100
> ```
> 
> tencent.yaml 内容：
> 
> ```yaml
> payload:
>   # > Tencent Intranet
>   - DOMAIN-SUFFIX,qq.com
>   - DOMAIN-KEYWORD,qq
>   - DOMAIN-KEYWORD,tencent
> ```
> 
> 但是第二个问题，因为目前 `PROCESS-NAME` 是全匹配，所以确实没有其他替代的方法
> 
> 希望能增加一个 PROCESS-KEYWORD 或者 PROCESS-GLOB 或者 PROCESS-REGEX

@dycwuxing 建议你按照我这种配置，如果没有 Office 的 proxies，可以直接写成 DIRECT
另外大小写尽量统一，rule-providers 的名称，和 rule-providers  path 路径 和 尽量保持一致

**Comment by xishang0128** [comment]
process-name-regex也已经支持了,该issues将被关闭
