### ISSUE TITLE
[Feature] Code of conduct 注意文明

### ISSUE THREAD

**Issue by arkxfly** [MetaCubeX/mihomo#847]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

请问你们有 Code of conduct，你们 telegram 管理组，骂人，提醒他注意文明，结果还把人踢出群。。。

虽然不跟这种人介意，但是对于 clash meta 项目而言，还是需要注意文明的，接收用户的同时，也可能会接收新的贡献者，壮大完善 clash meta。如果不是以此为目的完全可以闭源。

因社区吵架，项目分离的事情不少了。

**Comment by NevadaCities** [comment]
@arkxfly 请具体说明

**Comment by PuerNya** [comment]
@arkxfly 请勿滥用 issue
