### ISSUE TITLE
[Bug] mihomo-darwin-arm64-v1.17.0.gz shows malicious maleware warning on arm Macos

### ISSUE THREAD

**Issue by levihuayuzhang** [MetaCubeX/mihomo#851]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.17.0 darwin arm64 with go1.21.4 Sat Dec  2 11:02:29 UTC 2023 Use tags: with_gvisor

### Mihomo config

```yaml
null
```

### Mihomo log

```shell
null
```

### Description

Thanks for all you guys's great works and it's good to see that you guys are comming back~ However:

`mihomo-darwin-arm64-v1.17.0.gz` shows malicious maleware warning on arm Macos.

And I tried to pull the new version of Mihomo and built from source. The binary release seems not match the source in the git tree:
The source version (Branch Alpha and Meta) is still 1.10.0 and binary version is 1.17.0?

Does that means the mihomo only has releases to public community with binary but not source? Or the source development is not going to be public available from now?

It's quite confused that the corresponding branch does have some resonable git history. But the current release seems not a `'pre-built version directly from source'`, right? And I think just changing the constant may be insufficient to explain the binary.

It may be important to clarify this before the community keeps envolved in (after the new stage of developing since something happened)😊

Thanks again~

**Comment by Larvan2** [comment]
> Does that means the mihomo only has releases to public community with binary but not source?

No, the version you saw from your built is cause by this:
https://github.com/MetaCubeX/mihomo/blob/4949136c6d3db450ce772a4b24d66fcb981c44af/constant/version.go#L5

The binary version is set when [make](https://github.com/MetaCubeX/mihomo/blob/Alpha/Makefile)

**Comment by levihuayuzhang** [comment]
I see, thanks for you guys reply.
Cheers~
