### ISSUE TITLE
[Feature] 建议增加 tracing

### ISSUE THREAD

**Issue by Wanderingkang** [MetaCubeX/mihomo#858]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

 profile:
  tracing: true 

建议增加clash tracing，这个很好用

**Comment by llity** [comment]
希望有这个功能。
