### ISSUE TITLE
1.17.0版本不在支持Clash For Windows了吗 替换之后显示未启动核心

### ISSUE THREAD

**Issue by baiyigumeng** [MetaCubeX/mihomo#862]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

1.17.0版本不在支持Clash For Windows了吗 替换之后显示无法连接到核心
![cfw](https://github.com/MetaCubeX/mihomo/assets/86778695/75528d18-0b3a-4cf9-bf3a-11545ebed234)

**Comment by xishang0128** [comment]
@baiyigumeng 不提供对cfw的任何支持,请关闭这个issues

**Comment by CNM-xishang0128-NMSL** [comment]
@xishang0128 操你妈了个臭逼什么问题都解决不了只会在这里狗叫

**Comment by wilsonjor** [comment]
用clash.verge
