### ISSUE TITLE
请求完善文档

### ISSUE THREAD

**Issue by sf467** [MetaCubeX/mihomo#869]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

现有的文档缺少对诸多新特性的描述与示范，为使用带来不便，
如负载均衡策略组的 sticky-sessions 模式，流量隧道tunnels字段的作用及其与链式代理的区别，等等

**Comment by xiandu999-yu** [comment]
还有前置需要的库...我cgo用不了😂

**Comment by xishang0128** [comment]
@xiandu999-yu 用cgo之前建议先了解一下cgo是什么,需要什么

**Comment by xiandu999-yu** [comment]
> @xiandu999-yu 用cgo之前建议先了解一下cgo是什么,需要什么

求个入口先？
