### ISSUE TITLE
[Feature] Support LoongArch

### ISSUE THREAD

**Issue by ziqi-cn** [MetaCubeX/mihomo#870]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

支持龙芯龙架构

### Possible Solution

修改`component/ebpf/byteorder/byteorder_littleendian.go`，`component/ebpf/redir/bpf_bpfel.go`，`component/ebpf/tc/bpf_bpfel.go`这几个文件，加入loong64即可编译成功
```
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64 || loong64
```
这几个文件似乎是自动生成的，是如何生成的，应该如何修改比较妥当？

**Comment by Skyxim** [comment]
@ziqi-cn 由于无测试环境，如果需要，且有能力欢迎 PR

**Comment by LinuxResearcher** [comment]
我也想要！

**Comment by xishang0128** [comment]
已支持,该issues将被关闭
