### ISSUE TITLE
[Feature] 请将日志中带ANSI转义码的时间戳变成可选项

### ISSUE THREAD

**Issue by AXEVO** [MetaCubeX/mihomo#879]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

更新1.17.0内核之后输出的日志上都带了类似 [36mINFO[0m 这样的ANSI 转义码，希望把这个功能（包括后面的时间戳）做成可选项目，因为有些使用场景下这些日志是会被放在文件里由别的程序展示而不是输出到控制台上，这时候这些符号就会让日志变得很乱，可读性变差。
如图所示，颜色和时间等显示已经由其他的函数实现，输出到日志文件里，同时这个“clash控制器”app会显示日志。
![image](https://github.com/MetaCubeX/mihomo/assets/115725008/282d2a56-ee2d-4ab2-a631-36020fe36a5d)
在旧版本内核中蓝色[info]后面会直接跟着日志内容，没有那个转义码，新版本变得很乱了

另外，已经尝试自己使用sed命令去掉这个ansi转义码时间戳但是没有用，可能是因为其中有特殊符号。
使用命令：
sed -i 's/.*00] //g' ${Clash_run_path}/start.log

### Possible Solution

配置文件里面加一条，控制是否显示时间戳，是否显示ANSI转义码

**Comment by AXEVO** [comment]
另外我还尝试了一下对内核日志不使用log函数直接输出到文件由这个app读取，但是很遗憾，还是显示不了正确的颜色，只能显示转义符本身

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/d1539cbf-c7a8-4384-839e-ea3a6aaede46)
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/a340c6f8-72a4-443b-ae78-18a05e071c64)
可以去,你处理方式的问题,另外这应该由三方app去适配,是三方使用了meta不是meta去使用它

**Comment by AXEVO** [comment]
> ![image](https://private-user-images.githubusercontent.com/95160953/288321599-d1539cbf-c7a8-4384-839e-ea3a6aaede46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDc4ODksIm5iZiI6MTcwMTg0NzU4OSwicGF0aCI6Ii85NTE2MDk1My8yODgzMjE1OTktZDE1MzljYmYtYzdhOC00Mzg0LTgzOWUtZWEzYTZhYWVkZTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3MjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNWZiMTliY2RmYWRmNzQyZTNhMzYzZTI1MTI5MTY0ODgyMjk5NmM0ZDUwZGI5NGRiOTRjZmJiMDczMTE2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mECpwe4kdLp-gk2LvOmoOSf_rKDQKaEbv4hjoIpmWD4) ![image](https://private-user-images.githubusercontent.com/95160953/288321683-a340c6f8-72a4-443b-ae78-18a05e071c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDc4ODksIm5iZiI6MTcwMTg0NzU4OSwicGF0aCI6Ii85NTE2MDk1My8yODgzMjE2ODMtYTM0MGM2ZjgtNzJhNC00NDNiLWFlNzgtMThhMDVlMDcxYzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3MjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNTY1NmM2MTEyMjA3Zjk2OWJjMjkxODI4YjY3NWNhZWM2NzliMjk1NTkyMjUzZDY5ZGVmMTk3MTdjOWNhNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VTMVzAMTKZf3cbW1dwf6_5gv2IaU3nWannyCDm1TIno) 可以去,你处理方式的问题,另外这应该由三方app去适配,是三方使用了meta不是meta去使用它

感谢回复，现在换成   sed 's/.*Z] //g' -i ${Clash_run_path}/start.log   这个命令完美解决，不知道为什么我的时间戳是以 Z] 结尾而不是 00]，比如  [36mINFO[0m[2023-12-05T10:35:16.958919448Z]

**Comment by xishang0128** [comment]
@AXEVO 你终端给的时间格式不同)

**Comment by wwqgtxx** [comment]
fixed in: https://github.com/MetaCubeX/mihomo/commit/9729c2e440f5a288eaea4d364786d0ebddf6d054
