### ISSUE TITLE
[Feature] 开启 TUN 和 DNS 劫持时将物理网卡DNS设置为TUN 的 192.18.0.2

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/mihomo#881]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在Windows下测试了可以解决TUN的DNS泄露问题，请求添加配置选项

**Comment by Skyxim** [comment]
推荐使用脚本之类工具实现，一般由 GUI 实现其功能，内核直接做会有过大的侵入性，并且实现方式也可能不大好

**Comment by Brbrbr1995** [comment]
@limitwhy https://github.com/MetaCubeX/mihomo/issues/859

**Comment by Brbrbr1995** [comment]
> 推荐使用脚本之类工具实现，一般由 GUI 实现其功能，内核直接做会有过大的侵入性，并且实现方式也可能不大好
我.bat里写了内核启动之前更改dns,但是没法在退出后恢复,如果能由内核控制更方便吧

**Comment by Skyxim** [comment]
> > 推荐使用脚本之类工具实现，一般由 GUI 实现其功能，内核直接做会有过大的侵入性，并且实现方式也可能不大好
> 
> 我.bat里写了内核启动之前更改dns,但是没法在退出后恢复,如果能由内核控制更方便吧

巧了这也是内核没法直接做的东西

**Comment by gg4924** [comment]
我让clash的dns监听53端口，然后将物理网卡的dns设置成 127.0.0.1，ipv6设置成 ::1，没有dns泄露问题。

**Comment by iKun10001** [comment]
巧了 这就是GUI做比较合适的事情
