### ISSUE TITLE
[Feature] 想问一下Clash Meta for Android项目现在不更新内核了吗？

### ISSUE THREAD

**Issue by ForestL18** [MetaCubeX/mihomo#884]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

前两天看到meta内核已经更新到1.17了，但是Clash Meta for Android项目并没有同步源码。
从issue中看到了之前有大佬设置了[自动更新Clash Meta for Android内核的actions](https://github.com/MetaCubeX/mihomo/issues/799)，现在Clash Meta for Android仓库是由于被archive了所以不能自动更新最新内核了吗？

由于只有最新的内核才支持`include-all-providers`这个很方便的参数，所以想问下有没有什么解决方法啊

**Comment by zwyyy456** [comment]
同问。。。也是因为 include-all-providers
