### ISSUE TITLE
[Bug] 多个逻辑规则嵌套时，括号匹配似乎有问题

### ISSUE THREAD

**Issue by xkww3n** [MetaCubeX/mihomo#898]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.17.0 windows amd64 with go1.21.4 Sun Dec  3 01:01:52 UTC 2023 Use tags: with_gvisor

### Mihomo config

```yaml
rules:
- AND,((PROCESS-NAME,qbittorrent.exe),(NOT,(OR,((DOMAIN-KEYWORD,dht),(DOMAIN-KEYWORD,router))))),DIRECT
```

### Mihomo log

```shell
config error: rules[1] [AND,((PROCESS-NAME,qbittorrent.exe),(NOT,(OR,((DOMAIN-KEYWORD,dht),(DOMAIN-KEYWORD,router))))),DIRECT] error: unsupported rule type (DOMAIN-KEYWORD
```

### Description

使用上述嵌套逻辑规则时，核心无法启动。

**Comment by ccmuyuu** [comment]
@xkww3n 括号打少了

**Comment by xkww3n** [comment]
> @xkww3n 括号打少了

没有吧，我检查过好几次了

![图片](https://github.com/MetaCubeX/mihomo/assets/30206355/5c7f8146-d60a-44ee-b8e8-5851ae81f10e)

**Comment by ccmuyuu** [comment]
@xkww3n 你再仔细看看wiki not是怎么写的

**Comment by xkww3n** [comment]
> @xkww3n 你再仔细看看wiki not是怎么写的

好吧，是我没看仔细，感谢
