### ISSUE TITLE
[Bug] snell v4 请求支持

### ISSUE THREAD

**Issue by LevineWoo** [MetaCubeX/mihomo#902]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

9fc1fc4

### What OS are you seeing the problem on?

Windows

### Mihomo config

```yaml
- name: "snell"
    type: snell
    server: 111.111.111.111
    port: 12345
    psk: elhAbGZojxxxxxxxx04jh4GnewcNB
```

### Description

snell v4版本不支持
服务端提示：snell-server[1623]: 2023-12-12 06:16:49.717931 [server_tunnel-83] <WARN> Decryption failed, from: 222.222.222.222

**Comment by xishang0128** [comment]
@LevineWoo snell是闭源的,支持不了,老刘也不让反编译

**Comment by LevineWoo** [comment]
> @LevineWoo snell是闭源的,支持不了,老刘也不让反编译

这样。。谢谢哈。
