### ISSUE TITLE
编写[Feature] 

### ISSUE THREAD

**Issue by ldh1983** [MetaCubeX/mihomo#903]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

自建节点部分，换了vps后，需要重新命名节点名称。然后就要到每个代理组里改一下名称。可否像include-all-providers一样添加一个include-all-proxies？谢谢。

**Comment by ccmuyuu** [comment]
@ldh1983 那为什么不直接写provider

**Comment by xishang0128** [comment]
加了
