### ISSUE TITLE
[Bug] OpenClash上meta内核崩溃：不能加载大的rule-providers文件

### ISSUE THREAD

**Issue by mwnu** [MetaCubeX/mihomo#907]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-gcc64297

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
rule-providers:
  direct:
    type: http
    interval: 604800
    behavior: classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./rule_provider/direct.txt
  reject:
    type: http
    interval: 604800
    behavior: classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./rule_provider/reject.txt
  proxy:
    type: http
    interval: 604800
    behavior: classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./rule_provider/proxy.txt
```

### Mihomo log

```shell
2023-12-12 16:04:13 守护程序：检测到 Clash 内核崩溃，重启中...
2023-12-12 16:03:13 警告：OpenClash 启动成功，检测到您启用了IPv6的DHCP服务，可能会造成连接异常！
2023-12-12 16:03:13 第九步: 添加计划任务,启动进程守护程序...
2023-12-12 16:03:09 第八步: 重启 Dnsmasq 程序...
2023-12-12 16:03:09 提示：开始添加自定义防火墙规则...
2023-12-12 16:03:09 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
2023-12-12 16:03:08 提示：正在等待 TUN 接口启动...
2023-12-12 16:02:58 提示：检测到 Firewall4，使用 NFTABLE 规则...
2023-12-12 16:02:58 提示：DNS 劫持模式为 Dnsmasq 转发...
2023-12-12 16:02:58 第七步: 设置防火墙规则...
2023-12-12 16:02:58 第六步: 等待主程序下载外部文件...
2023-12-12 16:02:55 第五步: 检查内核启动状态...
2023-12-12 16:02:54 配置文件【/etc/openclash/self-file-test.yaml】测试成功...
2023-12-12 16:02:52 启动前调用内核测试配置文件...
2023-12-12 16:02:52 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2023-12-12 16:02:52 第四步: 启动主程序...
2023-12-12 16:02:52 提示：开始运行自定义覆写脚本...
2023-12-12 16:02:51 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:xxxxx】
2023-12-12 16:02:50 第三步: 修改配置文件...
2023-12-12 16:02:50 第二步: 组件运行前检查...
2023-12-12 16:02:50 第一步: 获取配置...
2023-12-12 16:02:50 OpenClash 开始启动...
2023-12-12 16:02:50 第六步：删除 OpenClash 残留文件...
2023-12-12 16:02:47 第五步: 重启 Dnsmasq 程序...
2023-12-12 16:02:47 第四步: 关闭 Clash 主程序...
2023-12-12 16:02:47 第三步: 关闭 OpenClash 守护程序...
2023-12-12 16:02:45 第二步: 删除 OpenClash 防火墙规则...
2023-12-12 16:02:45 第一步: 备份当前策略组状态...
2023-12-12 16:02:45 OpenClash 开始关闭...
2023-12-12 16:02:45 OpenClash 重新启动中...
2023-12-12 16:01:04【/tmp/openclash_last_version】下载失败：【curl: (35) Recv failure: Connection reset by peer】
```

### Description

相关问题：https://github.com/vernesong/OpenClash/issues/3665

我的配置文件遵循yaml和meta内核相关的语法要求，在merlinclash、shellclash、clash verge、meta android等客户端meta内核上测试正常使用，惟独在OpenClash无法启用。

经排查与闪存和内存大小无关，和路由器设置选项无关，和内核版本无关，而是OpenClash用meta内核加载外部资源配置是，对于大的rule-providers文件未能加载成功（测试文件见上方配置），会进入崩溃循环，用其他内核测试正常。

测试文件：

[direct](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt)https://[raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt)，包含 64808 条规则。
[proxy](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt)https://[raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt)，19030 条规则。
[reject](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt)https://[raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt](https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt)，66239 条规则。

有网友遇到类似的问题自行编译内核解决了，我尝试不成功。

那边说是内核的问题与客户端无关，由于没有相关日志显示，无法进一步调试。

我的路由器是AX6S-OpenWrt 23.05.0 官版，ARMv8 架构。

**Comment by SharerMax** [comment]
你这三个规则集的 `behavior` 不应该是 `domain` 吗？

**Comment by mwnu** [comment]
> `domain`

是domain，我配置里写的没错，粘贴上来的时候写错成了classical。

**Comment by yiiyahui** [comment]
最近试用meta，软路由上没试过，不过在mac和win平台上，无GUI在同样的配置下加载rule-providers（同款rule）内存占用大约是原clash pre版的2-3倍，后面试了下使用加载geoip和geosite文件的方式，回到一个比较正常的范围，但启动加载和大文件下载cpu和内存占用都不稳定。
或者你也试试用geosite替换掉rule-providers

**Comment by mwnu** [comment]
> 最近试用meta，软路由上没试过，不过在mac和win平台上，无GUI在同样的配置下加载rule-providers（同款rule）内存占用大约是原clash pre版的2-3倍，后面试了下使用加载geoip和geosite文件的方式，回到一个比较正常的范围，但启动加载和大文件下载cpu和内存占用都不稳定。 或者你也试试用geosite替换掉rule-providers

meta内核是相对不稳定，geosite好像不支持原版和Premium内核和某些客户端。

**Comment by yiiyahui** [comment]
我想表达的是加载同样数量的rule-providers，meta要比原clash的占用高。
而使用meta加载geosite/ip后，则回到一个比较正常的范围。（此时删除了所有rule-providers）
所以想说你是不是也可以试一下。

**Comment by mwnu** [comment]
> 我想表达的是加载同样数量的rule-providers，meta要比原clash的占用高。 而使用meta加载geosite/ip后，则回到一个比较正常的范围。（此时删除了所有rule-providers） 所以想说你是不是也可以试一下。

我配置一改所有的客户端都得跟着动，除非确定rule-providers无法加载只能用geosite，目前原版内核还能用，而远期得话的话我考虑切换到[sing-box](https://sing-box.sagernet.org/)。

**Comment by iKira** [comment]
AX6S的RAM才256MB，排掉系统占用的内存，可用内存更加少得可怜，小内存机器就不要用meta核了。

**Comment by lux5am** [comment]
I can confirm this. I think it's because the `rules` getting more and more complex make it harder to optimize the code.

**Comment by Rakau** [comment]
为啥不用Geoip:cn和match

**Comment by mwnu** [comment]
配置规则使用GEOSITE和GEOIP，openclash的Geodata 数据加载方式选择小内存模式可以切换到meta内核运行。

**Comment by blambin** [comment]
我也遇到同样的问题 我的路由器内存只有100m，所以我改成了黑名单模式，取消了最大的  reject.txt 和 direct.txt 就能运行了。
为什么我不用geoip，因为以ip来界定是否翻问题很多，一个域名对应多ip，或者反过来，在使用的过程中经常会遇到到莫名奇妙的问题。

**Comment by Skyxim** [comment]
@blambin 100M 你能跑起来就不错了

**Comment by mwnu** [comment]
256mb都经常运行崩溃，512mb还算稳定，估计用不了两年，得1gb内存才行。
