### ISSUE TITLE
[Bug] 没有了对chacha20-poly1305的支持：initialize error: unknown method: chacha20-poly1305

### ISSUE THREAD

**Issue by jacobin** [MetaCubeX/mihomo#910]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

clash-metaValpha-gcc64297

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml

选择chacha20-poly1305加密方法的节点
```

### Mihomo log

```shell
Openclash日志粘贴如下：

> ...
> 2023-12-10 00:24:59 错误：配置文件测试失败，请查看《_内核日志_》排查失败原因！
> 2023-12-10 00:24:59 配置文件【/etc/openclash/config/xxxxx.yaml】测试失败...
> 2023-12-10 00:24:58 配置文件下载成功，使用内核测试是否有错误...
> 2023-12-10 00:24:56 提示：检测到 Dnsmasq 正常工作，还原防火墙 DNS 劫持规则...
> 2023-12-10 00:24:56 开始更新配置文件【xxxxx】...
> ...

clash-metaValpha-gcc64297的《_内核日志_》

> 
> ...
> [ERRO][2023-12-09T23:59:29.132786284+08:00] proxy 880: ss 172.252.59.67:42572 initialize error: unknown method: chacha20-poly1305
> [INFO][2023-12-09T23:59:29.040051005+08:00] Start initial configuration in progress
> ...

```

### Description

在openwrt下用clash-metaValpha-gcc64297，对订阅下来yaml的进行校验检查，因为有chacha20-poly1305的节点，所以校验失败，结果是整个yaml都不可使用

**Comment by wwqgtxx** [comment]
https://shadowsocks.org/doc/aead.html#aead-ciphers
ss aead从来就没有`chacha20-poly1305`这种写法，谈何支持不支持

**Comment by sangyishuje1123** [comment]
额，chacha20-poly1305 是v2这边的写法
https://www.v2ray.com/chapter_02/protocols/shadowsocks.html

> - 加密方式（其中AEAD加密方式在 V2Ray 3.0 中加入）：
>   - aes-256-cfb
>   - aes-128-cfb
>   - chacha20
>   - chacha20-ietf
>   - aes-256-gcm
>   - aes-128-gcm
>   - **chacha20-poly1305 或称 chacha20-ietf-poly1305**

**Comment by NevadaCities** [comment]
@sangyishuje1123 您是否在找：https://github.com/shadowsocks/shadowsocks-libev/issues/507

**Comment by sangyishuje1123** [comment]
> @sangyishuje1123 您是否在找：[shadowsocks/shadowsocks-libev#507](https://github.com/shadowsocks/shadowsocks-libev/issues/507)

回的好快，重看了下我自己说的，确实也是没说清。
我本质上想回复的是题主，想表达的意思是这俩在v2输出是一个东西。

https://github.com/v2ray/v2ray-core/blob/d80440f3d57b45c829dbf513306f7adf9a0f3f76/infra/conf/shadowsocks.go#L27-L28

**Comment by jacobin** [comment]
> 额，chacha20-poly1305 是v2这边的写法 https://www.v2ray.com/chapter_02/protocols/shadowsocks.html
> 
> > * 加密方式（其中AEAD加密方式在 V2Ray 3.0 中加入）：
> >   
> >   * aes-256-cfb
> >   * aes-128-cfb
> >   * chacha20
> >   * chacha20-ietf
> >   * aes-256-gcm
> >   * aes-128-gcm
> >   * **chacha20-poly1305 或称 chacha20-ietf-poly1305**

我不能确信chacha20-poly1305和chacha20-ietf-poly1305是同一个东西

**Comment by jacobin** [comment]
> 额，chacha20-poly1305 是v2这边的写法 https://www.v2ray.com/chapter_02/protocols/shadowsocks.html
> 
> > * 加密方式（其中AEAD加密方式在 V2Ray 3.0 中加入）：
> >   
> >   * aes-256-cfb
> >   * aes-128-cfb
> >   * chacha20
> >   * chacha20-ietf
> >   * aes-256-gcm
> >   * aes-128-gcm
> >   * **chacha20-poly1305 或称 chacha20-ietf-poly1305**

[https://doc.libsodium.org/secret-key_cryptography/aead](https://doc.libsodium.org/secret-key_cryptography/aead)chacha20-poly1305和chacha20-ietf-poly1305不是同样的东西吧
