### ISSUE TITLE
1.17不支持vmess[Bug] 

### ISSUE THREAD

**Issue by fyhong** [MetaCubeX/mihomo#922]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

1.17

### Mihomo config

```yaml
proxies:
  - {name: xxx, server: mysite.com, port: 443, type: vmess, uuid: xxxuuid, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: mysite.com, network: ws, ws-opts: {path: prov2, headers: {Host: mysite.com}}}
```

### Description

相同的配置，1.16完全没问题，升到1.17就用不了
verge那个也反映了这个问题。
https://github.com/clash-verge-rev/clash-verge-rev/issues/127

**Comment by Skyxim** [comment]
`ws-opts: {path: prov2...`
尝试添加 / `ws-opts: {path: /prov2...`

**Comment by imshuai** [comment]
同样的，不支持vmess和vless的ws-opts.path为空，必须至少添加"/"

**Comment by wwqgtxx** [comment]
fixed in https://github.com/MetaCubeX/mihomo/commit/f16ebf9bfeaac55b2e203af9f2436c4897ac65b7
