### ISSUE TITLE
[Feature] Clash for Windows 更换最新版本内核启动失败，如何解决？ 求助

### ISSUE THREAD

**Issue by manchesterstoke** [MetaCubeX/mihomo#944]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

之前版本的内核可以直接替换，最新版请问有什么地方需要修改？

### Possible Solution

![287492508-6dc8720e-9a7a-4596-b36e-5f8c3cf59d16](https://github.com/MetaCubeX/mihomo/assets/33923008/7e1e53a2-00c3-465b-9cb1-55d9dcc89239)

**Comment by xishang0128** [comment]
@manchesterstoke cfw产生的问题自行解决,这不是内核的问题

**Comment by manchesterstoke** [comment]
> @manchesterstoke cfw产生的问题自行解决,这不是内核的问题

感谢指明问题所在
