### ISSUE TITLE
[Bug] UDP 不匹配规则

### ISSUE THREAD

**Issue by antonchen** [MetaCubeX/mihomo#945]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta alpha-1d3e9f4 linux amd64 with go1.21.5 Sun Dec 31 01:45:21 UTC 2023

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
- IP-CIDR,8.8.8.8/32,DNS,no-resolve
  - IP-CIDR,8.8.4.4/32,DNS,no-resolve
  - IP-CIDR,208.67.222.222/32,DNS,no-resolve
  - IP-CIDR,208.67.220.220/32,DNS,no-resolve
  - IP-CIDR,208.67.222.123/32,DNS,no-resolve
  - IP-CIDR,208.67.220.123/32,DNS,no-resolve
  - IP-CIDR,1.1.1.1/32,DNS,no-resolve
  - IP-CIDR,9.9.9.9/32,DNS,no-resolve
  - IP-CIDR,45.11.45.11/32,DNS,no-resolve
```

### Mihomo log

```shell
DEBU[2023-12-31T12:11:36.907102512+08:00] [Rule] use default rules
DEBU[2023-12-31T12:11:36.907187583+08:00] DNS UDP is not supported
DEBU[2023-12-31T12:11:36.907233778+08:00] 其它网络 UDP is not supported
INFO[2023-12-31T12:11:36.907362765+08:00] [UDP] 192.168.1.2:57501 --> 208.67.220.220:53 doesn't match any rule using DIRECT
DEBU[2023-12-31T12:11:37.042807245+08:00] TProxy listenLocalConn rAddr=208.67.220.220:53 lAddr=192.168.1.2:57501

DEBU[2023-12-31T12:18:26.990314145+08:00] [Rule] use default rules
DEBU[2023-12-31T12:18:26.990530412+08:00] 其它网络 UDP is not supported
INFO[2023-12-31T12:18:26.990814519+08:00] [UDP] 192.168.1.6:63851 --> 74.125.96.70:443 doesn't match any rule using DIRECT
DEBU[2023-12-31T12:18:27.124222053+08:00] [Rule] use default rules
DEBU[2023-12-31T12:18:27.124426739+08:00] 其它网络 UDP is not supported
INFO[2023-12-31T12:18:27.124648839+08:00] [UDP] 192.168.1.6:61373 --> 74.125.164.201:443 doesn't match any rule using DIRECT
```

### Description

我需要代理国外 DNS，刚刚发现设置 IP 规则后 UDP 请求不匹配规则。日志中带有 `规则名 UDP is not supported`。

已经测试 `1.6` 至 `alpha-1d3e9f4`，同时尝试 TCP 验证配置无问题。
同样 QUIC 也不能正常代理。

**Comment by PuerNya** [comment]
@antonchen 请检查你的出站有没有写 udp: true

**Comment by antonchen** [comment]
@PuerNya 

闹笑话了，看文档中配置 udp: true 我一直以为默认为 true，就想着默认就省略了。
感谢大佬解答。
