### ISSUE TITLE
[Bug] 逻辑规则不支持SRC-IP-SUFFIX

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/mihomo#948]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

Mihomo Meta v1.17.0 linux amd64 with go1.21.4 Sun Dec  3 01:02:22 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
- AND,((DOMAIN,api.epicgames.dev),(SRC-IP-SUFFIX,62a4:4cff:fecf:f8c/64)),Proxy
```

### Mihomo log

```shell
[31mERRO[0m[2023-12-31T23:07:34.454911652+08:00] rules[59] [AND,((DOMAIN,api.epicgames.dev),(SRC-IP-SUFFIX,62a4:4cff:fecf:f8c/64)),Proxy] error: payloadRule error
```

### Description

SRC-IP-CIDR可以，但SRC-IP-SUFFIX不行，SRC-IP-SUFFIX用于匹配IPV6主机，因为CN的家庭IPV6前缀是动态的

**Comment by Paulgudring** [comment]
好像没有`SRC-IP-SUFFIX`这个规则类型吧。为什么要这样处理，后缀是固定的吗？geoip的private或者lan不能覆盖吗？

**Comment by ShoukakuChuuCC** [comment]
> 好像没有`SRC-IP-SUFFIX`这个规则类型吧。为什么要这样处理，后缀是固定的吗？geoip的private或者lan不能覆盖吗？

文档里确实没有，但实际是有的，因为IPV6 SLAAC后缀是固定的，private或lan不能精确匹配到主机

**Comment by xishang0128** [comment]
@ShoukakuChuuCC 可以暂时先尝试使用sub-rule)

**Comment by Paulgudring** [comment]
> 文档里确实没有，但实际是有的，因为IPV6 SLAAC后缀是固定的，private或lan不能精确匹配到主机

@ShoukakuChuuCC  原来是这样。那应该是bug。我的话也会首用sub-rule，然后你可以试下入站规则？

**Comment by xishang0128** [comment]
@Paulgudring 逻辑规则并没有说支持所有规则类型(部分规则处理十分麻烦),所以这算不上是bug,只是没处理这个类型罢了

**Comment by ShoukakuChuuCC** [comment]
> @ShoukakuChuuCC 可以暂时先尝试使用sub-rule)

谢谢指导，sub-rule可以用

**Comment by xishang0128** [comment]
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/8b846857-8425-4c49-8d32-21da833c61e0)
![image](https://github.com/MetaCubeX/mihomo/assets/95160953/0f7a6cfb-78a8-419f-aea4-62ed1f54391a)
经测试,它是正常的,我觉得可能是你写法/环境的问题
