### ISSUE TITLE
[Feature] Specifies whether to add an IP-ASN traffic distribution rule

### ISSUE THREAD

**Issue by Wanderingkang** [MetaCubeX/mihomo#958]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Specifies whether to add an IP-ASN traffic distribution rule

**Comment by xishang0128** [comment]
Already added, try it, it should be fine
