### ISSUE TITLE
[Feature] 求助安卓开发中调用 mihomo 的思路

### ISSUE THREAD

**Issue by Cyberbolt** [MetaCubeX/mihomo#965]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

想到两种情况：

1.使用 Kotlin 开启 linux 子进程，运行 mihomo 的安卓可执行文件（如 `./mihomo -d ./`）（貌似在安卓10之后禁用了可执行文件，这种方法可能行不通）

2.将 mihomo 编译为 aar，Kotlin 将 mihomo 作为库调用

请问各位大佬是怎么做的，提供一下思路，非常感谢🙏

**Comment by xishang0128** [comment]
@Cyberbolt 可以参考clash meta for android

**Comment by Cyberbolt** [comment]
> clash meta for android

目前对安卓原生不是很熟悉，直接阅读源码比较困难，可以大致提供一下思路吗

**Comment by xishang0128** [comment]
@Cyberbolt 对内核打patch,ffi

**Comment by Cyberbolt** [comment]
> @Cyberbolt 对内核打patch,ffi

谢谢。没太理解，有没有相关的文档或教程可以提供？这种方法需要 root 权限吗

**Comment by Cyberbolt** [comment]
> @Cyberbolt 对内核打patch,ffi

看了一下 [https://github.com/MetaCubeX/ClashMetaForAndroid](https://github.com/MetaCubeX/ClashMetaForAndroid)，没有找到代码的何处调用了 clash meta

**Comment by xishang0128** [comment]
@Cyberbolt https://github.com/MetaCubeX/ClashMetaForAndroid/tree/init/core/src/main/golang

**Comment by xishang0128** [comment]
@Cyberbolt 可以实现

**Comment by Cyberbolt** [comment]
> @Cyberbolt https://github.com/MetaCubeX/ClashMetaForAndroid/tree/init/core/src/main/golang

竟然是直接通过原生代码来调用 Golang，[https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-android-arm64-alpha-4af94df.gz](https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-android-arm64-alpha-4af94df.gz) 存在的意义是什么呢

**Comment by xishang0128** [comment]
@Cyberbolt 这个Android是直接运行在Android的Linux层的,

**Comment by Cyberbolt** [comment]
> @Cyberbolt 这个Android是直接运行在Android的Linux层的,

Android 10 之后不允许在非 root 权限下运行，所以直接运行可执行文件实现不了？

**Comment by xishang0128** [comment]
@Cyberbolt 应用层得另外实现一些东西,或者你调用root权限去在Linux层运行release的二进制

**Comment by Cyberbolt** [comment]
@xishang0128 所以开发安卓应用的话还是得通过应用层实现，应该使用 Kotlin 和 Golang 通信。有一个问题，Linux、macOS、Windows 和 Android 的 Tun 层原理不同，可以调用同一套 Golang 代码运行？因为作者在实现时就作了系统判断吗，考虑了所有平台的情况

**Comment by xishang0128** [comment]
@Cyberbolt 都不太一样,是分开处理的,判断了OS

**Comment by xishang0128** [comment]
@Cyberbolt 进程获取也是

**Comment by xishang0128** [comment]
@Cyberbolt 如果你要原生Android调用,你得使用vpn service,然后把流量传递给内核,并且还得传递连接对应的参数

**Comment by Cyberbolt** [comment]
> @Cyberbolt 如果你要原生Android调用,你得使用vpn service,然后把流量传递给内核,并且还得传递连接对应的参数

Linux、macOS、Windows 上的 clash meta 直接内置了 Tun，Android 需要自己调用 vpn service 吗？具体调用哪个方法来传递 Tun 流量，需要我自己阅读 clash meta 的 Go 源码吗

**Comment by xishang0128** [comment]
@Cyberbolt Android应用没法直接使用tun,得通过vpn service的api启动,可以看clash meta for Android的处理

**Comment by PuerNya** [comment]
@Cyberbolt 请自行学习 android 开发

**Comment by xishang0128** [comment]
@Cyberbolt 是可以,以前iOS有个mfi,但是不做了

**Comment by Cyberbolt** [comment]
> > @Cyberbolt 如果你要原生Android调用,你得使用vpn service,然后把流量传递给内核,并且还得传递连接对应的参数
> 
> 如果是这种实现方法，理论上 iOS 也可以用 clash meta？调用 NetworkExtension 将流量传递给 clash meta 就行了。但我看官方文档并没有说 clash meta 支持 iOS

**Comment by xishang0128** [comment]
@Cyberbolt 你可能得自己修改一些代码,meta初始占用内存可能会超过ne应用可调用的上限(iOS15+为50m)

**Comment by Cyberbolt** [comment]
> @Cyberbolt 你可能得自己修改一些代码,meta初始占用内存可能会超过ne应用可调用的上限(iOS15+为50m)

好的，谢谢指点

**Comment by xishang0128** [comment]
@Cyberbolt 具体的得学习对应平台的原生开发,然后对meta的流量入口做一些调整,接入平台自己的vpn接口

**Comment by Cyberbolt** [comment]
@xishang0128 原生开发没什么问题，但是将 clash meta (Golang) 作为库调用的话，没有相关的 API 文档，可能需要研究下。感谢你的耐心指点！

**Comment by Cyberbolt** [comment]
@xishang0128 你好，我看了下 clash meta 的入站代理支持 Tunnel，意味着安卓的 VPNService 拿到的流量可以直接转发给 Tunnel 吗？像下面这样配置监听一个端口，安卓在拿到 VPNService 的 ip packet 后直接转发到这个端口就行了？


```yaml
listeners:
- name: tunnel-in
  type: tunnel
  port: 10816
  listen: 0.0.0.0
  network: [tcp, udp]
  target: target.com
```

**Comment by xishang0128** [comment]
@Cyberbolt 这个tunnel只是一个端口转发工具,并没有接受流量处理的功能,你可能需要自己实现一个入站

**Comment by xishang0128** [comment]
@Cyberbolt Android应用层的东西都得自己从原生实现,用原有的流量接管方式几乎只能在Linux底层使用

**Comment by Cyberbolt** [comment]
> @Cyberbolt 这个tunnel只是一个端口转发工具,并没有接受流量处理的功能,你可能需要自己实现一个入站

我看了一下这个 Tunnel 指的是 inbound，应该就是指的入站吧？

**Comment by xishang0128** [comment]
@Cyberbolt 这个listeners的tunnel是监听一个地址,转发到target

**Comment by Cyberbolt** [comment]
> @Cyberbolt Android应用层的东西都得自己从原生实现,用原有的流量接管方式几乎只能在Linux底层使用

举例一下呢，如果我用安卓版的 tun2socks 将流量转到本地监听的 socks 服务器，然后再转到 v2ray trojan 等协议，不还是流量接管吗，和 PC 是一个原理。还是说安卓不能在本地监听 TCP 端口来接管流量？无法建立 Socket Server 吗

**Comment by xishang0128** [comment]
@Cyberbolt 指的是路由/设置系统代理,而不是只是一个socks/http监听

**Comment by Cyberbolt** [comment]
> @Cyberbolt Android应用层的东西都得自己从原生实现,用原有的流量接管方式几乎只能在Linux底层使用

安卓在拿到 VPNService 的流量后，通过 tun2socks 转到 clash meta 的入站，是否可以这样实现😄

**Comment by xishang0128** [comment]
@Cyberbolt 可以,但是这样会缺失信息,比如包名/来源等

**Comment by Cyberbolt** [comment]
@xishang0128 好吧，不好意思，我只做过传输层以上的开发。弱弱的问下，我自己接管 tun2socks 的 TCP / UDP 包后，都是标准的 socks 5 协议，信息都有。这里的丢失信息是指 clash meta 做的一些标记吗

**Comment by xishang0128** [comment]
@Cyberbolt 你用tun2socks之后,所有的来源都是这个socks,而不是实际来源

**Comment by Cyberbolt** [comment]
> @Cyberbolt 你用tun2socks之后,所有的来源都是这个socks,而不是实际来源

tun2socks 是从 VPNService 转到 clash meta 监听的 socks 5 端口，meta 拿到的就是源数据包吧

**Comment by xishang0128** [comment]
@Cyberbolt 经过tun2socks之后就不是原始的数据包了,而是tun2socks发起的,发送给一个socks in的数据包

**Comment by Cyberbolt** [comment]
@xishang0128 您意思是，tun2socks 方案的全流程是: Tun -> socks1 -> socks2(meta inbound) -> v2ray(meta outbound) 吗？

**Comment by xishang0128** [comment]
@Cyberbolt 不,我指的是,meta能拿到的信息只有tun2socks这个socks请求者的信息,其他的信息都没了

**Comment by PuerNya** [comment]
@Cyberbolt 在你本地包装 socks 流量的时候，已经丢失很多信息，大家都是靠 socket-in 直接拿到全部信息的

**Comment by Cyberbolt** [comment]
> @Cyberbolt 经过tun2socks之后就不是原始的数据包了,而是tun2socks发起的,发送给一个socks in的数据包

如果丢失了原始数据包，会对什么功能造成影响呢？

**Comment by PuerNya** [comment]
@Cyberbolt 所有 process 相关信息都会消失，处理效率也会相对变低

**Comment by xishang0128** [comment]
@Cyberbolt 几乎所有来源信息都会消失

**Comment by Cyberbolt** [comment]
@xishang0128 您的意思是从网络层到传输层丢失的信息吧？但是 v2ray 这类代理也不需要更多信息了？在 Tun 模式之前 v2ray 桌面版一直使用的系统代理

**Comment by PuerNya** [comment]
@Cyberbolt 那是 v2ray……clash 支持的规则类型更多，自然需要更多信息

**Comment by xishang0128** [comment]
@Cyberbolt 这样会导致配置中的一些路由规则不可用

**Comment by Cyberbolt** [comment]
@xishang0128 好吧，就是对 meta 而言，丢失了很多信息导致功能实现受限制

**Comment by Cyberbolt** [comment]
@xishang0128 我理解您的意思了，非常感谢！是否可以总结为，如果我指实现 v2ray 的全部功能，使用 tun2socks 和其他方法就没有区别？

**Comment by Cyberbolt** [comment]
@xishang0128 对 v2ray 的路由匹配和 DNS 应该没影响吧？

**Comment by xishang0128** [comment]
@Cyberbolt 对dns可能有影响,路由匹配没影响

**Comment by Cyberbolt** [comment]
> @Cyberbolt 对dns可能有影响,路由匹配没影响

会不会出现流量死循环的情况🤣例如，从 VPNService 到 meta 的 socks in，meta 的 v2ray 在进行直连的时候。流量又回到 VPNService

**Comment by xishang0128** [comment]
@Cyberbolt 如果都是应用本身的子进程,那不会,如果不是,用vpn service的api绕过应用即可

**Comment by Cyberbolt** [comment]
@xishang0128 好的，再次感谢您的答疑！我的实现阉割了 clash 这么多功能🤣到时候都不敢开源了

**Comment by xishang0128** [comment]
@Cyberbolt 不,是由tun2socks发起的,而不是转发的,因为这是不同的协议

**Comment by Paulgudring** [comment]
cfa 3.0.3 `Kr328`应该是做了两个技术栈，在root模式下能做到接近 linux 的体验，也应该是有对内核做patch的。可惜没有开源，估计也难再见了。

**Comment by xishang0128** [comment]
@Paulgudring 没有,shizuku模式直接运行的clash原生tun,clash premium的tun直接可以在Linux层工作的,只是patch了一个socket用于控制)

**Comment by FrontMage** [comment]
@Cyberbolt 安卓下用gvisor就行了，安卓启动vpn service以后会给你一个fd，拿这个fd就可以起一个fd based endpoint给gvisor，然后有基于gvisor的tun2socks，它里面有个transport handler里面会把流量用golang conn的形式塞给你，拿到以后根据这个conn你创建对应的clash metadata然后直接丢进clash的tunnel里面有个TCPIn和UDPIn这两个channel
上面说的process信息丢失的问题用这个方法就不会遇到，还是能根据conn拿到source addr和remote addr从而拿到是哪个package发的，因为这里其实没用到tun2socks，只是用到了里面创建tcpip stack和自动poll的一些方法

@xishang0128 iOS内存不用担心，起来以后大约占个18-20mb，gc周期设置短一点，即使压力大的时候也就30，profile会发现大部分内存占用是因为io copy，这个只要及时释放问题不大的
