### ISSUE TITLE
[Feature] 更新docker版

### ISSUE THREAD

**Issue by DoyoDia** [MetaCubeX/mihomo#966]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

https://hub.docker.com/r/metacubex/clash-meta/tags
官方docker已经两个月没更新过了，action里docker的部分被跳过了，背后有什么原因吗（）
如果没啥问题的话可以更新一下嘛

**Comment by Larvan2** [comment]
https://hub.docker.com/r/metacubex/mihomo

**Comment by DoyoDia** [comment]
谢
