### ISSUE TITLE
缩减二进制文件大小

### ISSUE THREAD

**Issue by qwerr0** [MetaCubeX/mihomo#968]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

使用 upx 工具可以压缩二进制文件，经过测试，构建出来的二进制文件直接从28.7MB压缩到了9.63MB。
好在 upx 不会影响程序运行时的性能，我也简单对比了一下跑起来后占用的内存情况，也是一模一样，不知能否引入这项工具？
如果不能引入，希望写入文档中，给哪些在储存紧张的硬路由器用户知道还有这样一个选择。

**Comment by xishang0128** [comment]
@qwerr0 upx运行时会消耗更多的CPU/内存,如有需要自己压缩即可,官方不会提供压缩,另外upx的壳对于一些平台会报毒

**Comment by hass-demacia** [comment]
现在内核原来越大。原来的路由器设备，已经跑不了最新内核了
——————————————————
47M -> 16M 感谢
