### ISSUE TITLE
[Feature] 希望支持配置mptcp

### ISSUE THREAD

**Issue by ha-ku** [MetaCubeX/mihomo#972]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

xray在1.8.6中引入了对mptcp的支持，我看目前这边是还没有提供相关的配置的？请问有打算跟进吗？

**Comment by xishang0128** [comment]
@ha-ku https://github.com/MetaCubeX/mihomo/blob/d2d8c0115cb464b93ffee04f4768ebc35d49d4ec/config/config.go#L89C7-L89C7

**Comment by ha-ku** [comment]
> @ha-ku https://github.com/MetaCubeX/mihomo/blob/d2d8c0115cb464b93ffee04f4768ebc35d49d4ec/config/config.go#L89C7-L89C7

outbound那边请问有支持吗？

**Comment by xishang0128** [comment]
@ha-ku https://github.com/MetaCubeX/mihomo/blob/d2d8c0115cb464b93ffee04f4768ebc35d49d4ec/adapter/outbound/base.go#L156C31-L156C31

**Comment by ha-ku** [comment]
感谢……
