### ISSUE TITLE
支持设定不同的 /proc 路径,以便支持在 docker 中使用 process 规则

### ISSUE THREAD

**Issue by chisaato** [MetaCubeX/mihomo#98]
当在 docker 中使用 clash 的时候, /proc 是与主系统隔离的.   
但是设定 CAP 之后依然可以通过与 netlink 通信得到进程信息,但是却无法查询 /proc 取得进程名.
参考一些监控工具 (Prometheus) 的做法,他们可以在 docker 中只读挂载 /proc 并添加选项覆盖默认 /proc 路径.

**Comment by xishang0128** [comment]
考虑到这个 issue 没有使用正确的模板格式，我们决定关闭它。
Considering that this issue did not use the correct template format, we decided to close it.
