### ISSUE TITLE
mihomo无法访问, 但是chrome可以访问 [Feature] 

### ISSUE THREAD

**Issue by Sanchew** [MetaCubeX/mihomo#986]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我以为是443被封了,  但我发现浏览器可以正常访问, 我设置了ua也设置fingerprint但都不启作用, 
telnet 也连不上,

**Comment by PuerNya** [comment]
@Sanchew 请提供材料和验证描述而不是没头没尾的来一句谁都看不懂的

**Comment by Sanchew** [comment]
> @Sanchew 请提供材料和验证描述而不是没头没尾的来一句谁都看不懂的

我不知道该如何提供地址, 简单来说就是我的服务器被墙了, 但并不是完全被Block了, mihomo连接服务器会timeout 我测试了firefox和safari都不可以访问,   但chrome中可以正常访问被Block的端口, 同时我设置了mihomo的fingerprint为chrome也不启作用, 这个问题很令我费解
