### ISSUE TITLE
[Feature] 支持在 nameserver-policy 中为 DIRECT 出站设置DNS

### ISSUE THREAD

**Issue by iKun10001** [MetaCubeX/mihomo#988]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

感觉直连域名用默认DNS是最合适的

### Possible Solution

或者 为 DIRECT 设置默认的DNS 比如  system  感觉还是自定义更棒一些

**Comment by Paulgudring** [comment]
如果在fake-ip的情况下，就只有直连和IP规则的会查询内置DNS服务器。

你提的想法是这种吗：#863？应该是对不上的。proxy-group，specific rule type 通过rules下的分流规则才成完整的分流链，相当于specific rule type (domain, process, ...) --> rules --> (proxy-group --> outbound | outbound)。nameserver-policy能够得到domain, geo, rule-set 的指定，但是不能得到 proxy-group / outbound 的指定。

因此，你可以选择将需要指定DIRECT的那些规则放入nameserver-policy，或者直接将默认dns改为system。

**Comment by Skyxim** [comment]
NameServer 即是 DIRECT DNS
