### ISSUE TITLE
[Bug] 安卓手机上环境变量TZ设置时区无效

### ISSUE THREAD

**Issue by him007** [MetaCubeX/mihomo#989]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.0

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
export TZ=Asia/Shanghai
clash -d /data/adb/box/clash -f /data/adb/box/clash/config.yaml
```

### Description

在安卓手机上设置`export TZ=Asia/Shanghai`
后，`echo $TZ` 输出 `Asia/Shanghai` ,但是运行clash输出的日志还是UTC时区, 搜索了一下这应该会对go程序生效的，在 [https://github.com/MetaCubeX/mihomo/issues/879](url) 看到别人手机截图clash输出也是UTC时区。
下面是我手机上的截图
![Screenshot_2024-01-17-03-58-21-106_com termux](https://github.com/MetaCubeX/mihomo/assets/3102365/b9b2fc08-f3ab-4ce8-9938-5efdaceeb976)

**Comment by xishang0128** [comment]
@him007 对于安卓设备,一些系统变量读取异常是正常的,安卓并不是标准Linux设备,不能用标准Linux设备做对比

**Comment by him007** [comment]
> @him007 对于安卓设备,一些系统变量读取异常是正常的,安卓并不是标准Linux设备,不能用标准Linux设备做对比

安卓并不是标准Linux设备,不能用标准Linux设备做对比
这个我理解
一些系统变量读取异常是正常的
这个我理解不了
不清楚go在Windows是怎么运行的

**Comment by xishang0128** [comment]
@him007 就是说,android编译不吃在linux上有用的系统变量

**Comment by him007** [comment]
> @him007 就是说,android编译不吃在linux上有用的系统变量

那么，请问怎么解决我遇到的问题呢？我需要在安卓上clash输出的时间和我的时区一致

**Comment by fakeboboliu** [comment]
> 那么，请问怎么解决我遇到的问题呢？我需要在安卓上clash输出的时间和我的时区一致，而不是相差8个小时。

很简单，GOOS=linux

**Comment by him007** [comment]
> > 那么，请问怎么解决我遇到的问题呢？我需要在安卓上clash输出的时间和我的时区一致，而不是相差8个小时。
> 
> 很简单，GOOS=linux

不起作用。
找到了2017年到现在还没关闭的issue  [time: time.Local is always UTC on Android](https://github.com/golang/go/issues/20455) ，可能跟这个有关系。
好像go程序不会读取TZ变量判断时区，而是通过tzdate文件。

**Comment by fakeboboliu** [comment]
> 不起作用。 找到了2017年到现在还没关闭的issue [time: time.Local is always UTC on Android](https://github.com/golang/go/issues/20455) ，可能跟这个有关系。 好像go程序不会读取TZ变量判断时区，而是通过tzdate文件。

我在 clash 提过这个问题 https://github.com/clash-backup/clash/commit/1855e187341609b7f9699ebe9cfb15dd8bc4b67b 但是 meta 看起来没有合上游

**Comment by him007** [comment]
> > 不起作用。 找到了2017年到现在还没关闭的issue [time: time.Local is always UTC on Android](https://github.com/golang/go/issues/20455) ，可能跟这个有关系。 好像go程序不会读取TZ变量判断时区，而是通过tzdate文件。
> 
> 我在 clash 提过这个问题 https://github.com/clash-backup/clash/commit/1855e187341609b7f9699ebe9cfb15dd8bc4b67b 但是 meta 看起来没有合上游
> 

用了time/tzdata这个包会增加程序体积450KB左右

**Comment by him007** [comment]
总结一下我找到的处理方法：
- 1 导入time/tzdata，但会让程序增大体积450KB左右
- 2 通过getprop persist.sys.timezone判断时区，可以加个判断是安卓才允许此函数 [https://github.com/golang/go/issues/20455#issuecomment-342287698](https://github.com/golang/go/issues/20455#issuecomment-342287698)
- 3 通过系统环境变量TZ判断时区 [https://github.com/golang/go/issues/20455#issuecomment-504363523](https://github.com/golang/go/issues/20455#issuecomment-504363523)

**Comment by xishang0128** [comment]
应该可以了

**Comment by him007** [comment]
> 应该可以了

好，测试正常
