### ISSUE TITLE
有规则,但经常发生直连[Bug] 

### ISSUE THREAD

**Issue by Sanchew** [MetaCubeX/mihomo#992]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

v1.18.0

### What OS are you seeing the problem on?

macOS

### Mihomo config

```yaml
规则如下
- DOMAIN-SUFFIX,openai.com,🇭🇰 Fallback
```

### Description

日志显示
[UDP] 198.18.0.1:58688(Google Chrome Helper) --> chat.openai.com:443 doesn't match any rule using DIRECT
过一段时间就好了,  但是经常又这样了

**Comment by xishang0128** [comment]
@Sanchew 你的节点不支持udp(没有udp true),继续向下匹配了

**Comment by bakasine** [comment]
> @Sanchew 你的节点不支持udp(没有udp true),继续向下匹配了
并不是 我也有这种情况 多重启几次游戏又能正常代理

**Comment by xkww3n** [comment]
QUIC协议是基于UDP的，时好时坏是因为有的时候Chrome会用QUIC协议尝试连接，连不上又会回退到传统的TCP协议，在所有规则的前面添加一个 `AND,((DST-PORT,443),(NETWORK,UDP)),REJECT-DROP` 规则屏蔽掉QUIC试试
