### ISSUE TITLE
[Bug] hysteria2协议在Linux系统下有证书问题

### ISSUE THREAD

**Issue by yyxida** [MetaCubeX/mihomo#993]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 mihomo 或 mihomo Alpha 版本 Ensure you are using the latest version of Mihomo or Mihomo Alpha from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Mihomo 核心的问题，并非我所使用的 Mihomo 衍生版本（如 OpenMihomo、KoolMihomo 等）的特定问题 This is an issue of the Mihomo core *per se*, not to the derivatives of Mihomo, like OpenMihomo or KoolMihomo. 

### Mihomo version

alpha-460cc24

### What OS are you seeing the problem on?

Linux

### Mihomo config

```yaml
- {name:hysteria2, server: xxxxxxx.aaaaaa.com, port: xxxxx, type: hysteria2, password: xxxxxxxxxx, up: "30 mbps", down: "300 mbps"}
```

### Mihomo log

```shell
[TCP] dial 🚀 节点选择 (match DomainKeyword/github) 192.168.2.5:40006 --> raw.githubusercontent.com:443 error: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Description

在软路由上的openclash-meta内核（alpha-gcc64297）和docker里（alpha-460cc24）运行，链接hysteria2就会有这个证书问题，docker下尝试apk add --no-cache ca-certificates依然报错certificate signed by unknown authority。Windows下使用clash-verge（1.18.0内核）链接hysteria2没有这个问题。

**Comment by xishang0128** [comment]
@yyxida OpenWrt/docker的时间对吗,以及证书是否是知名ca颁发的证书

**Comment by yyxida** [comment]
> @yyxida OpenWrt/docker的时间对吗,以及证书是否是知名ca颁发的证书

OpenWrt/docker的时间是正确的。
节点是自己搭建的，使用的是zerossl的ecc证书，docker容器中cat /etc/ca-certificates.conf可以找到其根证书mozilla/USERTrust_ECC_Certification_Authority.crt正确引用。

**Comment by luckyyyyy** [comment]
在 hy2中 同样遇到了 context deadline exceeded 错误

目前已知的信息是 在v1.18.0的版本中，会提示H3_REQUEST_CANCELLED (local)，但不会造成两个节点都不可以使用的问题。
但在之后的版本，只要一旦某个节点出现问题，另一个hysteria2节点也无法使用。


缓解方式，在服务端配置quic参数后不再出现

例如
```yaml
quic:
  initStreamReceiveWindow: 16777216
  maxStreamReceiveWindow: 16777216
  initConnReceiveWindow: 33554432
  maxConnReceiveWindow: 33554432

**Comment by Skyxim** [comment]
是否尝试过全链证书

**Comment by wuziwei** [comment]
> > 是否尝试过全链证书
> 
> 
> 
> 我这边用的是amce部署的--fullchain-file
> 
> 另外断流的报错是 context deadline exceeded 错误。好像这个报错和证书无关？
> 
> 另外这边的设置是所有hy2节点都是 skip-cert-verify: true 的

请教一下这个全链证书是修改服务端hy2里面的证书路径吗，还是说linux客户端的，可否分享一下具体操作，最近也遇到这问题，谢谢

**Comment by yyxida** [comment]
修改服务器端配置文件指向的证书文件，acme.sh申请的话就是full-ca证书文件

**Comment by wuziwei** [comment]
> 修改服务器端配置文件指向的证书文件，acme.sh申请的话就是full-ca证书文件

好的，谢谢，看了之前acme申请的里面确实有fullchain.cer.我来替换一下谢谢
